#!/usr/bin/env python3
"""R1-8 (v3.96): separate repeat execution blocks from temporally
independent confirmation epochs.

Referee 1's point is exact: two blocks obtained on the same night do not
provide the confirmation power of two separated by months. The paper had
been quoting the number of systems with more than one searched block as
though it were the number with a confirmation opportunity. It is not.

An "independent epoch" is defined here as a separation of more than one
day between a system's blocks. The threshold is stated rather than tuned:
one day is the point beyond which ALMA scheduling no longer places
observations in the same execution session.
"""
import collections
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.96.csv'))))
EP = json.load(open(os.path.join(HERE, 'epochs_v386.json')))
OUT = os.path.join(HERE, 'survey_numbers_round56.tex')
SEP = 1.0

mjd = EP['mjd']
bysys = collections.defaultdict(set)
for r in CAT:
    bysys[r['system_id']].add(r['eb'])

c = collections.Counter()
for sysid, ebs in bysys.items():
    ts = sorted(mjd[e] for e in ebs if e in mjd)
    if len(ts) < 2:
        c['one'] += 1
        continue
    gaps = [ts[i + 1] - ts[i] for i in range(len(ts) - 1)]
    span = ts[-1] - ts[0]
    if max(gaps) < SEP:
        c['sameday'] += 1
    elif span < 30:
        c['days'] += 1
    elif span < 365:
        c['months'] += 1
    else:
        c['years'] += 1
tot = sum(c.values())
indep = c['days'] + c['months'] + c['years']
multi = tot - c['one']
assert c['one'] + c['sameday'] + indep == tot, 'epoch split must close'

L = ['%% GENERATED by epochsplit_v396.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('EpTot', '%d' % tot)
m('EpOne', '%d' % c['one'])
m('EpSameDay', '%d' % c['sameday'])
m('EpMulti', '%d' % multi)
m('EpIndep', '%d' % indep)
m('EpIndepPct', '%.0f' % (100.0 * indep / tot))
m('EpDays', '%d' % c['days'])
m('EpMonths', '%d' % c['months'])
m('EpYears', '%d' % c['years'])
m('EpSep', '%.0f' % SEP)
# R1-5: the systems that cannot provide independent temporal confirmation at
# all -- observed once, or with every block inside one day.  Asserted against
# the total so this and EpIndep cannot drift apart.
assert c['one'] + c['sameday'] + indep == tot, (
    'temporal partition does not close: %d one + %d same-day + %d '
    'independent != %d systems' % (c['one'], c['sameday'], indep, tot))
m('EpNoConfirm', '%d' % (c['one'] + c['sameday']))
open(OUT, 'w').writelines(L)
print('%s: %d macros' % (os.path.basename(OUT), len(L) - 1))
print('  systems %d: one block %d | multi-block %d, of which %d have ALL '
      'blocks within %.0f d' % (tot, c['one'], multi, c['sameday'], SEP))
print('  temporally independent epochs: %d (%.0f per cent) -- days %d, '
      'months %d, years %d' % (indep, 100.0 * indep / tot, c['days'],
                               c['months'], c['years']))
