#!/usr/bin/env python3
r"""Re-rank the stage-1 windows against a LOCALLY normalised statistic.

The pipeline divides every position in a window by one global noise
scale, while the true primary-beam-corrected noise varies smoothly with
radius across the annulus the controls occupy. That is a measurement
problem, and the honest repair is to fix the normalisation rather than to
debit the star afterwards.

The control probes come from one fixed seed, so every stored control
value can be paired with its radius. Standardise each probe within its
own radius bin, standardise the star on the innermost bin (the star sits
inside the annulus), and re-rank. No new data are needed and no free
parameter enters: there is no stellar debit in this calculation.

Writes localnorm_v384.json and survey_numbers_round33.tex.
"""
import csv, json

import numpy as np

R_IN, R_OUT, NPROBE, SEED, NBIN = 0.14, 0.78, 512, 20260825, 8
rng = np.random.default_rng(SEED)
U = np.sqrt(rng.uniform(R_IN ** 2, R_OUT ** 2, NPROBE))
edges = np.quantile(U, np.linspace(0, 1, NBIN + 1))
binid = np.clip(np.digitize(U, edges[1:-1]), 0, NBIN - 1)
FLOOR = 1.0 / (NPROBE + 1)

EXP = json.load(open('frozen_export_v3.81_survey.json'))['rows']
CAT = {}
for r in csv.DictReader(open('per_target_results_v3.96.csv')):
    CAT[(r['eb'], round(min(float(r['flo_GHz']), float(r['fhi_GHz'])), 4))] = r

seen, rows = set(), []
for r in EXP:
    c = np.asarray(r.get('ctrl_all') or [], float)
    if c.size != NPROBE or r['star_snr'] is None:
        continue
    key = (r['eb'], round(min(r['flo'], r['fhi']), 4))
    cat = CAT.get(key)
    if cat is None or cat['stage1_flag'] != 'True' or key in seen:
        continue
    seen.add(key)
    g = (1 + int((c >= r['star_snr']).sum())) / (c.size + 1.0)
    z = np.empty_like(c)
    for b in range(NBIN):
        sel = binid == b
        md = np.median(c[sel])
        sd = 1.4826 * np.median(np.abs(c[sel] - md)) or 1.0
        z[sel] = (c[sel] - md) / sd
    sel0 = binid == 0
    md0 = np.median(c[sel0])
    sd0 = 1.4826 * np.median(np.abs(c[sel0] - md0)) or 1.0
    zs = (r['star_snr'] - md0) / sd0
    l = (1 + int((z >= zs).sum())) / (z.size + 1.0)
    rows.append(dict(star=cat['star_name'].split('  Gaia')[0].strip(),
                     band=cat['band'], eb=r['eb'], tstar=r['star_snr'],
                     rank_global=g, rank_local=l,
                     flag_global=bool(g <= FLOOR), flag_local=bool(l <= FLOOR)))
rows.sort(key=lambda d: -d['tstar'])
same = sum(1 for d in rows if d['flag_global'] == d['flag_local'])
lost = [d for d in rows if d['flag_global'] and not d['flag_local']]
json.dump(dict(n=len(rows), n_same=same, n_lost=len(lost), rows=rows,
               lost=[d['star'] for d in lost]),
          open('localnorm_v384.json', 'w'), indent=1)

M = ['\\newcommand{\\LocNormN}{%d}' % len(rows),
     '\\newcommand{\\LocNormSame}{%d}' % same,
     '\\newcommand{\\LocNormLost}{%d}' % len(lost),
     '\\newcommand{\\LocNormKept}{%d}' % (len(rows) - len(lost)),
     '\\newcommand{\\LocNormLostList}{%s}'
     % ', '.join(d['star'].split(' Gaia')[0].replace('CP-72','CP$-$72') for d in lost)]
open('survey_numbers_round33.tex', 'w').write(
    '% generated by localnorm_v384.py -- do not edit\n' + '\n'.join(M) + '\n')
print('stage-1 windows %d | unchanged %d | lose the flag %d: %s'
      % (len(rows), same, len(lost), ', '.join(d['star'] for d in lost)))
