#!/usr/bin/env python3
"""R1-4 (v3.96): report the sensitivity as a DISTRIBUTION across systems,
not as a single median.

Referee 1: "I require the authors to make the sensitivity distribution,
rather than the median sensitivity, the primary quantitative result.
Specifically, in the Abstract and Conclusions, immediately following the
1.5e15 W median, state how many of the 60 Class-A systems have P90^sel
below physically useful benchmark powers -- for example 1e14, 1e15, 1e16
and 1e17 W."

P90^sel is built exactly as make_fig_classa_sens.py builds it, so the
numbers quoted in the text and the curve plotted in Fig. 7a cannot drift
apart: for each fine window, P_eff x P90FAC x (ring maximum / trigger),
minimised over each system's windows.  The two are cross-asserted below.

Writes survey_numbers_round62.tex.
"""
import csv
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'survey_numbers_round62.tex')

ROWS = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.96.csv'))))

# the trigger-to-P90 factor, read from the same frozen round the figure uses
P90FAC = None
for fn in sorted(os.listdir(HERE)):
    if fn.startswith('survey_numbers_round') and fn.endswith('.tex'):
        for line in open(os.path.join(HERE, fn)):
            if '\\newcommand{\\PNinetyOverTrig}' in line:
                P90FAC = float(line.split('}{')[1].split('}')[0])
assert P90FAC, 'PNinetyOverTrig not found; P90^sel cannot be built'


def F(x):
    try:
        v = float(x)
        return v if v > 0 else None
    except (TypeError, ValueError):
        return None


bestsel = {}
for r in ROWS:
    if r['resolution_class'] != 'fine':
        continue
    e, c = F(r['eirp_eff_total_W']), F(r['ctrl_max_snr'])
    if e is None or not c:
        continue
    sel = e * P90FAC * c / 5.0
    s = r['system_id']
    if s not in bestsel or sel < bestsel[s]:
        bestsel[s] = sel

vals = sorted(bestsel.values())
n = len(vals)
assert n, 'no systems with a P90^sel'
med = vals[n // 2] if n % 2 else 0.5 * (vals[n // 2 - 1] + vals[n // 2])

BENCH = [1e14, 1e15, 1e16, 1e17]
cnt = {t: sum(1 for v in vals if v <= t) for t in BENCH}

# the distribution must be consistent with the median the paper quotes
assert cnt[1e15] <= n // 2 + 1 and cnt[1e16] >= n // 2, (
    'the benchmark counts (%s) are inconsistent with a median of %.2e'
    % (cnt, med))

L = ['%% GENERATED by sensdist_v396.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


def sci(x):
    e = int(math.floor(math.log10(x)))
    return '%.1f\\times10^{%d}' % (x / 10.0 ** e, e)


m('SdNSys', '%d' % n)
m('SdMed', sci(med))
# LaTeX macro names must be letters only -- \SdN14 parses as \SdN then a
# literal "14", which typesets in the preamble and breaks the build
WORD = {14: 'Fourteen', 15: 'Fifteen', 16: 'Sixteen', 17: 'Seventeen'}
for t in BENCH:
    k = WORD[int(round(math.log10(t)))]
    m('SdN%s' % k, '%d' % cnt[t])
    m('SdPct%s' % k, '%d' % round(100.0 * cnt[t] / n))
m('SdMin', sci(vals[0]))
m('SdMax', sci(vals[-1]))
open(OUT, 'w').writelines(L)

print('sensdist: %d systems, median %.2e' % (n, med))
for t in BENCH:
    print('   <= %.0e : %2d systems (%d%%)' % (t, cnt[t],
                                               round(100.0 * cnt[t] / n)))
