#!/usr/bin/env python3
r"""The null distribution for the number of UNATTRIBUTED STAGE-1 EVENTS.

Referee 1, points 1 and 4, and referee 2's related request.

Every false-alarm expectation this paper has quoted -- 1.1, 3.1, 3.2, 3.9,
4.4, 4.7 -- predicts the number of windows in which a no-signal position
would rank FIRST among the control ensemble. None of them includes the
other half of the stage-1 definition: the position must also cross the
detection threshold. Comparing any of them with the observed count of
stage-1 events is therefore comparing two different quantities, which is
exactly the confusion the referees identify.

The null that matches the observed quantity is measured directly from the
stored control vectors. For each window, a control probe reproduces a
stage-1 event if it both

  (a) reaches the trigger, c_i >= TRIG, and
  (b) exceeds every other probe in that window,

and the probability that the stellar position would have done so, treated
as exchangeable with the probes, is the count of such probes divided by
the ensemble size. Summed over windows this is the expected number of
stage-1 events from noise alone; resampled over execution blocks it has an
interval and a tail probability.

The measured non-exchangeability of the stellar position is folded in as
the same tail factor used elsewhere, and the result is reported with and
without it.
"""
import csv, json, os
import collections
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
TRIG = 5.0
NBOOT = 20000
RNG = np.random.default_rng(20260921)
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

CAT = {}
for r in csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.96.csv'))):
    CAT[(r['eb'], round(min(float(r['flo_GHz']), float(r['fhi_GHz'])), 4))] = r
EXP = json.load(open(os.path.join(HERE,
                                  'frozen_export_v3.81_survey.json')))['rows']

# per-window probability that a no-signal position reproduces a stage-1 event
byblock, byblockA = collections.defaultdict(list), collections.defaultdict(list)
seen = set()
nwin = nwinA = 0
for r in EXP:
    c = np.asarray(r.get('ctrl_all') or [], float)
    key = (r['eb'], round(min(r['flo'], r['fhi']), 4))
    if c.size == 0 or key in seen or key not in CAT:
        continue
    seen.add(key)
    # exactly one probe is the maximum; it reproduces a stage-1 event only
    # if it also reaches the trigger
    p = (1.0 / (c.size + 1.0)) if c.max() >= TRIG else 0.0
    byblock[r['eb']].append(p)
    nwin += 1
    if CAT[key]['search_class'] == 'A':
        byblockA[r['eb']].append(p)
        nwinA += 1

TAIL = 1.4          # measured non-exchangeability of the stellar position


def resample(bb, tail):
    blocks = list(bb)
    out = np.empty(NBOOT, dtype=int)
    for b in range(NBOOT):
        pick = RNG.integers(0, len(blocks), len(blocks))
        tot = 0
        for i in pick:
            ps = np.asarray(bb[blocks[i]]) * tail
            if ps.size:
                tot += int((RNG.random(ps.size) < ps).sum())
        out[b] = tot
    return out


OBS = sum(1 for r in CAT.values() if r['stage1_flag'] == 'True'
          and not (r['nearest_line'] and r['line_offset_kms']
                   and abs(float(r['line_offset_kms'])) <= 50))

res = {}
for lab, bb, n in (('All', byblock, nwin), ('A', byblockA, nwinA)):
    for tlab, t in (('Exch', 1.0), ('', TAIL)):
        d = resample(bb, t)
        res[lab + tlab] = d
        M('StageNull%s%sMean' % (lab, tlab), '%.2f' % d.mean())
        M('StageNull%s%sLo' % (lab, tlab), '%.0f' % np.percentile(d, 2.5))
        M('StageNull%s%sHi' % (lab, tlab), '%.0f' % np.percentile(d, 97.5))
        p = float((d >= OBS).mean())
        M('StageNull%s%sP' % (lab, tlab),
          ('<10^{-4}' if p < 1e-4 else '%.4f' % p))
    M('StageNull%sWin' % lab, '%d' % n)
M('StageNullObs', '%d' % OBS)
M('StageNullTrig', '%.0f' % TRIG)
M('StageNullTail', '%.1f' % TAIL)
# fraction of windows in which noise can reach the trigger at all
_nz = sum(1 for v in byblock.values() for p in v if p > 0)
M('StageNullEligible', '%d' % _nz)
M('StageNullEligiblePct', '%.0f' % (100.0 * _nz / max(nwin, 1)))
_nzA = sum(1 for v in byblockA.values() for p in v if p > 0)
M('StageNullEligibleA', '%d' % _nzA)

open(os.path.join(HERE, 'survey_numbers_round47.tex'), 'w').write(
    '%% GENERATED by stageonenull_v396.py -- do not hand-edit.\n'
    + '\n'.join(OUT) + '\n')

print('stage-1 null over %d windows (%d Class A), trigger %.0f' % (nwin, nwinA, TRIG))
print('  windows where a no-signal position can reach the trigger: %d (%.0f per cent),'
      ' %d of them Class A' % (_nz, 100.0 * _nz / nwin, _nzA))
print('  observed unattributed stage-1 events: %d' % OBS)
for lab, name in (('AllExch', 'all windows, exchangeable'),
                  ('All', 'all windows, x%.1f tail' % TAIL),
                  ('AExch', 'Class A, exchangeable'),
                  ('A', 'Class A, x%.1f tail' % TAIL)):
    d = res[lab]
    print('  %-28s mean %5.2f  95%% %d-%d  P(>=%d) = %.4f'
          % (name, d.mean(), np.percentile(d, 2.5), np.percentile(d, 97.5),
             OBS, (d >= OBS).mean()))
print('macros -> survey_numbers_round47.tex (%d)' % len(OUT))
