#!/usr/bin/env python3
"""Emit survey_numbers_localnull.tex from the second-stage local-null results.

Single source: v342_local_null.json, the machine-readable output of the
local-null computation (code in localnull_code/).  Nothing here is hand-typed
into the manuscript; every quantity the text quotes is a macro emitted below.

The three parametric tail extrapolations of the beta Pic B3 scramble null are
reported in the prose of the accompanying report rather than in the JSON's
numeric fields, so they are carried here explicitly with their provenance.
They are used only to state that the extrapolations disagree, never as a
quoted probability.
"""
import json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
J = json.load(open(os.path.join(HERE, 'v342_local_null.json')))
W = {w['target']: w for w in J['windows']}

CP = W['CP-72_2713_B7']
HD = W['HD_48370_B6']
B3 = W['bet_Pic_B3']
B6 = W['bet_Pic_B6']

BONF = J['survey_wide_bonferroni_scale']

# Parametric tails of the beta Pic B3 scramble null (report section 5, item 2).
BPIC_TAILS = {'gev': 0.0, 'gumbel': 1.9e-18, 'gaussian_trials': 4.4e-44}


def sci(x, sig=2):
    """1.58e-3 -> '1.6\\times10^{-3}' with sig significant figures."""
    if x == 0:
        return '0'
    e = int(math.floor(math.log10(abs(x))))
    m = x / 10.0 ** e
    m = round(m, sig - 1)
    if abs(m - 10.0) < 1e-9:
        m, e = 1.0, e + 1
    ms = ('%.*f' % (sig - 1, m)).rstrip('0').rstrip('.')
    if e == 0:
        return ms
    return r'%s\times10^{%d}' % (ms, e)


def pow10(n):
    return r'10^{%d}' % n


def draws(n):
    """100000 -> '10^{5}', 20000 -> '2\\times10^{4}'."""
    s = sci(float(n), 1)
    return s[len(r'1\times'):] if s.startswith(r'1\times') else s


out = []
add = out.append
add('%% Generated by localnull_calc.py from v342_local_null.json.')
add('%% Second-stage local null for the four stage-1 flagged windows')
add('%% (referee A item 5).  DO NOT EDIT BY HAND.')

# --- method ---
add(r'\newcommand{\LNDrawsMax}{%s}' % draws(CP['null_A']['draws']))
add(r'\newcommand{\LNDrawsMin}{%s}' % draws(B6['null_A']['draws']))
add(r'\newcommand{\LNLagOne}{%.2f}' % CP['null_A']['z_lag1_autocorr'])
add(r'\newcommand{\LNNRetained}{%d}'
    % CP['geometry']['n_control_positions_retained_full_spectra'])
add(r'\newcommand{\LNNFirstStage}{%d}'
    % CP['geometry']['n_control_positions_first_stage'])
add(r'\newcommand{\LNNBootGEV}{%d}' % CP['null_B_real_controls_gev']['n_bootstrap'])
add(r'\newcommand{\LNValidLo}{0.2}')
add(r'\newcommand{\LNValidHi}{5}')

# --- CP-72 2713: the headline ---
cpA, cpB = CP['null_A'], CP['null_B_real_controls_gev']
add(r'\newcommand{\LNpCP}{%s}' % sci(cpA['p_local']))
add(r'\newcommand{\LNnExceedCP}{%d}' % cpA['n_draws_ge_T_star'])
add(r'\newcommand{\LNpCPgev}{%s}' % sci(cpB['p']))
add(r'\newcommand{\LNpCPgevLo}{%s}' % sci(cpB['p_95CI'][0]))
add(r'\newcommand{\LNpCPgevHi}{%s}' % sci(cpB['p_95CI'][1]))
add(r'\newcommand{\LNCPBootPct}{%.1f}' % (100 * cpB['bootstrap_prob_p_below_bonferroni']))
add(r'\newcommand{\LNCPRatio}{%d}' % int(round(cpA['p_local'] / BONF)))
add(r'\newcommand{\LNCPAgreeFac}{%.1f}' % (cpA['p_local'] / cpB['p']))
add(r'\newcommand{\LNCPNullMed}{%.2f}' % cpA['median'])
add(r'\newcommand{\LNCPNullMax}{%.2f}' % cpA['max'])
add(r'\newcommand{\LNCPRealMed}{%.2f}' % cpA['self_validation']['real512_median'])
add(r'\newcommand{\LNCPKS}{%.2f}' % cpA['self_validation']['ks_2samp']['p'])
add(r'\newcommand{\LNCPRecal}{%s}'
    % sci(cpA['recalibration_sensitivity_p_vs_added_offset']['0.04']))
add(r'\newcommand{\LNCPSubMax}{%.2f}' % CP['subband_cross_check']['max'])
add(r'\newcommand{\LNCPSubN}{%d}' % CP['subband_cross_check']['n_draws'])

# --- HD 48370: the invalid one ---
hdA = HD['null_A']
sv = hdA['self_validation']
add(r'\newcommand{\LNHDnAbove}{%d}'
    % int(round(sv['frac_real512_above_null_max'] * HD['geometry']['n_control_positions_first_stage'])))
add(r'\newcommand{\LNHDPctAbove}{%d}' % int(round(100 * sv['frac_real512_above_null_max'])))
add(r'\newcommand{\LNHDNullMax}{%.2f}' % hdA['max'])
add(r'\newcommand{\LNHDNullMed}{%.2f}' % hdA['median'])
add(r'\newcommand{\LNHDRealMed}{%.2f}' % sv['real512_median'])
add(r'\newcommand{\LNHDKSstat}{%.2f}' % sv['ks_2samp']['stat'])
add(r'\newcommand{\LNpHDgev}{%s}' % sci(HD['null_B_real_controls_gev']['p']))
add(r'\newcommand{\LNpHDgevLo}{%s}' % sci(HD['null_B_real_controls_gev']['p_95CI'][0]))
add(r'\newcommand{\LNpHDgevHi}{%s}' % sci(HD['null_B_real_controls_gev']['p_95CI'][1]))

# --- beta Pic: positive controls ---
add(r'\newcommand{\LNpBpicThree}{%s}' % sci(B3['null_A']['p_local'], 1))
add(r'\newcommand{\LNpBpicSix}{%s}' % sci(B6['null_A']['p_local'], 1))
add(r'\newcommand{\LNpBpicThreeGEV}{%s}' % sci(B3['null_B_real_controls_gev']['p']))
add(r'\newcommand{\LNpBpicSixGEV}{%s}' % sci(B6['null_B_real_controls_gev']['p']))

# --- the local null is not a spatial discriminator ---
nclear = sum(1 for w in J['windows']
             if w['control_discrimination']['ring_max_p_against_local_null'] < 1e-4)
add(r'\newcommand{\LNNCtrlClear}{%d}' % nclear)
add(r'\newcommand{\LNNWindows}{%d}' % len(J['windows']))

# --- tail-extrapolation disagreement ---
finite = [v for v in BPIC_TAILS.values() if v > 0]
dex = int(round(abs(math.log10(max(finite)) - math.log10(min(finite)))))
add(r'\newcommand{\LNTailDex}{%d}' % dex)

# --- validation of the reimplementation ---
add(r'\newcommand{\LNTstarMaxDiff}{%g}'
    % max(abs(w['reproduction']['abs_difference']) for w in J['windows']))

open(os.path.join(HERE, 'survey_numbers_localnull.tex'), 'w').write('\n'.join(out) + '\n')
print('wrote survey_numbers_localnull.tex (%d macros)'
      % sum(1 for l in out if l.startswith(r'\newcommand')))
