#!/usr/bin/env python3
"""R2-M2 / R1-4: the selection function P90^sel, measured END TO END.

The campaign this reads injects Hanning-convolved carriers at random
sub-channel phase and random drift into CALIBRATED VISIBILITIES, then runs
the unmodified extraction, baseline removal, de-drift stack, trigger and
512-control rank, and scores each tone on one criterion: peak de-drifted
SNR at the injected cell >= 5 AND greater than every one of the 512
controls. Amplitudes are in units of each window's own trigger flux
S_trig = 5 sigma_comb, so windows of very different depth contribute to
one curve.

This replaces a campaign that injected into retained per-integration
spectra AFTER the baseline step and never passed through the control
ranking at all. The two disagree by a factor of about four, and the reason
is visible in the numbers below: the rank gate, not the trigger, is what
limits recovery.

Two results here are not just a number.

  * The recovery curve SATURATES BELOW UNITY. At the top measured rung the
    trigger fires for every tone and a few per cent still fail, because a
    bright source at the stellar position leaks into the control ring
    through the dirty beam and lifts the control maximum with it (the
    median control maximum rises from the clean value to nearly twice it
    at the top rung). There is a ceiling on recovery that no amount of
    transmitter power removes.

  * For the fine (Class A) stratum the 90 per cent point sits close to the
    end of the ladder, and in a quarter of the unit-level bootstrap
    resamples the curve does not reach 0.9 at all within 8 x S_trig. That
    is reported, not smoothed over.

Reads m3a_result_v400.json (copied from the campaign host).
Writes survey_numbers_round68.tex and tab_m3a_v400.tex.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, 'm3a_result_v400.json')
OUT = os.path.join(HERE, 'survey_numbers_round68.tex')
TAB = os.path.join(HERE, 'tab_m3a_v400.tex')

D = json.load(open(RES))
S = {s['stratum']: s for s in D['strata']}
ALL, FINE, COARSE = S['all'], S['fine (<1 MHz)'], S['coarse (>5 MHz)']

# The campaign must not be quoted at all if its own positive control failed:
# a unit that cannot recover a 20x carrier at its own star position is not
# evidence about fainter ones.
for k, s in S.items():
    assert s['positive_control_frac'] >= 0.95, (
        'stratum %s failed its positive control at %.3f' % (k, s['positive_control_frac']))
# and the uninjected passes must not manufacture recoveries
assert ALL['null_recovered'] == 0, (
    'null arm recovered %d of %d cells with no signal injected'
    % (ALL['null_recovered'], ALL['null_n']))

L = ['%% GENERATED by m3a_v400.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('SelNUnit', '%d' % ALL['n_units'])
m('SelNUnitTotal', '%d' % D['n_units_total'])
m('SelNTone', '{:,}'.format(ALL['n_tones']).replace(',', '\\,'))
m('SelNTonePlain', '%d' % ALL['n_tones'])
m('SelNullN', '{:,}'.format(ALL['null_n']).replace(',', '\\,'))
m('SelPCFrac', '%.3f' % ALL['positive_control_frac'])
m('SelNPCFail', '%d' % len(D['positive_control_failures']))

m('SelPNinety', '%.1f' % ALL['P90_over_trigger'])
m('SelPNinetyLo', '%.1f' % ALL['P90_ci68'][0])
m('SelPNinetyHi', '%.1f' % ALL['P90_ci68'][1])
m('SelPNinetyFine', '%.1f' % FINE['P90_over_trigger'])
m('SelPNinetyFineLo', '%.1f' % FINE['P90_ci68'][0])
m('SelPNinetyFineHi', '%.1f' % FINE['P90_ci68'][1])
m('SelPNinetyCoarse', '%.1f' % COARSE['P90_over_trigger'])
m('SelFineUndefPct', '%.0f' % (100 * FINE['P90_bootstrap_undefined_frac']))

# The same curve scored on the TRIGGER ALONE, which is the quantity the
# paper's P_90 has always meant. Reporting both is what makes the size of
# the rank gate visible: the two are measured on the same tones.
def p90_of(ladder, key):
    xs = [r['amp_over_trig'] for r in ladder]
    ys = [r[key] for r in ladder]
    for j in range(1, len(xs)):
        if ys[j - 1] < 0.9 <= ys[j]:
            w = (0.9 - ys[j - 1]) / (ys[j] - ys[j - 1])
            return xs[j - 1] + w * (xs[j] - xs[j - 1])
    return None


for _tag, _s in (('', ALL), ('Fine', FINE), ('Coarse', COARSE)):
    _t = p90_of(_s['ladder'], 'frac_trig_only')
    if _t is not None:
        m('SelPNinetyTrig%s' % _tag, '%.1f' % _t)
        _r = p90_of(_s['ladder'], 'frac')
        if _r:
            m('SelGateCost%s' % _tag, '%.1f' % (_r / _t))

# The calibration uncertainty, as multipliers on the quoted value. This
# replaces the old window-to-window transfer bracket, which was the spread
# of a campaign that measured a different quantity; the interval here is a
# bootstrap over CONFIGURATIONS, which is the level at which the trials are
# independent.
for _tag, _s in (('', ALL), ('Fine', FINE), ('Coarse', COARSE)):
    _p = _s['P90_over_trigger']
    m('SelTrans%sLo' % _tag, '%.2f' % (_s['P90_ci68'][0] / _p))
    m('SelTrans%sHi' % _tag, '%.2f' % (_s['P90_ci68'][1] / _p))

# the ceiling, and the reason for it
top = max(ALL['ladder'], key=lambda r: r['amp_over_trig'])
ftop = max(FINE['ladder'], key=lambda r: r['amp_over_trig'])
m('SelTopRung', '%.0f' % top['amp_over_trig'])
m('SelTopFrac', '%.3f' % top['frac'])
m('SelTopTrigFrac', '%.3f' % top['frac_trig_only'])
m('SelFineTopFrac', '%.3f' % ftop['frac'])
m('SelFineTopTrigFrac', '%.3f' % ftop['frac_trig_only'])
m('SelCtrlClean', '%.1f' % ALL['ctrl_top_clean'])
m('SelCtrlTopRung', '%.1f' % ALL['ctrl_top_at_top_rung'])

# the rung at which the trigger and the rank part company most sharply
gap = max(FINE['ladder'], key=lambda r: r['frac_trig_only'] - r['frac'])
m('SelGapAmp', '%.1f' % gap['amp_over_trig'])
m('SelGapTrig', '%.2f' % gap['frac_trig_only'])
m('SelGapRec', '%.2f' % gap['frac'])

open(OUT, 'w').writelines(L)

with open(TAB, 'w') as fh:
    fh.write('%% GENERATED by m3a_v400.py -- do not hand-edit.\n')
    fh.write('\\begin{tabular}{@{}r rr rr@{}}\n\\toprule\n')
    fh.write('$S/S_{\\rm trig}$ & \\multicolumn{2}{c}{Class A (fine)} & '
             '\\multicolumn{2}{c}{Class B (coarse)} \\\\\n')
    fh.write('\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n')
    fh.write(' & trigger & recovered & trigger & recovered \\\\\n\\midrule\n')
    fb = {r['amp_over_trig']: r for r in FINE['ladder']}
    cb = {r['amp_over_trig']: r for r in COARSE['ladder']}
    for a in sorted(fb):
        fh.write('%.2f & %.3f & %.3f & %.3f & %.3f \\\\\n'
                 % (a, fb[a]['frac_trig_only'], fb[a]['frac'],
                    cb[a]['frac_trig_only'], cb[a]['frac']))
    fh.write('\\bottomrule\n\\end{tabular}\n')

print('m3a_v400: P90^sel/P_trig = %.2f (all), %.2f (Class A), %.2f (Class B); '
      '%d tones over %d units; null %d of %d; positive control %.3f'
      % (ALL['P90_over_trigger'], FINE['P90_over_trigger'],
         COARSE['P90_over_trigger'], ALL['n_tones'], ALL['n_units'],
         ALL['null_recovered'], ALL['null_n'], ALL['positive_control_frac']))
print('  ceiling: at %.0f x S_trig the trigger fires for %.3f of tones and '
      '%.3f are recovered; control max %.1f -> %.1f'
      % (top['amp_over_trig'], top['frac_trig_only'], top['frac'],
         ALL['ctrl_top_clean'], ALL['ctrl_top_at_top_rung']))
