#!/usr/bin/env python3
"""R2-M5: does the visibility-domain test have the power to see a source?

A null result from a test of unknown power says nothing, and the referee is
right to ask for the power to be demonstrated rather than asserted. The
demonstration has three parts, and all three come from quantities the fit
already stores.

  1. What the estimator returns at each flagged window's own recorded cell,
     tabulated against the image-plane statistic the pipeline reported
     there. If the two disagree for a source that really is at the star,
     the test is not measuring what it claims.

  2. What a real point source at the stellar position WOULD return. The
     image-plane statistic is a signal-to-noise ratio at the star, so a
     compact source producing T_star in the image produces Re/sigma of the
     same order in the visibilities; the positive controls fix the
     constant of proportionality empirically, because they ARE compact
     emission at the stellar position.

  3. The probability of the observed Re/sigma under that expectation. The
     fit's own sigma_re is the scale, so this is a normal-deviate
     statement and needs no simulation.

The language the paper may then use is bounded by this: not "decisive",
not "no point source", but emission at the stellar position excluded at
the stated number of sigma.

Writes survey_numbers_round74.tex and tab_vispower_v400.tex.
"""
import json
import math
import os
import statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
V = json.load(open(os.path.join(HERE, 'vistest_v385.json')))
OUT = os.path.join(HERE, 'survey_numbers_round74.tex')
TAB = os.path.join(HERE, 'tab_vispower_v400.tex')


def norm_sf(z):
    """P(X > z) for a standard normal, via erfc."""
    return 0.5 * math.erfc(z / math.sqrt(2.0))


ev = []
for k, d in V.items():
    if d.get('status') != 'ok':
        continue
    e, s = d['event'], d['star']
    ev.append(dict(
        tag=e['tag'], band=e['band'], eb=e['eb'],
        tstar=float(e['star_snr']), ctrl=float(e['ctrl']),
        dispo=(e.get('disposition') or 'unattributed'),
        re=float(s['re']), sig=float(s['sig_re']),
        snr_re=float(s['snr_re']), snr_im=float(s['snr_im']),
        freq=float(e['freq_GHz']),
        ctrl_re_max=float(d['ctrl_snr_re_max'])))

# the window's own trigger flux, from the released catalogue
import csv as _csv
_CAT = list(_csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.99.csv'))))
for x in ev:
    for r in _CAT:
        if r['eb'] != x['eb'] or r['band'] != str(x['band']):
            continue
        lo, hi = sorted((float(r['flo_GHz']), float(r['fhi_GHz'])))
        if lo - 1e-6 <= x['freq'] <= hi + 1e-6 and r['smin_mJy']:
            x['smin_Jy'] = float(r['smin_mJy']) / 1e3
            break

assert ev, 'no usable visibility fits'
att = [x for x in ev if x['dispo'] != 'unattributed']
un = [x for x in ev if x['dispo'] == 'unattributed']
assert att and un, 'need both attributed and unattributed events'

# (2) What a compact source at the stellar position WOULD return, computed
# from first principles rather than calibrated on the attributed events.
# Those are resolved or extended emission --- one of them is a CO ring that
# fills the control annulus --- so the ratio Re/sigma to T_star scatters
# over two orders of magnitude across them and is not a constant to fit.
#
# The image-plane statistic is a signal-to-noise ratio, so an event with
# statistic T_star at a window whose trigger flux is S_min = 5 sigma
# corresponds to a flux S = T_star x S_min / 5. The visibility fit reports
# its own flux uncertainty sigma_re in the same units, so a compact source
# of that flux would return Re/sigma = S / sigma_re. No free parameter
# enters.
for x in ev:
    if x.get('smin_Jy'):
        x['flux'] = x['tstar'] * x['smin_Jy'] / 5.0
        x['expect'] = x['flux'] / x['sig']
    else:
        x['flux'] = x['expect'] = float('nan')
    x['z'] = x['expect'] - x['snr_re']            # in units of sigma_re
    x['p'] = norm_sf(x['z']) if x['z'] == x['z'] and x['z'] > 0 else 1.0
ev = [x for x in ev if x['expect'] == x['expect']]
att = [x for x in ev if x['dispo'] != 'unattributed']
un = [x for x in ev if x['dispo'] == 'unattributed']
ratios = [x['snr_re'] / x['tstar'] for x in att]
K = st.median(ratios)

worst = max(un, key=lambda x: x['snr_re'])        # least constraining
best = min(un, key=lambda x: x['z'])

L = ['%% GENERATED by vispower_v400.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('VpNEvent', '%d' % len(ev))
m('VpNAtt', '%d' % len(att))
m('VpNUnatt', '%d' % len(un))
m('VpK', '%.2f' % K)
m('VpKLo', '%.2f' % min(ratios))
m('VpKHi', '%.2f' % max(ratios))
m('VpAttSnrLo', '%.1f' % min(x['snr_re'] for x in att))
m('VpAttSnrHi', '%.1f' % max(x['snr_re'] for x in att))
m('VpUnattSnrMax', '%.2f' % max(x['snr_re'] for x in un))
m('VpUnattExpectLo', '%.1f' % min(x['expect'] for x in un))
m('VpUnattExpectHi', '%.1f' % max(x['expect'] for x in un))
m('VpZMin', '%.1f' % min(x['z'] for x in un))
m('VpZMax', '%.1f' % max(x['z'] for x in un))
m('VpPWorst', ('<10^{-3}' if best['p'] < 1e-3 else '=%.3f' % best['p']))
m('VpWorstTag', worst['tag'].replace('_', ' '))

with open(TAB, 'w') as fh:
    fh.write('%% GENERATED by vispower_v400.py -- do not hand-edit.\n')
    fh.write('\\begin{tabular}{@{}llrrrrl@{}}\n\\toprule\n')
    fh.write('Star & B & $T_\\star$ & Re$/\\sigma$ & Im$/\\sigma$ & '
             'expected & disposition \\\\\n\\midrule\n')
    for x in sorted(ev, key=lambda y: -y['tstar']):
        fh.write('%s & %s & %.2f & $%+.2f$ & $%+.2f$ & %.1f & %s \\\\\n'
                 % (x['tag'].replace('_', ' '), x['band'], x['tstar'],
                    x['snr_re'], x['snr_im'], x['expect'], x['dispo']))
    fh.write('\\bottomrule\n\\end{tabular}\n')

open(OUT, 'w').writelines(L)
print('vispower_v400: %d events (%d attributed, %d unattributed)'
      % (len(ev), len(att), len(un)))
print('  attributed events return Re/sigma = %.1f-%.1f, giving '
      'Re/sigma = %.2f x T_star (range %.2f-%.2f)'
      % (min(x['snr_re'] for x in att), max(x['snr_re'] for x in att),
         K, min(ratios), max(ratios)))
print('  unattributed: max Re/sigma %.2f against an expectation of %.1f-%.1f '
      'for a real source; excluded at %.1f-%.1f sigma'
      % (max(x['snr_re'] for x in un),
         min(x['expect'] for x in un), max(x['expect'] for x in un),
         min(x['z'] for x in un), max(x['z'] for x in un)))
