#!/usr/bin/env python3
"""G-1: place the MeerKAT detection of auroral radio emission from the
exoplanet beta Pictoris b (Ortiz Ceballos et al. 2026, arXiv:2609.16720)
against this survey's frequency coverage.

The point is not a comparison of sensitivities.  Electron-cyclotron maser
emission has a hard upper frequency: the electron cyclotron frequency at
the source,

    f_ce = e B / (2 pi m_e)  =  2.8 MHz/G  x  B[G],

so a magnetic field sets a ceiling on where auroral emission can appear
at all.  Their implied field, >= 1.25 kG, reproduces their own quoted
upper edge of 3.5 GHz, which is the check that this calculation is the
same one they made.  Running it forwards to OUR band edges answers a
question a reader of both papers will ask: could this survey have seen
that signal?  It could not, and the reason is physics rather than
depth --- the required field is tens of kilogauss.

Writes survey_numbers_round57.tex.  No input from the search products,
so it has no ordering constraint in make_all.sh beyond needing the
catalogue for the band edges.
"""
import csv, json, os

# --- physical constants (CODATA 2018), so the 2.8 MHz/G is derived, not typed
E_CHARGE = 1.602176634e-19        # C
M_E      = 9.1093837015e-31       # kg
PI       = 3.141592653589793

# --- the preprint's reported quantities, and ONLY these are external inputs
BPICB_FIELD_KG   = 1.25           # kG, lower bound on the field at the planet
BPICB_FLO_GHZ    = 0.85           # GHz, low edge of the detected emission
BPICB_FHI_GHZ    = 3.5            # GHz, high edge = their cyclotron ceiling
BPICB_ARXIV      = '2609.16720'


def f_ce_GHz(B_gauss):
    """Electron cyclotron frequency for a field in gauss."""
    return E_CHARGE * (B_gauss * 1e-4) / (2 * PI * M_E) / 1e9


def B_gauss_for(f_GHz):
    """Field required to put the cyclotron frequency at f_GHz."""
    return 2 * PI * M_E * (f_GHz * 1e9) / E_CHARGE * 1e4


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    rows = list(csv.DictReader(open(os.path.join(
        here, 'per_target_results_v3.97.csv'))))
    flo = min(float(r['flo_GHz']) for r in rows)
    fhi = max(float(r['fhi_GHz']) for r in rows)

    # the consistency check: their field must give their own upper edge
    ceil_bpicb = f_ce_GHz(BPICB_FIELD_KG * 1000.0)
    assert abs(ceil_bpicb - BPICB_FHI_GHZ) < 0.05 * BPICB_FHI_GHZ, (
        'the cyclotron ceiling for %.2f kG is %.2f GHz, which does not '
        'reproduce the reported upper edge %.2f GHz -- either the reported '
        'field or this calculation is wrong, and the text must not be '
        'built on it' % (BPICB_FIELD_KG, ceil_bpicb, BPICB_FHI_GHZ))

    B_lo_kG = B_gauss_for(flo) / 1000.0      # field needed at our low edge
    B_hi_kG = B_gauss_for(fhi) / 1000.0      # ... and at our high edge
    B_b7_kG = B_gauss_for(345.0) / 1000.0    # ... and in Band 7
    ratio_lo = B_lo_kG / BPICB_FIELD_KG
    ratio_b7 = B_b7_kG / BPICB_FIELD_KG

    # our bands must lie ABOVE their ceiling, or the whole argument inverts
    assert flo > BPICB_FHI_GHZ, (
        'this survey reaches down to %.1f GHz, at or below the quoted '
        'auroral ceiling %.1f GHz; the "outside our bands by physics" '
        'statement would then be false' % (flo, BPICB_FHI_GHZ))

    # how far below our coverage their detection sits
    decades = None
    import math
    decades = math.log10(flo / BPICB_FHI_GHZ)

    out = []
    A = out.append
    A('%% generated by ecmi_v397.py -- do not edit')
    A('%% Ortiz Ceballos et al. (2026), arXiv:%s' % BPICB_ARXIV)
    A('\\newcommand{\\BpicbArxiv}{%s}' % BPICB_ARXIV)
    A('\\newcommand{\\BpicbFieldkG}{%.2f}' % BPICB_FIELD_KG)
    A('\\newcommand{\\BpicbFlo}{%.2f}' % BPICB_FLO_GHZ)
    A('\\newcommand{\\BpicbFhi}{%.1f}' % BPICB_FHI_GHZ)
    A('\\newcommand{\\BpicbCeiling}{%.1f}' % ceil_bpicb)
    A('\\newcommand{\\EcmiFieldLo}{%.0f}' % B_lo_kG)
    A('\\newcommand{\\EcmiFieldHi}{%.0f}' % B_hi_kG)
    A('\\newcommand{\\EcmiFieldBSeven}{%.0f}' % B_b7_kG)
    A('\\newcommand{\\EcmiRatioLo}{%.0f}' % ratio_lo)
    A('\\newcommand{\\EcmiRatioBSeven}{%.0f}' % ratio_b7)
    A('\\newcommand{\\EcmiDecades}{%.1f}' % decades)
    A('\\newcommand{\\EcmiSurveyFlo}{%.1f}' % flo)
    A('\\newcommand{\\EcmiSurveyFhi}{%.1f}' % fhi)

    # named OUT so roundcollide.py can see who writes this round file
    OUT = os.path.join(here, 'survey_numbers_round57.tex')
    open(OUT, 'w').write('\n'.join(out) + '\n')

    json.dump(dict(arxiv=BPICB_ARXIV, field_kG=BPICB_FIELD_KG,
                   reported_fhi_GHz=BPICB_FHI_GHZ,
                   ceiling_from_field_GHz=ceil_bpicb,
                   survey_flo_GHz=flo, survey_fhi_GHz=fhi,
                   field_for_survey_flo_kG=B_lo_kG,
                   field_for_band7_kG=B_b7_kG,
                   ratio_at_survey_flo=ratio_lo,
                   ratio_at_band7=ratio_b7, decades_below=decades),
              open(os.path.join(here, 'ecmi_v397.json'), 'w'), indent=1)

    print('ecmi_v397: %.2f kG -> ceiling %.2f GHz (reported %.1f) OK ; '
          'our %.1f GHz needs %.0f kG = %.0fx ; %.1f decades above their edge'
          % (BPICB_FIELD_KG, ceil_bpicb, BPICB_FHI_GHZ, flo, B_lo_kG,
             ratio_lo, decades))


if __name__ == '__main__':
    main()
