#!/usr/bin/env python3
"""R1-4 (v3.97): the three frequency-union quantities, defined once and
generated, so the manuscript cannot quote them inconsistently again.

Referee 1 found Table 3 giving "Class B only" as 70.4 GHz while the scope
paragraph gave Class B as "90.5 GHz", and correctly diagnosed the cause:
those are different quantities. They are

  dnu_A      the Class A union
  dnu_B      the FULL Class B union, which overlaps Class A
  dnu_AuB    the union of the two
  dnu_Bonly  dnu_AuB - dnu_A, the coverage Class B adds

with dnu_A + dnu_B - dnu_AuB the overlap. All four are emitted here and
the identity is asserted.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.97.csv'))))
OUT = os.path.join(HERE, 'survey_numbers_round53.tex')


def union(iv):
    iv = sorted((min(a, b), max(a, b)) for a, b in iv)
    tot, clo, chi = 0.0, None, None
    for lo, hi in iv:
        if clo is None:
            clo, chi = lo, hi
        elif lo <= chi:
            chi = max(chi, hi)
        else:
            tot += chi - clo
            clo, chi = lo, hi
    if clo is not None:
        tot += chi - clo
    return tot


def iv(cls):
    return [(float(r['flo_GHz']), float(r['fhi_GHz'])) for r in CAT
            if r['search_class'] == cls]


uA, uB = union(iv('A')), union(iv('B'))
uAB = union(iv('A') + iv('B'))
bonly = uAB - uA
overlap = uA + uB - uAB
assert abs((uA + bonly) - uAB) < 1e-6, 'A + B-only must equal the union'
assert overlap > 0, 'the classes do overlap; that is the whole point'

L = ['%% GENERATED by freqdef_v397.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('DnuA', '%.1f' % uA)
m('DnuB', '%.1f' % uB)
m('DnuAB', '%.1f' % uAB)
m('DnuBonly', '%.1f' % bonly)
m('DnuOverlap', '%.1f' % overlap)
open(OUT, 'w').writelines(L)
print('%s: %d macros' % (os.path.basename(OUT), len(L) - 1))
print('  dnu_A     = %5.1f GHz' % uA)
print('  dnu_B     = %5.1f GHz  (full Class B union, overlaps A)' % uB)
print('  dnu_AuB   = %5.1f GHz' % uAB)
print('  dnu_Bonly = %5.1f GHz  = dnu_AuB - dnu_A' % bonly)
print('  overlap   = %5.1f GHz' % overlap)
