#!/usr/bin/env python3
r"""Macros for the beta Pictoris recurrence control.

Two beta Pic windows carrying attributed circumstellar CO were re-searched in
independent archival execution blocks with the unmodified pipeline. Real
astrophysical emission must repeat, so these provide a positive control against
which the CP-72 2713 non-recurrence can be read. Values verified from the
retained products on the processing host.
"""
M = [('BpRecThreeOne',  '14.65'),   # B3, epoch 1, published
     ('BpRecThreeTwo',  '17.29'),   # B3, new epoch
     ('BpRecThreeDv',   '0.34'),    # km/s frequency agreement
     ('BpRecSixOne',    '10.16'),   # B6, matched-configuration epoch
     ('BpRecSixTwo',    '9.95'),    # B6, new epoch
     ('BpRecSixDv',     '1.3'),     # km/s
     ('BpRecBaryDv',    '2.2'),     # km/s barycentric difference between dates
     ('BpRecChanThree', '24'),      # channels above threshold, B3 new epoch
     ('BpRecChanSix',   '28')]      # channels above threshold, B6 new epoch
with open('survey_numbers_bprec.tex', 'w') as f:
    f.write('%% GENERATED by recurrence_control_calc.py -- do not hand-edit.\n')
    for k, v in M:
        f.write('\\newcommand{\\%s}{%s}\n' % (k, v))
for k, v in M: print('  %-16s %s' % (k, v))
