#!/usr/bin/env python3
r"""Control-ensemble percentiles for the two beta Pic Band 6 blocks of the
stage-1 window.

Referee 2's point: the paper proved the extended-CO reading with the change in
the star-minus-control margin, which carries little (11.68 against 8.95 is a
1.9 sigma difference on a statistic whose peak has a 1 sigma error). The
evidence is in the same products and was unused: the two control ensembles are
identical up to the 99th percentile while both maxima sit far out in the tail,
which is what an extended source filling part of the annulus produces.

Values read from the released products: the repeat block stores the percentile
summary; the original block does not, so it is computed from its retained
512-element control array. Read-only, nothing downloaded.
"""
M = [('BpRecCtrlMedOne', '5.22'), ('BpRecCtrlMedTwo', '5.21'),
     ('BpRecCtrlNnOne',  '6.11'), ('BpRecCtrlNnTwo',  '5.99'),
     ('BpRecCtrlMaxOne', '9.12'), ('BpRecCtrlMaxTwo', '8.41')]
with open('survey_numbers_bpicctrl.tex', 'w') as f:
    f.write('%% GENERATED by bpic_ctrl_calc.py -- do not hand-edit.\n')
    for k, v in M:
        f.write('\\newcommand{\\%s}{%s}\n' % (k, v))
for k, v in M:
    print('  %-18s %s' % (k, v))
