#!/usr/bin/env python3
"""R2-4 (v3.99): activity and multiplicity status of the four unattributed
stage-1 hosts.

Referee 2 asked whether the hosts of the four unattributed events are
chromospherically active or in binaries, on the reasonable ground that an
active star is a plausible non-artificial source of a compact excess at the
stellar position and the paper should say so rather than leave it open.

The status is taken from SIMBAD (object-type lists and spectral types),
queried once on 2026-09-22 and FROZEN into hosts_v399.json so the build
does not depend on a live service.  Re-run with --requery to refresh, which
rewrites the frozen file; the frozen file is what make_all.sh reads.

The answer is not favourable to us and is reported as such: three of the
four hosts carry activity indicators.  That does not explain the events --
none of them is a point source at the stellar position in the visibilities,
which is the test that actually dispositions them -- but it does mean the
unattributed population cannot be described as quiet stars.

Writes survey_numbers_round58.tex and tab_hosts_v399.tex.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FROZEN = os.path.join(HERE, 'hosts_v399.json')
OUT = os.path.join(HERE, 'survey_numbers_round58.tex')
TAB = os.path.join(HERE, 'tab_hosts_v399.tex')

# The hosts of the unattributed stage-1 events. This list is READ from the
# catalogue-derived file v381_calc.py writes, not written here: it was a
# literal list of four, fixed before the ACA control geometry was repaired,
# and two of those four (HD 23484, HD 14055) were artefacts of the defect.
# The table went on naming them after the events themselves had gone. Only
# the display form and the SIMBAD identifier are local knowledge, and an
# unmapped name is a hard error rather than a silently dropped row.
DISPLAY = {'61 Vir': ('61 Vir', '61 Vir'),
           'HD 23484': ('HD 23484', 'HD 23484'),
           'HD 14055': ('HD 14055', 'HD 14055'),
           'CP-72 2713': ('CP$-$72 2713', 'CPD-72 2713'),
           'CP$-$72 2713': ('CP$-$72 2713', 'CPD-72 2713')}
_names = json.load(open(os.path.join(HERE, 'unattributed_hosts.json')))
_missing = [n for n in _names if n not in DISPLAY]
assert not _missing, ('unattributed host with no SIMBAD identifier mapped: '
                      '%s -- add it to DISPLAY rather than dropping the row'
                      % _missing)
HOSTS = [DISPLAY[n] for n in _names]

# SIMBAD object types that indicate magnetic activity, and multiplicity
ACTIVE = {'X': 'X-ray', 'Er*': 'em.-line', 'Fl*': 'flare',
          'Ro*': 'rot.\\ var.', 'BY*': 'BY Dra', 'RS*': 'RS CVn'}
# 'V*' (generic variable) is deliberately absent: it is implied by any of
# the specific classes above and printing both makes the cell redundant
MULT = {'**': 'multiple', 'SB*': 'spectroscopic binary', 'EB*': 'eclipsing'}


def requery():
    import urllib.parse
    import urllib.request
    tap = 'https://simbad.cds.unistra.fr/simbad/sim-tap/sync'

    def ask(q):
        u = tap + '?' + urllib.parse.urlencode(
            dict(request='doQuery', lang='adql', format='json', query=q))
        return json.load(urllib.request.urlopen(u, timeout=90)).get('data', [])

    rec = {}
    for disp, sid in HOSTS:
        b = ask("SELECT b.main_id, b.sp_type, b.plx_value FROM basic b "
                "JOIN ident i ON i.oidref=b.oid WHERE i.id='%s'" % sid)
        o = ask("SELECT o.otype FROM otypes o JOIN ident i "
                "ON i.oidref=o.oidref WHERE i.id='%s'" % sid)
        assert b, 'SIMBAD did not resolve %s' % sid
        rec[disp] = dict(main_id=b[0][0], sp_type=b[0][1], plx=b[0][2],
                         otypes=sorted(r[0] for r in o))
    json.dump(dict(queried='2026-09-22', hosts=rec),
              open(FROZEN, 'w'), indent=1)
    return rec


if '--requery' in sys.argv or not os.path.exists(FROZEN):
    HOST = requery()
else:
    HOST = json.load(open(FROZEN))['hosts']

assert all(disp in HOST for disp, sid in HOSTS), (
    'frozen host file does not cover every unattributed host')

rows, n_active, n_mult = [], 0, 0
for disp, sid in HOSTS:
    h = HOST[disp]
    act = [ACTIVE[t] for t in h['otypes'] if t in ACTIVE]
    mul = [MULT[t] for t in h['otypes'] if t in MULT]
    n_active += 1 if act else 0
    n_mult += 1 if mul else 0
    d = 1000.0 / h['plx'] if h['plx'] else float('nan')
    rows.append('%s & %s & %.1f & %s & %s \\\\' % (
        disp, (h['sp_type'] or '--').replace('-', '$-$'), d,
        ', '.join(act) if act else 'none',
        ', '.join(mul) if mul else 'none'))

with open(TAB, 'w') as f:
    f.write('%% GENERATED by hosts_v399.py -- do not hand-edit.\n')
    # the activity cell is the long one; give it a fixed measure so it
    # wraps instead of running the table off the column
    f.write('\\begin{tabular}{@{}llr p{1.75cm} l@{}}\n\\hline\n')
    f.write('Host & Sp.\\ type & $d$\\,(pc) & Activity indicators & '
            'Multiplicity \\\\\n\\hline\n')
    f.write('\n'.join(rows) + '\n\\hline\n\\end{tabular}\n')

with open(OUT, 'w') as f:
    f.write('%% GENERATED by hosts_v399.py -- do not hand-edit.\n')
    f.write('\\newcommand{\\HostNTot}{%d}\n' % len(HOSTS))
    f.write('\\newcommand{\\HostNActive}{%d}\n' % n_active)
    f.write('\\newcommand{\\HostNMult}{%d}\n' % n_mult)
    f.write('\\newcommand{\\HostQueried}{2026 September 22}\n')

print('hosts_v399: %d of %d hosts carry activity indicators, %d multiplicity'
      % (n_active, len(HOSTS), n_mult))
