#!/usr/bin/env python3
"""R2-M6 (v3.99): the searched range is NOT above every allocated service.

The manuscript said "the searched range, 90-873 GHz, lies above every
allocated terrestrial service". That is wrong. ITU Radio Regulations
Article 5 carries active allocations throughout 90-275 GHz, and WRC-19
identified parts of 275-450 GHz for land-mobile and fixed use. The
referee names the specific hazard: the 94.0-94.1 GHz Earth
exploration-satellite (active) allocation used by spaceborne cloud radar
(CloudSat, and EarthCARE since 2024), which is a documented problem in
ALMA Band 3.

This generator answers the referee's factual question -- does any window,
and in particular any threshold crossing, fall in that band? -- from the
released catalogue, so the answer cannot drift from the data.

Writes survey_numbers_round63.tex.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'survey_numbers_round63.tex')

# the 94 GHz spaceborne cloud-radar allocation, EESS (active)
RADAR_LO, RADAR_HI = 94.0, 94.1

CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.99.csv'))))


def overlaps(r, lo, hi):
    a, b = float(r['flo_GHz']), float(r['fhi_GHz'])
    if a > b:
        a, b = b, a
    return not (b < lo or hi < a)


win = [r for r in CAT if overlaps(r, RADAR_LO, RADAR_HI)]
cross = [r for r in win if r['crossing'] == 'True']
stage1 = [r for r in win if r['stage1_flag'] == 'True']

# the claim the text makes must follow from the data
assert not cross and not stage1, (
    'a crossing or stage-1 event falls in %.1f-%.1f GHz; the text must then '
    'report the execution-block times against CloudSat/EarthCARE overpasses '
    'rather than stating that none does' % (RADAR_LO, RADAR_HI))

lo = min(float(r['flo_GHz']) for r in CAT)
hi = max(float(r['fhi_GHz']) for r in CAT)

L = ['%% GENERATED by rfialloc_v399.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('RadarLo', '%.1f' % RADAR_LO)
m('RadarHi', '%.1f' % RADAR_HI)
m('RadarNWin', '%d' % len(win))
m('RadarNCross', '%d' % len(cross))
m('RadarNStage', '%d' % len(stage1))
m('RadarNTot', '%d' % len(CAT))
m('RfiSurveyLo', '%.1f' % lo)
m('RfiSurveyHi', '%.1f' % hi)
open(OUT, 'w').writelines(L)

print('rfialloc: %d of %d windows overlap %.1f-%.1f GHz; %d crossings, '
      '%d stage-1' % (len(win), len(CAT), RADAR_LO, RADAR_HI, len(cross),
                      len(stage1)))
