#!/usr/bin/env python3
"""R1-4 (v3.99): report the sensitivity as a DISTRIBUTION across systems,
not as a single median.

Referee 1: "I require the authors to make the sensitivity distribution,
rather than the median sensitivity, the primary quantitative result.
Specifically, in the Abstract and Conclusions, immediately following the
1.5e15 W median, state how many of the 60 Class-A systems have P90^sel
below physically useful benchmark powers -- for example 1e14, 1e15, 1e16
and 1e17 W."

P90^sel is built exactly as make_fig_classa_sens.py builds it, so the
numbers quoted in the text and the curve plotted in Fig. 7a cannot drift
apart: for each fine window, P_eff x P90FAC x (ring maximum / trigger),
minimised over each system's windows.  The two are cross-asserted below.

Writes survey_numbers_round62.tex.
"""
import csv
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'survey_numbers_round62.tex')

ROWS = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.99.csv'))))

# R2 minor 2: build P90^sel from the catalogue's OWN stored eirp_p90_W, the
# same construction v381_calc.py uses for the headline median. Reconstructing
# it as eirp_eff_total_W x PNinetyOverTrig is not equivalent -- the stored
# column is ~2.4 per cent higher -- and that is why the abstract read
# 1.4e15 W while Table 2, section 5.3, Fig. 7 and Conclusion 2 read 1.5e15.
# The two are cross-asserted at the end of this file.


def F(x):
    try:
        v = float(x)
        return v if v > 0 else None
    except (TypeError, ValueError):
        return None


bestsel = {}
for r in ROWS:
    if r['search_class'] != 'A':
        continue
    v, c = F(r['eirp_p90_W']), F(r['ctrl_max_snr'])
    if not v or not c:
        continue
    sel = v * c / 5.0
    k = r['system_id']
    if k not in bestsel or sel < bestsel[k]:
        bestsel[k] = sel

vals = sorted(bestsel.values())
n = len(vals)
assert n, 'no systems with a P90^sel'
# v381_calc.py quotes vals[n//2]; use the same element so the two agree
med = vals[n // 2]

BENCH = [1e14, 1e15, 1e16, 1e17]
cnt = {t: sum(1 for v in vals if v <= t) for t in BENCH}

# the distribution must be consistent with the median the paper quotes
assert cnt[1e15] <= n // 2 + 1 and cnt[1e16] >= n // 2, (
    'the benchmark counts (%s) are inconsistent with a median of %.2e'
    % (cnt, med))

L = ['%% GENERATED by sensdist_v399.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


def sci(x):
    e = int(math.floor(math.log10(x)))
    return '%.1f\\times10^{%d}' % (x / 10.0 ** e, e)


m('SdNSys', '%d' % n)
m('SdMed', sci(med))
# LaTeX macro names must be letters only -- \SdN14 parses as \SdN then a
# literal "14", which typesets in the preamble and breaks the build
WORD = {14: 'Fourteen', 15: 'Fifteen', 16: 'Sixteen', 17: 'Seventeen'}
for t in BENCH:
    k = WORD[int(round(math.log10(t)))]
    m('SdN%s' % k, '%d' % cnt[t])
    m('SdPct%s' % k, '%d' % round(100.0 * cnt[t] / n))
m('SdMin', sci(vals[0]))
m('SdMax', sci(vals[-1]))
open(OUT, 'w').writelines(L)

print('sensdist: %d systems, median %.2e' % (n, med))
for t in BENCH:
    print('   <= %.0e : %2d systems (%d%%)' % (t, cnt[t],
                                               round(100.0 * cnt[t] / n)))


# cross-assert against the headline median generated elsewhere, so the
# abstract and Table 2 can never again disagree
_head = None
for fn in sorted(os.listdir(HERE)):
    if fn.startswith('survey_numbers_round') and fn.endswith('.tex'):
        for line in open(os.path.join(HERE, fn)):
            if '\\newcommand{\\PromoteSysMedA}' in line:
                # the value contains braces (10^{15}), so take everything
                # between the first '}{' and the final '}'
                _head = line.strip().split('}{', 1)[1].rstrip()[:-1]
if _head:
    assert _head == sci(med), (
        'PromoteSysMedA is %s but this file computes %s; the headline median '
        'and the distribution must come from one construction'
        % (_head, sci(med)))
    print('  cross-check: PromoteSysMedA = %s  OK' % _head)
