#!/usr/bin/env python3
r"""Round 680: THE FIGURE OF MERIT ON ONE BASIS, AND THE DISTANCE RATIO OVER
ONE POPULATION.

Two defects in one paragraph, and both halves are real.

1.  TWO DIFFERENT VALUES OF THE SAME EXTERNAL CONSTANT.  Table 1 gives
    Margot et al. (2023) an EIRP_min of 1.35e13 W, read from their own
    sentence and generated by the same code that draws Figure 1; the
    Discussion evaluated their figure of merit on 1e13 W, typed into
    `occurrence_v399.py` beside the comment "a limit of EIRP > 1e13 W".
    1e13 W is NOT Margot et al.'s limit -- it is the Arecibo planetary radar
    normalisation of the CWTFM itself (`\FomAreciboEirp`), and the two were
    run together.  Margot et al. 2023, AJ 166, 206 state the limit twice,
    sec. 3.6 "transmitters located 326 ly (100 pc) away are detectable with
    0.62 Arecibos (EIRP=1.35 x 10^13 W)" and sec. 6 "fewer than 6.6% of the
    331,312 stars within 100 pc host a transmitter that is detectable in our
    survey (EIRP > 1.35 x 10^13 W)".  Their figure of merit as evaluated here
    is therefore 0.14, not 0.11, and 0.072 rather than 0.053 once their
    S/N = 10 threshold is put on the common basis of five.

    Nothing here is typed: the value is READ from the literature table in
    `make_fig_context_v410.py`, which is the table Figure 1 and Table 1 are
    both drawn from, and F1 requires it to equal the cell Table 1 actually
    prints.  The two can no longer disagree.

2.  A GAP QUOTED ON A BASIS THE SENTENCE DOES NOT USE.  The widening "from
    1.6e4 to 7.9e4" is the ratio of this survey's EIRP_90 figure of merit to
    Enriquez et al.'s, published and rescaled.  But the sentence that carries
    it has just put every programme on a common bare five-sigma threshold and
    calls that the only commensurable footing, and on that footing the survey
    figure is the bare-threshold one (4.4e3, round 270), not the EIRP_90 one
    (1.3e4).  The gap on the basis the paragraph declares is 5.2e3 widening
    to 2.6e4.  Both bases are legitimate and the paper quotes both, but each
    number must be computed on the basis beside it, so this round publishes
    the bare-threshold pair for the sentence that declares a bare threshold
    and leaves the EIRP_90 figures of merit where they already are.

    F4 is the check that keeps them apart: the gap pair must reproduce from
    the BARE branch of the same per-system calculation, must agree with the
    published `\SzCwtfmBareMed` inside its own rounding, and must come out
    SMALLER than the EIRP_90 pair quoted beside it.  Computing it from the
    EIRP_90 branch -- which is what the manuscript did -- makes that last
    clause false, and drive 4 does exactly that.

3.  MINOR 12: "between 25 and 277 times further away than the stars searched
    here" is measured over the CARRIER search and described as the survey.
    277x is tau Cet at 3.652 pc; the surveyed sample reaches Proxima Cen at
    1.302 pc, which is 776x.  The arithmetic is right and the label is wrong,
    which is the third place in this paper where a ratio has been computed
    over one population and described as another, so F5 ties the label to the
    measurement rather than fixing the number: the published ratio must
    reproduce from the nearest star OF THE CARRIER SEARCH, and the sample
    must contain a nearer star that is not in it, so that the population
    cannot be dropped from the sentence again.

Six assertions, six drives, each driven to fail on its own.
"""
import csv
import glob
import json
import math
import os
import re
import statistics as st
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROUND = 680

# D36: a test must never write to a path production reads.  The suffix
# follows the FLAG, not the perturbation.
DRIVE = int(sys.argv[sys.argv.index('--drive') + 1]) if '--drive' in sys.argv \
    else None
SUF = '' if DRIVE is None else '_drive%d' % DRIVE

# --------------------------------------------------------------- macro layer
_VALS = {}
for _f in sorted(glob.glob(os.path.join(HERE, 'survey_numbers*.tex'))):
    if '_drive' in os.path.basename(_f):
        continue
    for _n, _v in re.findall(
            r'\\(?:new|renew|provide)command\*?\{\\([A-Za-z]+)\}'
            r'\{((?:[^{}]|\{[^{}]*\})*)\}',
            open(_f, encoding='utf8', errors='ignore').read()):
        if _v.strip():
            _VALS[_n] = _v.strip()


def texval(name):
    if name not in _VALS:
        raise SystemExit('fig_r16: macro \\%s is not published' % name)
    return _VALS[name]


def texnum(name):
    return float(re.sub(r'[^0-9.eE+-]', '', texval(name)
                        .replace(r'\times10^{', 'e')
                        .replace(r'\times 10^{', 'e')))


def texround(name):
    """(value, half a unit in the macro's own last printed place).  A figure
    of merit published to two significant figures reproduces when the
    recomputation lands inside its own rounding, not inside a percentage of
    my choosing."""
    t = texval(name).replace(' ', '')
    mm = re.match(r'([-\d.]+)\\times10\^\{(-?\d+)\}$', t)
    if not mm:
        dp = len(t.split('.')[1]) if '.' in t else 0
        return float(t), 0.5 * 10.0 ** (-dp)
    mant, ex = mm.group(1), int(mm.group(2))
    dp = len(mant.split('.')[1]) if '.' in mant else 0
    return float(mant) * 10.0 ** ex, 0.5 * 10.0 ** (ex - dp)


def sci(x, nd=2):
    e = int(math.floor(math.log10(abs(x))))
    return r'%.*f\times10^{%d}' % (nd - 1, x / 10.0 ** e, e)


fail = []


def ck(name, ok, detail=''):
    print('  %-4s %s\n       %s' % ('PASS' if ok else 'FAIL', name, detail))
    if not ok:
        fail.append(name.split()[0])


# =====================================================================
# 1.  MARGOT et al.'s LIMIT, READ FROM THE TABLE THE PAPER PRINTS
# =====================================================================
# The module is imported, not run: it guards its own main().  This is the
# same import `occurrence_v399.py` already uses for the threshold factors,
# so the EIRP now comes from the same place the factor does.
import make_fig_context_v410 as _ctx          # noqa: E402

_MAR = _ctx.LIT['margot2023']
# the deepest published limit, which is the convention `thresholds_table`
# uses for the cell Table 1 prints
E_MAR = min(p[1] for p in _MAR['pts'])
SNR_MAR = _MAR['snr']
SCALE_MAR = _ctx.scale_to_common('margot2023')
NU_LO, NU_HI = _MAR['freq_GHz']

# --- F1: the value the Discussion uses is the cell Table 1 prints ---------
_tab = open(os.path.join(HERE, 'tab_litthresh_r15.tex'),
            encoding='utf8').read()
_row = [ln for ln in _tab.splitlines() if 'Margot' in ln]
assert len(_row) == 1, 'Table 1 has %d Margot rows' % len(_row)
_cells = [c.strip() for c in _row[0].split('&')]
TAB_EIRP = float(re.sub(r'[^0-9.eE+-]', '',
                        _cells[4].replace(r'\times10^{', 'e')))
TAB_EIRP_FIVE = float(re.sub(r'[^0-9.eE+-]', '',
                             _cells[5].replace(r'\times10^{', 'e')))
_v = E_MAR if DRIVE != 1 else 1.0e13
ck('F1 the EIRP the Discussion evaluates the figure of merit on is the cell '
   'Table 1 prints for the same programme, to the digit',
   abs(_v / TAB_EIRP - 1.0) < 1e-9
   and abs(TAB_EIRP_FIVE / (TAB_EIRP * SCALE_MAR) - 1.0) < 1e-9,
   'Discussion %.4g against Table 1 %.4g; Table 1 at five %.4g against '
   '%.4g x %.2f' % (_v, TAB_EIRP, TAB_EIRP_FIVE, TAB_EIRP, SCALE_MAR))

# --- F2: and it is the value in Margot et al.'s own sentence -------------
_e = E_MAR if DRIVE != 2 else 1.0e13
_ex = int(math.floor(math.log10(_e)))
_lit = ('%g x 10^%d' % (_e / 10.0 ** _ex, _ex))
_quotes = (_MAR['src'], _MAR['snr_src'])
ck('F2 that EIRP appears verbatim in the sentences of Margot et al. recorded '
   'beside it, so it is read from their paper and not from a summary of it',
   all(_lit in q for q in _quotes) and len(_quotes[0]) > 80,
   'looking for %r in both recorded quotations: %s'
   % (_lit, [(_lit in q) for q in _quotes]))

# --- their figure of merit, on the quantities they publish ---------------
ZETA_AO = (texnum('FomNormN') * texnum('FomNormNuRel')
           / texnum('FomAreciboEirp'))
N_MAR = texnum('FomMargotN')
NUREL_MAR = (NU_HI - NU_LO) / (0.5 * (NU_HI + NU_LO))
CW_MAR = ZETA_AO * E_MAR / (N_MAR * NUREL_MAR)
CW_MAR_FIVE = CW_MAR * SCALE_MAR

_v = SCALE_MAR if DRIVE != 3 else 1.0
ck('F3 their figure of merit is the published expression on the three '
   'quantities they publish, the common-basis one is that value times the '
   'ratio of thresholds and nothing else, and both lie below the Enriquez '
   'et al. value the sentence compares them with',
   abs(_v - 5.0 / SNR_MAR) < 1e-12
   and abs(CW_MAR * _v / (ZETA_AO * E_MAR * _v / (N_MAR * NUREL_MAR)) - 1.0)
   < 1e-12
   and CW_MAR * _v < texnum('FomLitEnriquezFive') < texnum('FomLitEnriquez')
   and abs(NUREL_MAR - (NU_HI - NU_LO) / (0.5 * (NU_HI + NU_LO))) < 1e-12,
   'zeta %.3g, N %.0f, nu_rel %.4f -> %.4f published, x%.2f -> %.4f at five; '
   'Enriquez %.3f -> %.3f'
   % (ZETA_AO, N_MAR, NUREL_MAR, CW_MAR, _v, CW_MAR * _v,
      texnum('FomLitEnriquez'), texnum('FomLitEnriquezFive')))

# =====================================================================
# 2.  THE GAP, ON THE BASIS THE PARAGRAPH DECLARES
# =====================================================================
import adopted_e90 as _ae                     # noqa: E402

CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.99.csv'))))
A = [r for r in CAT if r['search_class'] == 'A']
E90 = _ae.per_window(CAT, HERE)


def _union(iv):
    iv = sorted((min(a, b), max(a, b)) for a, b in iv)
    tot, (clo, chi) = 0.0, iv[0]
    for a, b in iv[1:]:
        if a > chi:
            tot += chi - clo
            clo, chi = a, b
        else:
            chi = max(chi, b)
    return tot + chi - clo


_iv = [(float(r['flo_GHz']), float(r['fhi_GHz'])) for r in A]
_lo = min(min(a, b) for a, b in _iv)
_hi = max(max(a, b) for a, b in _iv)
NUREL = _union(_iv) / (0.5 * (_lo + _hi))
NSYS = len({r['system_id'] for r in A})


def per_system(which):
    """The deepest window of each system, on one of the two conventions.
    Keyed on the system identifier and never on a name."""
    d = {}
    for r in A:
        v = E90[id(r)] if which == 'e90' else float(r['eirp_nominal_W'])
        if v and v < d.get(r['system_id'], float('inf')):
            d[r['system_id']] = v
    return sorted(d.values())


def cwtfm(e):
    return ZETA_AO * e / (NSYS * NUREL)


BARE = per_system('bare')
ADOPT = per_system('e90')
CW_BARE_MED, CW_BARE_HI = cwtfm(st.median(BARE)), cwtfm(BARE[-1])
CW_AD_MED, CW_AD_HI = cwtfm(st.median(ADOPT)), cwtfm(ADOPT[-1])

EN_PUB, EN_FIVE = texnum('FomLitEnriquez'), texnum('FomLitEnriquezFive')
# the gap the paragraph quotes, on the bare-threshold basis it declares
GAP_PUB, GAP_FIVE = CW_BARE_MED / EN_PUB, CW_BARE_MED / EN_FIVE
# and the same two on the EIRP_90 basis, which the paragraph names as such
GAP90_PUB, GAP90_FIVE = CW_AD_MED / EN_PUB, CW_AD_MED / EN_FIVE

_M = texround('SzCwtfmBareMed')
_W = texround('SzCwtfmBareWorst')
_v = CW_BARE_MED if DRIVE != 4 else CW_AD_MED
ck('F4 the gap is computed from the bare five-sigma branch, which is the '
   'basis the sentence declares: it reproduces the published bare figures of '
   'merit inside their own rounding, it widens when the comparison '
   'programme is rescaled, and it is SMALLER than the EIRP_90 gap quoted '
   'beside it',
   abs(CW_BARE_MED - _M[0]) <= _M[1] and abs(CW_BARE_HI - _W[0]) <= _W[1]
   and _v / EN_FIVE > _v / EN_PUB
   and _v / EN_PUB < GAP90_PUB and _v / EN_FIVE < GAP90_FIVE
   and abs(NUREL - texnum('FomNuRel')) < 5e-4 and NSYS == texnum('NSysClassA'),
   'bare %.4g / %.4g against published %s / %s; gap %.4g -> %.4g against the '
   'EIRP_90 gap %.4g -> %.4g; %d systems at nu_rel %.4f'
   % (CW_BARE_MED, CW_BARE_HI, texval('SzCwtfmBareMed'),
      texval('SzCwtfmBareWorst'), _v / EN_PUB, _v / EN_FIVE,
      GAP90_PUB, GAP90_FIVE, NSYS, NUREL))

# =====================================================================
# 3.  MINOR 12: WHICH POPULATION THE DISTANCE RATIO IS MEASURED OVER
# =====================================================================
D_A = sorted(float(r['dist_pc']) for r in A)
D_ALL = sorted(float(r['dist_pc']) for r in CAT)
MAS_PC = texnum('MasonNearKpc') * 1e3
NEAR_A = sorted({r['star_name'] for r in A
                 if abs(float(r['dist_pc']) - D_A[0]) < 1e-6})
NEAR_ALL = sorted({r['star_name'] for r in CAT
                   if abs(float(r['dist_pc']) - D_ALL[0]) < 1e-6})
R_NEAR_ALL = MAS_PC / D_ALL[0]

_v = D_A[0] if DRIVE != 5 else D_ALL[0]
ck('F5 the published distance ratio reproduces from the nearest star of the '
   'CARRIER search and from no other population, and the surveyed sample '
   'holds a nearer star that the carrier search does not contain, so the '
   'sentence cannot describe the ratio as the survey\'s',
   abs(MAS_PC / _v - texnum('MasonDistRatioNear')) < 1.0
   and D_ALL[0] < D_A[0] and NEAR_A != NEAR_ALL
   and abs(MAS_PC / D_A[-1] - texnum('MasonDistRatioFar')) < 1.0,
   'nearest carrier-search star %s %.3f pc -> x%.0f (published %s); nearest '
   'of the surveyed sample %s %.3f pc -> x%.0f; far edge %.3f pc -> x%s'
   % (', '.join(NEAR_A), D_A[0], MAS_PC / _v,
      texval('MasonDistRatioNear'), ', '.join(NEAR_ALL), D_ALL[0],
      R_NEAR_ALL, D_A[-1], texval('MasonDistRatioFar')))

# =====================================================================
# 4.  ONE BASIS IN THE MANUSCRIPT, NOT TWO
# =====================================================================
sys.path.insert(0, HERE)
import manuscript as _ms                      # noqa: E402

PROSE = _ms.flat()
NEW = ['FgMargotEirp', 'FgLitMargot', 'FgLitMargotFive',
       'FgGapBarePub', 'FgGapBareFive']
# the superseded names: the 1e13 Margot family and the EIRP_90 gap pair that
# was quoted as if it were the common-threshold one
OLD = ['FomMargotEirp', 'FomLitMargot', 'FomLitMargotFive',
       'FomRatioEnriquez', 'FomRatioEnriquezFive']


def cited(n):
    return re.search(r'\\%s(?![A-Za-z])' % n, PROSE) is not None


_old = list(OLD) if DRIVE != 6 else OLD + ['FomCwtfmMed']
ck('F6 every macro this round publishes is referenced by the manuscript, and '
   'none of the superseded ones is, so the paragraph cannot carry two values '
   'of one external constant or a gap on an undeclared basis',
   all(cited(n) for n in NEW)
   and not any(cited(n) for n in _old)
   and cited('SzCwtfmBareMed') and cited('FomCwtfmMed'),
   'published and cited %s; superseded and still cited %s'
   % ([n for n in NEW if cited(n)], [n for n in _old if cited(n)]))

print('\nassertions failed: %d %s' % (len(fail), fail))
if fail and DRIVE is None:
    raise SystemExit('fig_r16: %d assertion(s) failed: %s' % (len(fail), fail))

# ------------------------------------------------------------------ macros
OUTM = []


def m(name, val):
    assert name.isalpha(), name      # a macro name may contain letters only
    assert not any(x.startswith('\\newcommand{\\%s}' % name) for x in OUTM), \
        name
    OUTM.append('\\newcommand{\\%s}{%s}' % (name, val))


m('FgMargotEirp', sci(E_MAR, 3))
m('FgLitMargot', '%.2f' % CW_MAR)
m('FgLitMargotFive', '%.3f' % CW_MAR_FIVE)
m('FgGapBarePub', sci(GAP_PUB))
m('FgGapBareFive', sci(GAP_FIVE))

OUT = os.path.join(HERE, 'survey_numbers_round680%s.tex' % SUF)
with open(OUT, 'w') as fh:
    fh.write('%% GENERATED by fig_r16.py (round %d) -- do not hand-edit.\n'
             % ROUND)
    fh.write('\n'.join(OUTM) + '\n')

json.dump({'margot': {'eirp_W': E_MAR, 'snr': SNR_MAR,
                      'scale_to_common': SCALE_MAR,
                      'nu_lo_GHz': NU_LO, 'nu_hi_GHz': NU_HI,
                      'N_star': N_MAR, 'nu_rel': NUREL_MAR,
                      'cwtfm_published': CW_MAR,
                      'cwtfm_at_five': CW_MAR_FIVE,
                      'table1_eirp_W': TAB_EIRP,
                      'table1_eirp_five_W': TAB_EIRP_FIVE},
           'survey': {'n_systems': NSYS, 'nu_rel': NUREL,
                      'cwtfm_bare_median': CW_BARE_MED,
                      'cwtfm_bare_worst': CW_BARE_HI,
                      'cwtfm_eirp90_median': CW_AD_MED,
                      'cwtfm_eirp90_worst': CW_AD_HI},
           'gap_to_enriquez': {'basis': 'bare 5 sigma, both sides',
                               'published': GAP_PUB, 'at_five': GAP_FIVE,
                               'eirp90_published': GAP90_PUB,
                               'eirp90_at_five': GAP90_FIVE},
           'distance_ratio': {'nearest_carrier_search_pc': D_A[0],
                              'nearest_carrier_search': NEAR_A,
                              'ratio_carrier_search': MAS_PC / D_A[0],
                              'nearest_surveyed_pc': D_ALL[0],
                              'nearest_surveyed': NEAR_ALL,
                              'ratio_surveyed': R_NEAR_ALL,
                              'far_edge_pc': D_A[-1],
                              'ratio_far_edge': MAS_PC / D_A[-1]},
           'drive': DRIVE, 'failed': fail},
          open(os.path.join(HERE, 'fig_r16%s.json' % SUF), 'w'),
          indent=1, sort_keys=True)
print('\nwrote %s (%d macros)' % (os.path.basename(OUT), len(OUTM)))
