#!/usr/bin/env python3
"""The drift-following, continuum-subtracted visibility fit: macros and table.

Round-2 self-review made this a condition of acceptance (M1): the uniform
single-channel test of Table 9 is under-sensitive to a drifting carrier,
and one event had been measured the sensitive way with a very different
answer. So the sensitive estimator was applied to all thirteen stage-1
events from the recalibrated blocks.

The result is decisive in both directions:

  * beta Pictoris is recovered in 7 of its 8 windows at 6.1-9.5 sigma and
    HD 48370 at 5.9 sigma with a 2.7 sigma imaginary part, so the estimator
    works and still flags the displaced source as displaced;
  * all four unattributed events give |Re/sigma| <= 0.93.

It also contradicts the single-block fit reported at v3.58, which returned
5.5 sigma for CP-72 2713. The two differ in how the continuum is removed:
that window's stellar continuum is 10.9 mJy at 5.8 sigma, almost exactly
the 10.4 mJy the older fit attributed to a narrowband excess, while this
fit removes a local continuum per integration along the drift track and
finds -0.86 sigma. We report both and prefer the later one.
"""
import csv, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
VIS = json.load(open(os.path.join(HERE, 'visfit_all_v385.json')))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

TIDY = {'bet Pic': r'$\beta$~Pic', 'CP-72 2713': r'CP$-$72~2713',
        'HD 23484 Gaia DR3 4856592239127350400': 'HD 23484',
        'HD14055': 'HD~14055', 'HD 48370': 'HD~48370', '61 Vir': '61 Vir'}

rows = [(k, v) for k, v in VIS.items() if v.get('status') == 'ok']
assert len(rows) == len(VIS), 'a fit did not return'
rows.sort(key=lambda kv: -kv[1]['event']['star_snr'])

att = [(k, v) for k, v in rows if 'CO' in str(v['event'].get('disposition', ''))]
un = [(k, v) for k, v in rows if (k, v) not in att]

# The one window the estimator cannot reach: its drift track sweeps more
# channels than the continuum reference leaves, so every reference channel
# is inside the guard band. Report it as a limitation, not as a null.
def failed(v):
    return abs(v['star']['snr_re']) < 0.01


# Q15: HD 48370 has a large real part AND a 2.7 sigma imaginary part, so
# it is a displaced source and not a recovery at the star. Counting it as
# one made the paper say "beta Pictoris recovered in 7 windows at
# 5.9-9.5 sigma" where 5.9 was HD 48370.
BPIC = [(k, v) for k, v in att if k.startswith('bet Pic')]
REC = [(k, v) for k, v in BPIC
       if v['star']['snr_re'] >= 3.0 and abs(v['star']['snr_im']) <= 2.5]
DISP = [(k, v) for k, v in att
        if v['star']['snr_re'] >= 3.0 and abs(v['star']['snr_im']) > 2.5]
BAD = [(k, v) for k, v in att if failed(v)]

with open(os.path.join(HERE, 'tab_visfit_v385.tex'), 'w') as fh:
    fh.write('% generated by visfit_v385_calc.py -- do not edit\n')
    fh.write('\\begin{tabular}{@{}llrrrrl@{}}\n\\toprule\n')
    fh.write('Star & B & $N_{\\rm vis}$ & Re/$\\sigma$ & Im/$\\sigma$ & '
             'ctrl & verdict \\\\\n\\midrule\n')
    for group, head in ((un, 'Unattributed'),
                        (att, 'Attributed to CO (positive controls)')):
        fh.write('\\multicolumn{7}{@{}l}{\\emph{%s}} \\\\\n' % head)
        for k, v in group:
            st = v['star']
            cm = max([x for x in (v['ctrl_pos_max'], v['ctrl_freq_max'])
                      if x is not None] or [0.0])
            if failed(v):
                verd = 'track too wide to reference'
            elif abs(st['snr_im']) > 2.5 and st['snr_re'] >= 3.0:
                verd = 'displaced: phase inconsistent'
            elif st['snr_re'] >= 3.0 and st['snr_re'] > cm:
                verd = 'source at the stellar position'
            else:
                verd = 'nothing at the star'
            fh.write('%s & %s & %s & $%+.2f$ & $%+.2f$ & $%+.2f$ & %s \\\\\n'
                     % (TIDY.get(k.split('|')[0], k.split('|')[0]),
                        v['event'].get('band', ''),
                        '{:,}'.format(st['n_vis']).replace(',', '\\,'),
                        st['snr_re'], st['snr_im'], cm, verd))
    fh.write('\\bottomrule\n\\end{tabular}\n')

M('NFitTested', '%d' % len(rows))
M('NFitUnatt', '%d' % len(un))
M('NFitAtt', '%d' % len(att))
M('NFitAttRecov', '%d' % len(REC))
M('NFitBpicWin', '%d' % len(BPIC))
M('NFitDisplaced', '%d' % len(DISP))
M('FitAttReLo', '%.1f' % min(v['star']['snr_re'] for _, v in REC))
M('FitAttReHi', '%.1f' % max(v['star']['snr_re'] for _, v in REC))
M('NFitAttUnreachable', '%d' % len(BAD))
M('FitUnattMaxAbs', '%.2f' % max(abs(v['star']['snr_re']) for _, v in un))
M('NFitUnattAtStar',
  '%d' % sum(1 for _, v in un if v['star']['snr_re'] >= 3.0))
_hd48 = [v for k, v in att if k.startswith('HD 48370')]
if _hd48:
    M('FitHdFortyRe', '%.1f' % _hd48[0]['star']['snr_re'])
    M('FitHdFortyIm', '%.1f' % _hd48[0]['star']['snr_im'])
_cp = [v for k, v in un if k.startswith('CP-72')]
if _cp:
    M('FitCpRe', '%.2f' % _cp[0]['star']['snr_re'])
    M('FitCpIm', '%.2f' % _cp[0]['star']['snr_im'])
M('FitCtrlMax', '%.2f' % max(
    max([x for x in (v['ctrl_pos_max'], v['ctrl_freq_max'])
         if x is not None] or [0.0]) for _, v in rows))

open(os.path.join(HERE, 'survey_numbers_round44.tex'), 'w').write(
    '%% GENERATED by visfit_v385_calc.py -- do not hand-edit.\n'
    + '\n'.join(OUT) + '\n')

print('drift-following, continuum-subtracted fit on %d stage-1 events' % len(rows))
print('  beta Pic: %d of %d windows recovered at the star, %.1f-%.1f sigma;'
      ' %d unreachable' % (len(REC), len(BPIC),
                           min(v['star']['snr_re'] for _, v in REC),
                           max(v['star']['snr_re'] for _, v in REC), len(BAD)))
print('  displaced (large Re, large Im): %d' % len(DISP))
print('  unattributed: largest |Re/sigma| = %.2f, %d at the star'
      % (max(abs(v['star']['snr_re']) for _, v in un),
         sum(1 for _, v in un if v['star']['snr_re'] >= 3.0)))
print('  every control position and control frequency below %.2f sigma'
      % max(max([x for x in (v['ctrl_pos_max'], v['ctrl_freq_max'])
                 if x is not None] or [0.0]) for _, v in rows))
print('macros -> survey_numbers_round44.tex (%d)' % len(OUT))
