#!/usr/bin/env python3
"""One table of every false-alarm expectation this paper quotes.

Referee 1, point 1, and referee 2's request for the same thing from the
other direction. Six numbers are in circulation -- 1.1, 3.1, 3.2, 3.9,
4.4 and 4.7 -- and each is correct for its own population and correction,
but a reader should not have to reconstruct the denominators from six
sections. This emits them all in one place with their sample, window
count, rate, expectation, observed count and purpose, and marks the one
the paper uses for interpretation.

Referee 1, point 4, also asks for the tail probability of the observed
count under the adopted null, with the block clustering included. That is
computed by blockboot_v385.py and read back here so the table and the text
cannot disagree.
"""
import csv, glob, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
MAC = {}
for fn in glob.glob(os.path.join(HERE, 'survey_numbers*.tex')):
    for m in re.finditer(r'\\newcommand\{\\([A-Za-z]+)\}\{(.*?)\}\s*$',
                         open(fn).read(), re.M):
        MAC.setdefault(m.group(1), m.group(2))
V = lambda k: MAC.get(k, '--')

ROWS = list(csv.DictReader(open(os.path.join(HERE,
                                             'per_target_results_v3.91.csv'))))
NWIN = len(ROWS)
NWINA = sum(1 for r in ROWS if r['search_class'] == 'A')
NUNATT = sum(1 for r in ROWS if r['stage1_flag'] == 'True'
             and not (r['nearest_line'] and r['line_offset_kms']
                      and abs(float(r['line_offset_kms'])) <= 50))
NSTAGE = sum(1 for r in ROWS if r['stage1_flag'] == 'True')

#: sample, windows, rate, predicts, expected, observed, primary?
ENTRIES = [
    ('All searched windows, exchangeable', str(NWIN),
     r'$1/(\NCtrl+1)$', 'rank-first windows', V('ExpStageOneAll'), '--', False),
    ('Distinct (block, window) datasets', V('NDistinctDatasets'),
     r'$1/(\NCtrl+1)$', 'rank-first windows', V('BootPoisson'), '--', False),
    ('All windows, measured tail rate', str(NWIN),
     r'$\BootTail/(\NCtrl+1)$', 'rank-first windows',
     V('ExpStageOneTail'), '--', False),
    ('All windows, block-resampled', V('StageNullAllWin'),
     r'$\BootTail/(\NCtrl+1)$', 'rank-first windows', V('BootMean'), '--',
     False),
    ('Pseudo-star first-rank rate', str(NWIN),
     'measured on inner probes', 'rank-first windows',
     V('PseudoExpFlags'), '--', False),
    ('Class~A windows, block-resampled', V('BootWinA'),
     r'$\BootTail/(\NCtrl+1)$', 'rank-first Class~A windows',
     r'%s [%s--%s]' % (V('BootMeanA'), V('BootMeanALo'), V('BootMeanAHi')),
     '--', False),
    (r'\textbf{Class~A windows, block-resampled, trigger required}',
     V('StageNullAWin'),
     r'$\BootTail/(\NCtrl+1)$ if $\max c\geq\StageNullTrig$',
     r'\textbf{unattributed stage-1 events}',
     r'$\mathbf{%s}$ (%s--%s)' % (V('StageNullAMean'), V('StageNullALo'),
                                   V('StageNullAHi')),
     r'$\mathbf{%s}$' % V('StageNullObs'), True),
]

lines = [r'\begin{tabular}{@{}p{0.23\textwidth}rp{0.17\textwidth}p{0.15\textwidth}rr@{}}',
         r'\toprule',
         r'Sample & Windows & Rate per window & Predicts & Expected & '
         r'Obs. \\',
         r'\midrule']
# The tuple order IS the column order: sample, windows, rate, predicts,
# expected, observed. Naming the fourth field `exp` and the fifth `obs`
# was how the header came to disagree with the body in the first build of
# this table.
for sample, nwin, rate, predicts, expected, observed, primary in ENTRIES:
    lines.append('%s & %s & %s & %s & %s & %s \\\\'
                 % (sample, nwin, rate, predicts, expected, observed))
lines += [r'\bottomrule', r'\end{tabular}']
open(os.path.join(HERE, 'tab_falsealarm_v391.tex'), 'w').write(
    '\n'.join(lines) + '\n')

OUT = ['%% GENERATED by falsealarm_v391.py -- do not hand-edit.',
       r'\newcommand{\NFaRows}{%d}' % len(ENTRIES),
       r'\newcommand{\NUnattEvents}{%d}' % NUNATT]
open(os.path.join(HERE, 'survey_numbers_round46.tex'), 'w').write(
    '\n'.join(OUT) + '\n')

print('false-alarm expectations collected: %d rows' % len(ENTRIES))
for e in ENTRIES:
    print('  %-52s expected %-16s %s'
          % (e[0][:52].replace(r'\textbf{', '').replace('}', ''), e[4],
             'PRIMARY' if e[6] else ''))
print('observed unattributed: %d of %d stage-1' % (NUNATT, NSTAGE))
