#!/usr/bin/env python3
"""How much the single-channel visibility test dilutes a DRIFTING carrier.

Round-1 self-review, C5: the appendix reports a dedicated,
continuum-subtracted, drift-following fit of the CP-72 2713 event that
returns 10.4 mJy at the star, 5.5 sigma, while the uniform test of
Table 9 -- one channel, no continuum subtraction, applied identically to
all thirteen events -- returns 2.3 sigma on the same 405,860
visibilities.  Both are right; they are different estimators, and the
paper presented them as if they measured the same thing.

The difference matters for interpretation, because it is not symmetric:

  * the events attributed to CO are broad lines, several km/s wide, so any
    single channel inside the line carries the full surface brightness and
    the uniform test is fully sensitive to them;
  * a narrowband carrier that drifts sits in a given channel for only a
    fraction of the track, so the uniform test loses it by roughly the
    square root of the number of channels the track sweeps.

So the attributed events are a positive control for LOCALISATION -- the
test finds emission that is at the star and flags emission that is
displaced -- and not for narrowband-carrier sensitivity.  This generator
quantifies the dilution per event so the caveat carries a number.

Recovered drift rates come from the pipeline peak-frequency record and,
for the four unattributed events, from the visibility-test event list.
"""
import csv, json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

CAT = {r['eb']: r for r in
       csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.91.csv')))
       if r['stage1_flag'] == 'True'}
PK = {p['eb']: p for p in
      json.load(open(os.path.join(HERE, 'pipeline_peakfreq_v342.json')))}
VIS = json.load(open(os.path.join(HERE, 'vistest_v385.json')))
OLD = json.load(open(os.path.join(HERE, 'vistest_v384.json')))

# recovered drift rate, by execution block, from whichever record has it
DRIFT = {}
for eb, p in PK.items():
    if eb in CAT and p.get('dr') is not None:
        DRIFT[eb] = float(p['dr'])
for _, v in OLD.items():
    e = v.get('event') or {}
    if e.get('eb') in CAT and e.get('drift_Hz_s') is not None:
        DRIFT[e['eb']] = float(e['drift_Hz_s'])

rows = []
for k, v in VIS.items():
    if v.get('status') != 'ok':
        continue
    e = v['event']
    r = CAT[e['eb']]
    cw, ons = float(r['chanw_Hz']), float(r['on_source_s'])
    d = DRIFT.get(e['eb'])
    swept = abs(d) * ons / cw if d is not None else None
    rows.append(dict(tag=e['tag'], eb=e['eb'], band=e['band'],
                     att='CO' in str(e.get('disposition', '')),
                     drift=d, swept=swept, chanw=cw, onsrc=ons,
                     re_sig=v['star']['snr_re']))

known = [r for r in rows if r['swept'] is not None]
unatt = [r for r in known if not r['att']]
att = [r for r in known if r['att']]

M('VisDilKnown', '%d' % len(known))
M('VisDilTotal', '%d' % len(rows))
if unatt:
    M('VisDilUnattLo', '%.0f' % min(r['swept'] for r in unatt))
    M('VisDilUnattHi', '%.0f' % max(r['swept'] for r in unatt))
    M('VisDilUnattFacLo', '%.1f' % math.sqrt(min(r['swept'] for r in unatt)))
    M('VisDilUnattFacHi', '%.1f' % math.sqrt(max(r['swept'] for r in unatt)))
if att:
    M('VisDilAttLo', '%.0f' % min(r['swept'] for r in att))
    M('VisDilAttHi', '%.0f' % max(r['swept'] for r in att))

# The one event measured both ways: the observed ratio against the
# fully-diluted expectation.
CP = [r for r in rows if r['tag'].startswith('CP-72')]
FIT = json.load(open(os.path.join(HERE, 'visfit_cp72_v358.json')))
if CP:
    cp = CP[0]
    fit_sig = float(FIT['flagged']['A_star_snr'])
    M('VisCpUniform', '%.1f' % cp['re_sig'])
    M('VisCpFit', '%.1f' % fit_sig)
    M('VisCpRatio', '%.1f' % (fit_sig / cp['re_sig']))
    M('VisCpSwept', '%.0f' % cp['swept'])
    M('VisCpFullDil', '%.1f' % math.sqrt(cp['swept']))

open(os.path.join(HERE, 'survey_numbers_round42.tex'), 'w').write(
    '%% GENERATED by visdilute_v385.py -- do not hand-edit.\n' + '\n'.join(OUT) + '\n')

print('drift-track dilution of the single-channel visibility test:')
print('  %-12s %-20s %-3s %10s %9s %8s' %
      ('star', 'eb', 'att', 'drift Hz/s', 'ch swept', 'Re/sig'))
for r in sorted(rows, key=lambda r: (r['att'], -(r['swept'] or 0))):
    print('  %-12s %-20s %-3s %10s %9s %8.1f'
          % (r['tag'][:12], r['eb'], 'CO' if r['att'] else '--',
             ('%.0f' % r['drift']) if r['drift'] is not None else '--',
             ('%.1f' % r['swept']) if r['swept'] is not None else '--',
             r['re_sig']))
if CP:
    print('  CP-72 measured both ways: uniform %.1f sigma, drift-following '
          'continuum-subtracted fit %.1f sigma (x%.1f); the track sweeps '
          '%.0f channels, full dilution would be x%.1f'
          % (cp['re_sig'], fit_sig, fit_sig / cp['re_sig'], cp['swept'],
             math.sqrt(cp['swept'])))
print('macros -> survey_numbers_round42.tex (%d)' % len(OUT))
