#!/usr/bin/env python3
r"""Macros for the HD 23484 held-out event, including its own disposition.

Referee 2 found that the campaign disposes of this event itself: the same
tuning was searched in further execution blocks of the same star, and the
stellar position does not approach threshold in any of them. That is a
recurrence test the campaign performed without anyone noticing, and it is a
stronger disposition than the "marginal single cell" argument the text had.

Source: heldout_v352.json, refreshed from the campaign. Read-only.
"""
import json

HO = json.load(open('heldout_v352.json'))
W = [w for w in HO['windows'] if 'HD 23484' in w['star']]

# the flagged window, and the other blocks that cover the same tuning
flag = [w for w in W if w.get('stage1')]
assert len(flag) == 1, 'expected exactly one stage-1 HD 23484 window'
f = flag[0]
lo, hi = sorted([f['freq_lo_GHz'], f['freq_hi_GHz']])
same = [w for w in W if not w.get('stage1')
        and abs(sorted([w['freq_lo_GHz'], w['freq_hi_GHz']])[0] - lo) < 0.01]

ranks = sorted(w['n_control_ge_star'] for w in same)
ts = sorted(w['star_peak_snr'] for w in same)
cs = sorted(w['control_peak_snr'] for w in same)

M = [('HOOddNRep',     '%d' % len(same)),
     ('HOOddRepRanks', ', '.join(str(r) for r in ranks)),
     ('HOOddRepTLo',   '%.2f' % ts[0]),
     ('HOOddRepTHi',   '%.2f' % ts[-1]),
     ('HOOddRepCtrlLo', '%.2f' % cs[0]),
     ('HOOddRepCtrlHi', '%.2f' % cs[-1]),
     # Referee 2, verified against Splatalogue: AlF v=0 at 230.79389 GHz,
     # E_u = 44 K, log A = -3.81, inside the paper's own line-strength cut.
     # The "no transition within 252 MHz" claim was true only of the frozen
     # 17-transition mask, not of the catalogue.
     ('HOOddDbOffKms', '4.6')]

with open('survey_numbers_hd23484.tex', 'w') as fh:
    fh.write('%% GENERATED by hd23484_calc.py -- do not hand-edit.\n')
    for k, v in M:
        fh.write('\\newcommand{\\%s}{%s}\n' % (k, v))
for k, v in M:
    print('  %-16s %s' % (k, v))
print('\nthe flagged window ranks 0 of %d; the same tuning in %d further blocks '
      'ranks %s' % (f['n_control'], len(same), ', '.join(str(r) for r in ranks)))
