#!/usr/bin/env python3
r"""Macros for the pointing audit of the unsearched target-bands.

Source: untried_eb_audit_v346.json (copy of /shared/ASTRA/untried_eb_audit.json),
an independent re-crossmatch from ALMA obscore of every target-band the pipeline
failed to deliver. The result is that most were never observed: the observing
units were pointed at solar-system ephemeris targets, and the candidate
crossmatch admitted them because obscore reports an enormous field of view for
such deliveries.

v3.46 correction: the separation statistics are now taken over the never-pointed
target-bands only, one number per target-band, being the distance to the NEAREST
field centre among that target-band's candidate observing units. The previous
version pooled every candidate unit of every failed target-band, including the
eight that do point at the star, which put the median at 1.4 deg and the maximum
at 8777 arcsec. The audit document's own figures, 250 to 8205 arcsec with a
median of 1.6 deg, are reproduced by the population used here.
"""
import json
import statistics

d = json.load(open('untried_eb_audit_v346.json'))
t = d['targets']
never = [v for v in t.values() if v.get('n_mous_pointing_at_star') == 0]


def nearest(v):
    s = [m['min_separation_star_to_field_arcsec'] for m in v.get('candidate_mous', [])
         if m.get('min_separation_star_to_field_arcsec') is not None]
    return min(s) if s else None


seps = [x for x in (nearest(v) for v in never) if x is not None]
pointed = [x for x in (nearest(v) for v in t.values()
                       if v.get('n_mous_pointing_at_star') != 0) if x is not None]
fovs = [m['nearest_field_fov_half_arcsec']
        for v in t.values() for m in v.get('candidate_mous', [])
        if m.get('nearest_field_fov_half_arcsec')]
thin = lambda n: format(int(round(n)), ',').replace(',', r'\,')
M = [('NAudit',        '%d' % len(t)),
     ('NNotPointed',   '%d' % len(never)),
     ('NPointed',      '%d' % (len(t) - len(never))),
     ('SepMedianDeg',  '%.1f' % (statistics.median(seps) / 3600.0)),
     ('SepMinArc',     '%.0f' % min(seps)),
     ('SepMaxArc',     thin(max(seps))),
     ('SepPointedArc', '%.1f' % max(pointed)),
     ('FovMaxDeg',     '%.0f' % (max(fovs) / 3600.0)),
     ('PmFastest',     '5.12'),
     ('PmYears',       '49')]
with open('survey_numbers_pointing.tex', 'w') as f:
    f.write('%% GENERATED by pointing_calc.py -- do not hand-edit.\n')
    for k, v in M:
        f.write('\\newcommand{\\%s}{%s}\n' % (k, v))
for k, v in M:
    print('  %-14s %s' % (k, v))
