#!/usr/bin/env python3
r"""Gate: no generated fragment may be older than the generator that owns it.

The ledger fragment and the mask ladder were the same failure one file
apart: a `tab_*.tex` or a frozen `*.json` still on disk from a run of its
generator that happened before the inputs changed. Both looked
authoritative -- both were generated, both carried a "do not hand-edit"
header -- and both disagreed with the analysis the paper now describes. A
generated file is not thereby current; it is only a record of the last time
someone ran something.

Nothing checked this, so this does, three ways:

  S1  every generated fragment the manuscript inputs declares a generator
      in its own header, and that generator exists;
  S2  no fragment is older than its generator, than the catalogue, or than
      any frozen record the generator reads -- an output older than an
      input is stale by definition and needs no semantic knowledge to spot;
  S3  re-running the generator into a scratch directory reproduces the
      fragment byte for byte, where the generator supports being pointed at
      one.  S2 catches staleness cheaply; S3 catches a fragment that was
      edited by hand or left behind by a generator that has since changed
      its mind.

S2 is deliberately crude. A timestamp comparison knows nothing about what a
fragment means, which is exactly why it cannot be fooled by a fragment that
is internally consistent and wrong -- the failure mode both of the known
cases had.

    python3 fragstale.py [--drive N] [--quiet]

Exit 1 if any fragment is stale. --drive 1..3 breaks one clause each.
"""
import glob
import json
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
HDR = re.compile(r'GENERATED by ([A-Za-z0-9_]+\.py)', re.I)
# Inputs every fragment depends on even when its own generator does not name
# them: the catalogue is the spine, and the frozen records are the analysis.
def _catalogue_of_record():
    """The one catalogue the manuscript names, not every file matching it.

    ★ The directory holds ten historical catalogues, and an unrelated
    generator rewrites one of them on every run, so globbing the pattern
    made the spine's timestamp jump and reported four current fragments as
    stale.  A gate that fires on a file nobody reads is worse than no gate:
    it trains its reader to ignore it.
    """
    try:
        import manuscript
        src = manuscript.flat()
    except Exception:
        src = ''
    named = re.findall(r'(per_target_results[\w.]*\.csv)', src)
    for n in named:
        p = os.path.join(HERE, n)
        if os.path.exists(p):
            return [p]
    c = sorted(glob.glob(os.path.join(HERE, 'per_target_results*.csv')))
    return c[-1:] if c else []


SPINE = (_catalogue_of_record()
         + sorted(glob.glob(os.path.join(HERE, 'r9inputs', '*.json'))))
# Fragments that are deliberately frozen copies of a retired generator's
# output: declared, with the reason, so "frozen" is a decision and not an
# absence of a generator.
FROZEN_OK = {}


def inputted():
    """Fragments the manuscript actually inputs, flattened."""
    try:
        import manuscript
        src = manuscript.flat()
    except Exception:
        src = ''
        for f in glob.glob(os.path.join(HERE, 'sections', '*.tex')):
            src += open(f, errors='ignore').read()
    names = set(re.findall(r'\\input\{([A-Za-z0-9_/]+)\}', src))
    out = []
    for n in sorted(names):
        p = os.path.join(HERE, n if n.endswith('.tex') else n + '.tex')
        if os.path.exists(p) and os.path.basename(p).startswith('tab'):
            out.append(p)
    return out


def main(argv):
    drive = 0
    quiet = '--quiet' in argv
    for i, a in enumerate(argv):
        if a == '--drive':
            drive = int(argv[i + 1])
    frags = inputted()
    stale, nogen, mismatch = [], [], []
    spine_mtime = max((os.path.getmtime(p) for p in SPINE), default=0)

    for f in frags:
        base = os.path.basename(f)
        head = ''.join(open(f, errors='ignore').readline() for _ in range(3))
        m = HDR.search(head)
        if drive == 1 and f is frags[0]:
            m = None
        gen = m.group(1) if m else None
        gpath = os.path.join(HERE, gen) if gen else None
        if gen is None or not os.path.exists(gpath):
            if base not in FROZEN_OK:
                nogen.append((base, gen or '(no header)'))
            continue
        ft = os.path.getmtime(f)
        gt = os.path.getmtime(gpath)
        if drive == 2 and not stale:
            gt = ft + 1
        older = []
        if gt > ft:
            older.append('its generator %s' % gen)
        if spine_mtime > ft:
            older.append('an input it depends on')
        if older:
            stale.append((base, gen, ', '.join(older)))

    # S3 -- byte reproduction, where the generator takes an output directory
    repro = []
    for f in frags:
        base = os.path.basename(f)
        head = ''.join(open(f, errors='ignore').readline() for _ in range(3))
        m = HDR.search(head)
        if not m:
            continue
        gen = m.group(1)
        gpath = os.path.join(HERE, gen)
        if not os.path.exists(gpath):
            continue        # already reported by S1
        gsrc = open(gpath, errors='ignore').read()
        if '--out' not in gsrc:
            continue
        d = tempfile.mkdtemp(prefix='fragstale_')
        try:
            cmd = [sys.executable, os.path.join(HERE, gen), '--out', d]
            if '--cat' in gsrc:
                cmd += ['--cat', HERE]
                for pk in ('per_target_results_v3.99.csv', 'starrv_v399.json',
                           'bary_v405.json', 'm3a_result_v400.json',
                           'freqocc_v405.json'):
                    cmd += ['--pick', pk]
            subprocess.run(cmd, capture_output=True, text=True, timeout=600)
            cand = os.path.join(d, base)
            if os.path.exists(cand):
                a = open(cand, 'rb').read()
                b = open(f, 'rb').read()
                if drive == 3:
                    b = b + b'\n'
                if a != b:
                    repro.append((base, gen))
        except Exception:
            pass
        finally:
            import shutil
            shutil.rmtree(d, ignore_errors=True)
        mismatch = repro

    # ★ S4 -- a SHADOW copy.  `\input{tab_selection}` resolves to the
    #   top-level file, while the generator writes `tables/tab_selection.tex`
    #   -- so the manuscript typesets whichever copy was left behind, and the
    #   live one is never read.  The two happen to be identical today, which
    #   is the whole danger: the shadow is invisible until the day they
    #   differ, and then the gate above cannot help because the stale file
    #   IS the one being typeset.
    shadow = []
    for f in frags:
        base = os.path.basename(f)
        alt = os.path.join(HERE, 'tables', base)
        if os.path.dirname(f) == HERE and os.path.exists(alt):
            same = open(f, 'rb').read() == open(alt, 'rb').read()
            older = os.path.getmtime(f) < os.path.getmtime(alt) - 1
            # TeX does not search `tables/`, so the top-level copy is the one
            # typeset and it cannot simply be deleted.  What it must never be
            # is a DIFFERENT file from the live one, or an older one.
            if not same or older:
                shadow.append((base, 'tables/' + base,
                               'differs' if not same else 'older'))
    if drive == 4:
        shadow.append(('drive', 'drive', 'drive'))
    fail = len(stale) + len(nogen) + len(mismatch) + len(shadow)
    if not quiet:
        print('fragstale: %d generated fragments the manuscript inputs, '
              '%d spine inputs' % (len(frags), len(SPINE)))
        for b, g in nogen:
            print('  FAIL S1 %-28s declares no live generator (%s)' % (b, g))
        for b, g, why in stale:
            print('  FAIL S2 %-28s is older than %s' % (b, why))
        for b, g in mismatch:
            print('  FAIL S3 %-28s does not reproduce from %s' % (b, g))
        for b, a, same in shadow:
            print('  FAIL S4 %-28s shadows %s, and \\input takes the '
                  'shadow (%s)' % (b, a, same))
        print('fragstale: %d FAIL' % fail)
    return 1 if fail else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
