#!/usr/bin/env python3
"""Gate: no two generators may write the same survey_numbers_roundNN.tex,
and every such file the manuscript \\inputs must have exactly one writer.

Written after an occurrence-rate generator added in the v3.99 cycle
silently overwrote survey_numbers_round47.tex, which stageonenull_v399.py
owns. The build did not complain, because the macros it destroyed were
still in the .aux from the previous run. Nothing in gate.sh could see it.
The only defence is to check the writers, so this does.

Exit status 1 on any collision, missing writer, or orphan file.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAT = re.compile(r'survey_numbers_round(\d+)\.tex')

writers = {}
for fn in sorted(os.listdir(HERE)):
    if not fn.endswith('.py') or fn == os.path.basename(__file__):
        continue
    src = open(os.path.join(HERE, fn), errors='ignore').read()
    # A generator "writes" a round file if it names it in a write context.
    for mm in PAT.finditer(src):
        name = mm.group(0)
        # A generator is a WRITER of a round file if the filename appears
        # either next to an explicit write, or as the value of an OUT-style
        # variable that is later written. A generator that only READS a
        # round file -- viscal_v399.py reads round38 to recombine the
        # budget -- must not be counted, so read contexts are excluded.
        line_start = src.rfind('\n', 0, mm.start()) + 1
        line_end = src.find('\n', mm.end())
        line = src[line_start:line_end if line_end > 0 else len(src)]
        near = src[max(0, mm.start() - 80):mm.end() + 80]
        is_read = ('.read()' in line or 'open(p).read' in near
                   or re.search(r'def\s+\w+\([^)]*%s' % re.escape(name),
                                src) is not None)
        # v4.06: TEX/TEXOUT added.  A gate that recognises only three
        # variable names can be defeated by choosing a fourth, which is
        # what happened: p90r7_v406.py assigned its round file to `TEX`
        # and this gate reported NO WRITER for a file a generator plainly
        # writes.  The generator was renamed to house style AND the
        # pattern widened, because the next one will pick another name.
        assigns_out = re.match(
            r'\s*(OUT|OUTNAME|OUTFILE|OUTPATH|TEX|TEXOUT|DEST)\s*=',
            line) is not None
        # v4.09: AND the pattern was defeated a second time, exactly as the
        # note above predicted it would be.  Two generators in this cycle
        # suffix every output under `--drive N` -- D36's rule that a test may
        # not write where production reads -- so the round file reaches
        # `os.path.splitext(...)` rather than an `open(..., 'w')`.  Recognise
        # that shape too, instead of waiting for a third variable name.
        assigns_out = assigns_out or 'splitext(' in line
        writes_here = ("'w'" in line or '"w"' in line or '.write' in line)
        if (writes_here or assigns_out) and not is_read:
            writers.setdefault(name, set()).add(fn)

# ★ DEFEATED A THIRD TIME, by a third variable name (`OUTNAME`, holding the
# basename so a drive suffix can be applied before the path is joined).  The
# name list is widened again, but widening it is plainly not the fix -- the
# note above predicted a third name and here it is.  So the writer is now
# also taken from the ROUND FILE'S OWN HEADER, which every generator in this
# tree writes and which no choice of variable name can hide.  The header is
# consulted only where the source scan found NO writer, so it can close a
# false "NO WRITER" without ever inventing a collision.
HDR = re.compile(r'generated by ([A-Za-z0-9_]+\.py)', re.I)
for fn in sorted(os.listdir(HERE)):
    if not PAT.fullmatch(fn):
        continue
    if fn in writers:
        continue
    with open(os.path.join(HERE, fn), errors='ignore') as fh:
        head = ''.join(fh.readline() for _ in range(3))
    mh = HDR.search(head)
    if mh and os.path.exists(os.path.join(HERE, mh.group(1))):
        writers.setdefault(fn, set()).add(mh.group(1) + ' (self-declared)')

# Rounds whose generator has been retired are shipped as frozen copies and
# restored by make_all.sh; those have a legitimate single "writer".
FROZEN = os.path.join(HERE, 'frozen_macros')
if os.path.isdir(FROZEN):
    for fn in sorted(os.listdir(FROZEN)):
        if PAT.fullmatch(fn):
            writers.setdefault(fn, set()).add('frozen_macros/ (retired)')

import manuscript  # v4.10: split manuscript
# v4.10: the manuscript is split into sections/, so this must read the
# FLATTENED document.  Reading the main file alone leaves this check
# looking at a preamble, where it can only be vacuous or wrong.
inputs = set()
for mm in re.finditer(r'\\input\{(survey_numbers_round\d+)\}', manuscript.flat()):
    inputs.add(mm.group(1) + '.tex')

fail = 0
for name in sorted(writers, key=lambda n: int(PAT.match(n).group(1))):
    who = sorted(writers[name])
    if len(who) > 1:
        print('COLLISION %s written by %s' % (name, ', '.join(who)))
        fail += 1

for name in sorted(inputs, key=lambda n: int(PAT.match(n).group(1))):
    if name not in writers:
        print('NO WRITER %s is \\input by the manuscript but no generator '
              'writes it' % name)
        fail += 1
    if not os.path.exists(os.path.join(HERE, name)):
        print('MISSING   %s is \\input by the manuscript and does not exist'
              % name)
        fail += 1

for name in sorted(writers, key=lambda n: int(PAT.match(n).group(1))):
    if name not in inputs:
        print('ORPHAN    %s is generated but never \\input' % name)
        fail += 1

print('roundcollide: %d round files, %d inputs, %d problems'
      % (len(writers), len(inputs), fail))
# v4.06: raise rather than sys.exit, so selftest_v406.py can drive this gate's
# own detection logic in both directions.  A gate whose failure mode cannot be
# distinguished from a crash is hard to test.
assert not fail, 'roundcollide: %d problem(s)' % fail
