#!/usr/bin/env python3
"""Cluster-robust statistics for the held-out rank departure (referee 3, v3.54).

Why this exists
---------------
v3.52 reports the held-out rank displacement twice: once at window level
(D, p from a one-sample KS test against U(0,1) over the 185 null windows) and
once as "one median rank per star over 15 stars gives D = 0.37 (p = 0.02)".

The second test is not valid.  Under the null the per-star *medians* are not
U(0,1): the median of n uniform draws concentrates about 0.5 (Beta(k, n-k+1)),
so a KS test of 15 such medians against U(0,1) rejects far too often.
Simulated with the campaign's own group sizes (20 000 draws, windows i.i.d.
U(0,1) within each star):

    null E[D]      = 0.316        (5-95 % 0.244-0.393)
    P(D >= 0.369)  = 0.123        <- the honest p for the quoted D
    P(naive KS p < 0.05) = 0.220  <- the test's real size at nominal 5 %

So the quoted p = 0.02 is an artefact of the test, not evidence.  The finding
itself survives, but it needs a test that is valid under clustering.  This
script computes two that are:

  * a sign test on execution-block mean ranks (48 blocks);
  * a star-clustered bootstrap of the pooled median (15 clusters, 20 000
    resamples, fixed seed), reported as a 95 per cent interval.

Usage:  python3 v353_heldout_cluster.py [heldout_v352.json]
Writes: survey_numbers_round21.tex   (add it to make_all.sh and to the
        \input list in the manuscript preamble)
"""
import json
import sys

import numpy as np
from scipy import stats

SRC = sys.argv[1] if len(sys.argv) > 1 else "heldout_v352.json"
OUT = "survey_numbers_round21.tex"
SURVEY = "per_target_results_v3.52.csv"
NBOOT = 20000
SEED = 20260912

rec = json.load(open(SRC))
win = [w for w in rec["windows"]
       if not w.get("detection") and not w.get("stage1")]
p = np.array([w["p_star_empirical"] for w in win])
star = np.array([w["star"] for w in win])
eb = np.array([w["eb"] for w in win])
assert len(p) > 0, "empty held-out null sample"
print("null sample: %d windows, %d stars, %d blocks"
      % (len(p), len(set(star)), len(set(eb))))

# --- block-level sign test -------------------------------------------------
blocks = sorted(set(eb))
bmean = np.array([p[eb == b].mean() for b in blocks])
nbelow = int((bmean < 0.5).sum())
sign_p = stats.binomtest(nbelow, len(bmean), 0.5).pvalue

# --- star-clustered bootstrap of the pooled median -------------------------
rng = np.random.default_rng(SEED)
stars = sorted(set(star))
idx = {s: np.where(star == s)[0] for s in stars}
meds = np.empty(NBOOT)
for i in range(NBOOT):
    pick = rng.choice(stars, len(stars), replace=True)
    meds[i] = np.median(np.concatenate([p[idx[s]] for s in pick]))
lo, hi = np.percentile(meds, [2.5, 97.5])

print(f"windows {len(p)}  blocks {len(blocks)}  stars {len(stars)}")
print(f"pooled median rank          {np.median(p):.3f}")
print(f"blocks with mean rank < 0.5 {nbelow} of {len(bmean)}  sign p = {sign_p:.4f}")
print(f"star-clustered bootstrap    95% interval {lo:.3f}-{hi:.3f}"
      f"   P(median >= 0.5) = {np.mean(meds >= 0.5):.3f}")

# --- the survey's own in-sample rank distribution, for comparison ----------
import csv
rows = list(csv.DictReader(open(SURVEY)))
sp = np.array([float(r["p_rank_addone"]) for r in rows])
sname = np.array([r["star_name"] for r in rows])
sstars = sorted(set(sname))
sidx = {s: np.where(sname == s)[0] for s in sstars}
rng2 = np.random.default_rng(SEED)
smeds = np.empty(NBOOT)
for i in range(NBOOT):
    pick = rng2.choice(sstars, len(sstars), replace=True)
    smeds[i] = np.median(np.concatenate([sp[sidx[s]] for s in pick]))
slo, shi = np.percentile(smeds, [2.5, 97.5])
d2, p2 = stats.ks_2samp(sp, p)
print(f"survey in-sample median      {np.median(sp):.3f}"
      f"  95% interval {slo:.3f}-{shi:.3f}  P(>=0.5) = {np.mean(smeds >= 0.5):.3f}")
print(f"two-sample KS survey vs held-out  D = {d2:.3f}  p = {p2:.3f}")

with open(OUT, "w") as f:
    f.write("%% GENERATED by v353_heldout_cluster.py -- do not hand-edit.\n")
    f.write("\\newcommand{\\HOBlockBelow}{%d}\n" % nbelow)
    f.write("\\newcommand{\\HOBlockN}{%d}\n" % len(bmean))
    # a p-value that rounds to zero should be printed as a bound, not as 0.000
    f.write("\\newcommand{\\HOBlockSignP}{%s}\n"
            % ("<0.001" if sign_p < 5e-4 else "%.3f" % sign_p))
    f.write("\\newcommand{\\HOBootLo}{%.2f}\n" % lo)
    f.write("\\newcommand{\\HOBootHi}{%.2f}\n" % hi)
    f.write("\\newcommand{\\SurvMedP}{%.2f}\n" % np.median(sp))
    f.write("\\newcommand{\\SurvBootLo}{%.2f}\n" % slo)
    f.write("\\newcommand{\\SurvBootHi}{%.2f}\n" % shi)
    f.write("\\newcommand{\\SurvHOKsD}{%.2f}\n" % d2)
    f.write("\\newcommand{\\SurvHOKsP}{%.2f}\n" % p2)
print("wrote", OUT)
