#!/usr/bin/env python3
"""Empirical calibration of the spatial-control null, and the rank CDF figure.

Referees asked for two things the paper did not have: the stage-1 expectation
recomputed from the observed held-out rank distribution instead of assumed
exchangeability, and a figure showing the rank distributions themselves.
Both are produced here from the released catalogue and the campaign export.
"""
import json, csv, math, os
import numpy as np
import matplotlib
matplotlib.use('Agg')
# Type 42 (TrueType): matplotlib's default Type 3 would fail the release gate
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

HO = json.load(open(os.path.join(HERE, 'heldout_v352.json')))['windows']
R = list(csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.52.csv'))))

# Null pool: every held-out window except the beta Pic CO detections, which are
# real astrophysical signal and must not calibrate a false-alarm rate.
null = [w for w in HO if not w.get('line_attributed')]
k = sum(1 for w in null if w.get('unattributed_stage1'))
n = len(null)
NW = len(R)
p_hat = k / n
LO, HI = 0.0253 / n, 3.689 / n          # exact Poisson limits for k = 1

M('RankCalN', '%d' % n)
M('RankCalK', '%d' % k)
M('RankCalRate', '%.2f' % (100.0 * p_hat))
M('RankCalOneIn', '%d' % round(1 / p_hat))
M('RankCalRatio', '%.1f' % (p_hat * 513))
M('RankCalExpIdeal', '%.2f' % (NW / 513))
M('RankCalExpEmp', '%.1f' % (NW * p_hat))
M('RankCalExpLo', '%.2f' % (NW * LO))
M('RankCalExpHi', '%.1f' % (NW * HI))
M('RankCalPgeOne', '%.0f' % (100 * (1 - math.exp(-NW * p_hat))))

# Is the displacement widespread or driven by a subset?
import collections, statistics as st
byst = collections.defaultdict(list)
for w in null:
    if w.get('p_star_empirical') is not None and not w.get('unattributed_stage1'):
        byst[w['star']].append(w['p_star_empirical'])
meds = {s: st.median(v) for s, v in byst.items()}
M('RankCalStarsBelow', '%d' % sum(1 for v in meds.values() if v < 0.5))
M('RankCalStarsN', '%d' % len(meds))

open(os.path.join(HERE, 'survey_numbers_round22.tex'), 'w').write(
    '%% Generated by v357_rankcal.py -- do not edit by hand.\n' + '\n'.join(OUT) + '\n')
print('\n'.join(OUT))

# ---------------------------------------------------------------- the figure
ho = np.array(sorted(w['p_star_empirical'] for w in null
                     if w.get('p_star_empirical') is not None))
sv = np.array(sorted(float(r['p_rank_addone']) for r in R
                     if r['p_rank_addone'] not in ('', 'nan')))
fig, ax = plt.subplots(figsize=(3.5, 1.72))
ax.plot([0, 1], [0, 1], color='0.55', lw=0.9, ls='--', label='uniform')
ax.step(sv, np.arange(1, sv.size + 1) / sv.size, where='post', lw=1.4,
        color='#1f4e9c', label='survey (%d)' % sv.size)
ax.step(ho, np.arange(1, ho.size + 1) / ho.size, where='post', lw=1.4,
        color='#c2432b', label='held out (%d)' % ho.size)
ax.set_xlabel(r'add-one rank of the star among its %d controls' % 512, fontsize=6.8)
ax.set_ylabel('cumulative fraction', fontsize=6.8)
ax.tick_params(labelsize=6.2)
ax.set_xlim(0, 1); ax.set_ylim(0, 1)
ax.legend(fontsize=5.9, loc='lower right', frameon=True, framealpha=0.9)
fig.tight_layout(pad=0.25)
fig.savefig(os.path.join(HERE, 'figures', 'rank_cdf.pdf'))
print('wrote figures/rank_cdf.pdf  (survey n=%d, held-out n=%d)' % (sv.size, ho.size))
