#!/usr/bin/env python3
"""R1-1 (v3.92): what extending the visibility-domain test to every
threshold crossing requires, costed from products we already hold.

Referee 1 asked for the test to be applied to all 75 threshold crossings
rather than only the 13 the spatial screen flagged, and asked that if the
products no longer exist we say exactly which subset can be tested and
why. This generator answers that quantitatively instead of vaguely.
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.92.csv'))))
OUT = os.path.join(HERE, 'survey_numbers_round54.tex')

cross = [r for r in CAT if r['crossing'] == 'True']
tested = {r['eb'] for r in CAT if r['stage1_flag'] == 'True'}
need_ebs = sorted({r['eb'] for r in cross} - tested)
need_win = [r for r in cross if r['eb'] in need_ebs]

sizes = {}
meta = json.load(open(os.path.join(HERE, 'archive_meta_v381.json')))
for v in meta['mous'].values():
    sizes.update(v.get('sizes') or {})
gb = sum(sizes.get(e, 0) for e in need_ebs) / 1e9
# the campaign's own measured cost model
hrs = (len(need_ebs) * 384.0 + gb * 113.0) / 3600.0

L = ['%% GENERATED by visextend_v392.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('VxNCross', '%d' % len(cross))
m('VxNTestedWin', '%d' % sum(1 for r in CAT if r['stage1_flag'] == 'True'))
m('VxNUntestedWin', '%d' % len(need_win))
m('VxNBlocks', '%d' % len(need_ebs))
m('VxTB', '%.2f' % (gb / 1000.0))
m('VxHours', '%.0f' % hrs)
open(OUT, 'w').writelines(L)
print('%s: %d macros' % (os.path.basename(OUT), len(L) - 1))
print('  threshold crossings %d; visibility-tested %d; untested %d windows '
      'in %d blocks' % (len(cross), len(tested), len(need_win), len(need_ebs)))
print('  extension cost: %.2f TB, %.0f h serial on the measured cost model'
      % (gb / 1000.0, hrs))
