#!/usr/bin/env python3
"""Retire generated macros that the manuscript does not reference.

The v3.46 referee round found 31 of the 129 round-13 macros unused, six of
them the archive audit that never reached the reader.  Those are now used.
This step closes the remaining hygiene: it deletes, from the generated
`survey_numbers*.tex` files, every `\newcommand` that no `.tex` file in this
folder references.  The generators keep computing the quantities, so nothing
is lost and re-enabling one means deleting a name from the report below.

Run last in `make_all.sh`, after every generator has written its file.
It refuses to remove a macro that is referenced anywhere, so it cannot break
a build; run `macrosweep.py` afterwards to confirm zero orphans remain.
"""
import glob, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)

MACFILES = sorted(glob.glob("survey_numbers*.tex"))

# ★ v4.11: A STRAY `.tex` IN THIS DIRECTORY SILENTLY DISABLES THIS PASS.
# The consumer list below is `glob.glob("*.tex")`, so anything with that
# suffix counts as a document that references macros.  A probe copy of the
# manuscript -- which is what every agent makes when it wants to typeset one
# section -- references every macro in the paper, INCLUDING the superseded
# ones this pass exists to delete.  With one sitting here, retirement
# retires nothing and says so in a line nobody reads: a check that cannot
# fail, which is this project's seventeenth instance of that family.  Two
# were sitting here during round 10.
#
# So the root is now declared rather than globbed.  A `.tex` here is
# legitimate only if it is the manuscript, a generated macro file, a
# fragment the manuscript \inputs, or a generated fragment with a writer --
# either a `GENERATED by x.py` header or some generator in the tree that
# names it.  Anything else is a scratch file and FAILS LOUDLY, because the
# alternative is that it goes quiet.  And nothing in the root but the
# manuscript may contain `\begin{document}`: a second document in the build
# root IS a probe, whatever it is called.
def _root_tex_gate():
    import manuscript
    man = manuscript.main_file()
    inputted = {m + '.tex' for m in
                re.findall(r'\\input\{([^}]+)\}', manuscript.flat())}
    hdr = re.compile(r'GENERATED by ([A-Za-z0-9_]+\.py)', re.I)
    pysrc = {}
    for p in sorted(glob.glob('*.py')):
        pysrc[p] = open(p, encoding='utf-8', errors='ignore').read()
    bad = []
    for f in sorted(glob.glob('*.tex')):
        txt = open(f, encoding='utf-8', errors='ignore').read()
        if f != man and r'\begin{document}' in txt:
            bad.append((f, 'contains \\begin{document}: a second document in '
                           'the build root is a probe'))
            continue
        if f == man or f in MACFILES or f in inputted:
            continue
        head = ''.join(txt.splitlines(True)[:4])
        mh = hdr.search(head)
        if mh and os.path.exists(mh.group(1)):
            continue
        if any(f in s for p, s in pysrc.items() if p != os.path.basename(
                __file__)):
            continue
        bad.append((f, 'neither \\input by the manuscript nor written by any '
                       'generator in this tree'))
    if bad:
        print('retire_macros: UNEXPECTED .tex IN THE BUILD ROOT -- '
              'retirement would be a check that cannot fail')
        for f, why in bad:
            print('  FAIL %-34s %s' % (f, why))
        raise SystemExit('retire_macros: %d unexpected .tex in the build root'
                         % len(bad))
    return len(glob.glob('*.tex'))


_NROOT = _root_tex_gate()
print('root .tex gate: %d files, all accounted for' % _NROOT)

# v4.10: sections/*.tex carries all the prose now.  Without it on this
# list every macro used only in prose looks unreferenced and is DELETED.
CONSUMERS = [f for f in glob.glob("*.tex") + glob.glob("tables/*.tex")
             + glob.glob("sections/*.tex")
             if os.path.basename(f) not in MACFILES]

body = ""
for c in CONSUMERS:
    body += re.sub(r"(?<!\\)%.*", "", open(c, encoding="utf-8").read()) + "\n"

used = set(re.findall(r"\\([A-Za-z]+)", body))

# Generators that READ macros back out of the round files are consumers
# too. Missing this shipped four rows of the v3.99 false-alarm table as
# "--": falsealarm_v399.py looks its inputs up by name with V('Name'), and
# occurrence_v399.py cross-asserts against published values the same way.
# A macro read by a generator is not unreferenced.
# ★ DEFEATED A FOURTH TIME, by a fourth accessor name.  `audit_numbers`
# reads 54 macros through a one-letter helper `M('Name')`, which no
# enumeration of accessor names was ever going to contain, and every one of
# them was deleted as unreferenced -- so the forensic audit crashed on a
# macro that had been retired out from under it.  Enumerating names has now
# failed in this project four times (here, and three times in
# `roundcollide`), so stop enumerating: match ANY short call taking a single
# bare string literal, and keep only those whose literal is actually the
# name of a macro some generator defines.  Over-protection is the safe
# direction -- it keeps a macro that could have gone -- and a literal that
# is not a macro name cannot be matched at all.
# ★ and the widened pattern must take ONE argument and close: `M('Name')`
# is a read, `m('Name', value)` is a WRITE, and a pattern that cannot tell
# them apart protects every macro any generator emits -- which would make
# this pass unable to retire anything, i.e. a check that cannot fail, which
# is the defect family this tree has met sixteen times.
GEN_READ = re.compile(
    r"""\b[A-Za-z_][A-Za-z_0-9]{0,9}\(\s*['"]([A-Za-z]+)['"]\s*\)""", re.X)
# ★ FIFTH SHAPE, v4.11.  A generator that pins a whole TABLE of macros reads
# them from a list of pairs -- `PIN = [('NEB', len(EB_CAT)), ('LedProgenitor',
# len(PROG)), ...]` -- and no call pattern can see that.  `blockledger_v411`'s
# L11, which is the assertion that stops the block ledger becoming a
# thirteenth set of numbers, pins twenty-three macros that way; two of them
# were retired out from under it, so the generator could not be re-run after
# a build.  Same mechanism as `audit_numbers`' `M('Name')` four shapes ago.
# Over-protection is the safe direction: the literal has to be the name of a
# macro some generator actually defines, so a quoted word cannot protect
# anything.
GEN_PAIR = re.compile(r"""\(\s*['"]([A-Za-z]+)['"]\s*,""")
gen_used = set()
for g in sorted(glob.glob("*.py")):
    if os.path.basename(g) == os.path.basename(__file__):
        continue
    src = open(g, encoding="utf-8", errors="ignore").read()
    gen_used |= set(GEN_READ.findall(src))
    gen_used |= set(GEN_PAIR.findall(src))
# only names that really are macros; a string literal that is not one cannot
# protect anything, and this keeps the widened pattern from being a licence
# to keep every quoted word in the tree.
_defined_names = set()
for mf in MACFILES:
    _t = open(mf, encoding="utf-8", errors="ignore").read()
    _defined_names |= set(re.findall(r"\\newcommand\{?\\([A-Za-z]+)\}?\{", _t))
    _defined_names |= set(re.findall(
        r"\\providecommand\{\\([A-Za-z]+)\}\{\}", _t))
gen_used &= _defined_names
if gen_used:
    print("protected because a generator reads them: %d (%s)"
          % (len(gen_used), ", ".join(sorted(gen_used))))
used |= gen_used

# A macro a GATE reads is referenced too.  macrosyn.py declares macro groups
# that must agree and ledger identities that must close; dropping one of them
# as "unreferenced" would silently disarm the check instead of failing it,
# which is exactly what happened to \MaskCrossInNoFlagN the first time this
# ran after the gate was added.
import importlib.util as _ilu

_spec = _ilu.spec_from_file_location('macrosyn_decl',
                                     os.path.join(HERE, 'macrosyn.py'))
_mod = _ilu.module_from_spec(_spec)
try:
    _spec.loader.exec_module(_mod)
except SystemExit:
    pass                      # macrosyn exits after reporting; the table is
                              # already bound by then
gate_used = _mod.declared_macros()
print("protected because macrosyn.py compares them: %d" % len(gate_used))
used |= gate_used

# ★★★★ ROUND 14: `twinmacro.py` IS A GATE TOO, AND ITS DECLARED PAIRS WERE
# NOT PROTECTED.  `twinmacro.SAME` names pairs of macros that are two names for
# one quantity and must agree; dropping one member as "unreferenced" disarms
# the comparison rather than failing it -- and that had already happened:
# `\ScrNBright` was gone from the layer, so the pair that pins it against
# `\CsNDiscFourteen` had been silently skipped.  Found the moment
# `twinmacro.declared()` was given the anti-vacuity clause every other gate
# here has.  The accessor patterns above cannot see these names, because a
# dict key `('A', 'B'): 'reason'` has no identifier before the bracket, so only
# the first of each pair was matched.  Declared explicitly.
_tspec = _ilu.spec_from_file_location('twinmacro_decl',
                                      os.path.join(HERE, 'twinmacro.py'))
_tmod = _ilu.module_from_spec(_tspec)
try:
    _tspec.loader.exec_module(_tmod)
except SystemExit:
    pass                      # twinmacro exits after reporting; the tables
                              # are bound by then
twin_used = {n for pair in _tmod.SAME for n in pair}
twin_used |= {n for pair in _tmod.TWINS_OK for n in pair}
twin_used |= set(_tmod.DENOM) | set(_tmod.DENOM.values())
twin_used |= {n for pair in _tmod.DIFFERENT_OK for n in pair}
twin_used &= _defined_names   # a quoted word that is not a macro protects nothing
print("protected because twinmacro.py compares them: %d" % len(twin_used))
used |= twin_used

# ★ A macro named in the BODY of another macro is referenced.  The macro
# files are excluded from CONSUMERS -- correctly, because a definition
# header is not a use -- but that exclusion threw away their bodies too, and
# a body is a use like any other.  Round 103 retires a superseded quantity by
# aliasing it, `\renewcommand{\SdMed}{\EirpNinetySysMedA}`, so the
# replacement is referenced only from inside a macro file until the prose
# catches up.  Without this, the replacement is deleted as unreferenced and
# the alias expands to an undefined control sequence: the build breaks on the
# one mechanism that was supposed to make a wrong number impossible.
body_used = set()
_DEFHEAD = re.compile(r"\\(?:new|renew|provide)command\s*\{?\\[A-Za-z]+\}?")
for mf in MACFILES:
    txt = re.sub(r"(?<!\\)%.*", "", open(mf, encoding="utf-8").read())
    body_used |= set(re.findall(r"\\([A-Za-z]+)", _DEFHEAD.sub("", txt)))
print("protected because a macro body names them: %d" % len(body_used))
used |= body_used

total = removed = 0
report = []
for mf in MACFILES:
    lines = open(mf, encoding="utf-8").read().splitlines(True)
    keep, drop = [], []
    for ln in lines:
        # ★ Two definition shapes now.  A round file whose names may or may
        # not already exist writes `\providecommand{\X}{}\renewcommand{\X}
        # {...}`, which is the only form correct in both cases; a regex that
        # knows only `\newcommand` cannot see those lines at all, and a
        # retirement pass that silently skips a whole file is worse than one
        # that deletes too much, because nothing reports it.
        m = re.match(r"\\newcommand\{?\\([A-Za-z]+)\}?\{", ln) or re.match(
            r"\\providecommand\{\\([A-Za-z]+)\}\{\}\\renewcommand\{\\\1\}\{",
            ln)
        if m:
            total += 1
            if m.group(1) not in used:
                drop.append(m.group(1))
                continue
        keep.append(ln)
    if drop:
        removed += len(drop)
        report.append((mf, drop))
        with open(mf, "w", encoding="utf-8") as fh:
            fh.write("".join(keep))
            fh.write("%% retired by retire_macros.py (unreferenced): %s\n"
                     % ", ".join(sorted(drop)))

print("macros written %d, retired %d as unreferenced" % (total, removed))
for mf, drop in report:
    print("  %-32s %2d: %s" % (mf, len(drop), ", ".join(sorted(drop))))
