#!/usr/bin/env python3
r"""v3.48 generated numbers, referee cycle 5.

Two quantities that the v3.48 reports showed to be asserted or hand-typed.

Sources
-------
  obscore_category_v348.json   ALMA obscore harvest: scientific_category and
                               science_keyword for all 102 execution blocks of
                               the released catalogue (102 of 102 matched).
  per_target_results_v3.50.csv the released catalogue (431 windows), which maps
                               execution block -> star -> system.

What the referees asked for
---------------------------
  R2-E3  the debris-disc prior is the strongest argument in Sec. 5.3 and was
         the only one still asserted rather than measured.  The proposal
         category and science keyword of every block that produced a searched
         window measure it directly.
  R1-N4  the Galactic-rotation check on HD 48370 printed +23.1 km/s, which does
         not reproduce from the constants of the authors' own reply
         (R0 = 8.15 kpc, Theta0 = 236 km/s give +23.2 at 2 kpc), and printed no
         constant a reader could check it against.  The check is restated as
         the kinematic distance at which a flat curve reaches the measured
         V_LSR, which is a distance rather than a loose coincidence.
"""
import csv, json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)

N = []


def M(name, val):
    N.append('\\newcommand{\\%s}{%s}' % (name, val))


# ==================================================== R2-E3: the debris archive
OB = json.load(open('obscore_category_v348.json'))['blocks']
ROWS = list(csv.DictReader(open('per_target_results_v3.50.csv')))


def uid(eb):
    """A002_X6f1341_X1484 -> uid://A002/X6f1341/X1484 (the obscore asdm_uid)."""
    return 'uid://' + eb.replace('_', '/', 1).replace('_', '/')


blocks_of = {}
system_of = {}
for r in ROWS:
    blocks_of.setdefault(r['star_name'], set()).add(r['eb'])
    system_of[r['star_name']] = r['system_id']

missing = sorted(uid(e) for s in blocks_of for e in blocks_of[s] if uid(e) not in OB)
assert not missing, 'obscore harvest incomplete: %r' % missing[:3]

disk_cat, debris_kw = set(), set()
for star, ebs in blocks_of.items():
    for eb in ebs:
        b = OB[uid(eb)]
        if b['scientific_category'] == 'Disks and planet formation':
            disk_cat.add(star)
        if 'Debris disks' in (b['science_keyword'] or ''):
            debris_kw.add(star)

M('NDiskCatStars', '%d' % len(disk_cat))                 # 79 of 88
M('NDebrisKwStars', '%d' % len(debris_kw))               # 73 of 88
M('NDebrisKwSys', '%d' % len({system_of[s] for s in debris_kw}))   # 67 of 81
M('NObscoreBlocks', '%d' % len({uid(e) for s in blocks_of for e in blocks_of[s]}))

# ================================================ R1-N4: the rotation-curve check
# A flat curve, the IAU-recommended modern constants, and the sight line of the
# HD 48370 window.  V_MEAS is the LSR velocity our own frame chain returns for
# that feature; it is the same number the mask paragraph quotes as an offset
# from CO(2->1) in the LSR frame, so it is defined once here and printed from
# \VlsrHdLsr in both the velocity and the distance.
R0_KPC, THETA0 = 8.15, 236.0          # Reid et al. 2019 / GRAVITY 2019 scale
GAL_L, GAL_B = 214.55, -3.19          # degrees, from the window's own position
V_MEAS = 23.9                         # km/s, LSR, this paper's frame chain


def vlsr(d_kpc):
    """Flat-curve V_LSR for gas at distance d along (l, b)."""
    l, b = math.radians(GAL_L), math.radians(GAL_B)
    dp = d_kpc * math.cos(b)
    R = math.sqrt(R0_KPC ** 2 + dp ** 2 - 2 * R0_KPC * dp * math.cos(l))
    return THETA0 * (R0_KPC / R - 1) * math.sin(l) * math.cos(b)


lo, hi = 0.05, 8.0                    # bisection: V_LSR rises monotonically here
for _ in range(200):
    mid = 0.5 * (lo + hi)
    if vlsr(mid) < V_MEAS:
        lo = mid
    else:
        hi = mid
D_KIN = 0.5 * (lo + hi)
assert abs(vlsr(D_KIN) - V_MEAS) < 1e-6, vlsr(D_KIN)

M('RzeroKpc', '%.2f' % R0_KPC)
M('ThetaZeroKms', '%d' % THETA0)
M('VlsrHdLsr', '%.1f' % V_MEAS)
M('KinDistKpc', '%.2f' % D_KIN)                          # 2.07
M('VlsrTwoKpc', '%.1f' % vlsr(2.0))                      # 23.2, for the record

with open('survey_numbers_round17.tex', 'w') as fh:
    fh.write('% generated by v348_calc.py -- do not edit\n')
    fh.write('\n'.join(N) + '\n')
print('survey_numbers_round17.tex: %d macros' % len(N))
for line in N:
    print('   ', line)
