#!/usr/bin/env python3
"""R2-M3 (v3.98): the ACA control geometry, repaired and verified.

Referee 2 required the ACA windows to be re-extracted on the correct 7 m
geometry rather than compensated for by argument. That has now been done:
278 blocks (265 ACA + the 52 holding the 75 threshold crossings, overlapping
by 39), 739 GB, re-fetched, re-calibrated and re-searched with the frozen
pipeline and a corrected extractor.

The correction, pre-specified before the run in ACA_REEXTRACTION_SPEC.md:
the dish diameter now comes from ANTENNA::DISH_DIAMETER and the maximum
baseline from UVW, so both theta_PB and theta_syn are measured from the data,
and the control annulus starts at

    max(0.14 theta_PB, 2.0 theta_syn)

so that no control position lies on the star's own synthesised main lobe.
ANN_SYN_FACTOR = 2.0 was fixed in advance and has not been adjusted.

This generator reads the corrected products and emits the numbers the paper
quotes. It asserts the pre-registered success criterion so that the claim in
the text cannot outrun the measurement.

Writes survey_numbers_round64.tex.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'survey_numbers_round64.tex')
TRIG = 5.0

W = json.load(open(os.path.join(HERE, 'acareext_v398.json')))
aca = [w for w in W if w['dish'] < 10]
twm = [w for w in W if w['dish'] >= 10]
assert aca, 'no corrected ACA windows found'


def rank(w):
    return (w['ge'] + 1.0) / (w['n'] + 1.0)


def ks(u):
    u = sorted(u)
    n = len(u)
    D = max(max((i + 1) / n - x, x - i / n) for i, x in enumerate(u))
    lam = (math.sqrt(n) + 0.12 + 0.11 / math.sqrt(n)) * D
    p = 2 * sum((-1) ** (k - 1) * math.exp(-2 * k * k * lam * lam)
                for k in range(1, 101))
    return D, max(0.0, min(1.0, p))


u = [rank(w) for w in aca]
D, p = ks(u)
med = sorted(u)[len(u) // 2]

# THE PRE-REGISTERED CRITERION. If this ever fails, the paper must not claim
# the screen was repaired, and the build should stop rather than print it.
assert p > 0.05, (
    'the corrected ACA stellar ranks are still inconsistent with uniformity '
    '(D=%.3f, p=%.4f). The pre-specified success criterion was p > 0.05. Do '
    'not weaken the criterion; report the failure.' % (D, p))

# stage-1 under the corrected screen: reaches the trigger AND outranks every
# control -- the same definition used throughout the paper
s1 = [w for w in aca if w['star'] and w['star'] >= TRIG and w['ge'] == 0]
s1.sort(key=lambda w: -w['star'])

LINES = {'CO(1-0)': 115.271202, 'CO(2-1)': 230.538000, 'CO(3-2)': 345.795990}


def dv_kms(w):
    f = w.get('pkf') or 0.0
    if not f:
        return None
    name, rest = min(LINES.items(), key=lambda kv: abs(f - kv[1]))
    return name, (f - rest) / rest * 299792.458


attributed, unattributed = [], []
for w in s1:
    d = dv_kms(w)
    (attributed if d and abs(d[1]) <= 50.0 else unattributed).append(w)

L = ['%% GENERATED by acafix_v398.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('FixNBlocks', '%d' % len({w['eb'] for w in W}))
m('FixNWin', '%d' % len(W))
m('FixNAcaWin', '%d' % len(aca))
m('FixNTwmWin', '%d' % len(twm))
m('FixKsD', '%.3f' % D)
m('FixKsP', '%.2f' % p)
m('FixMedRank', '%.3f' % med)
m('FixNStageOne', '%d' % len(s1))
m('FixNAttrib', '%d' % len(attributed))
m('FixNUnattrib', '%d' % len(unattributed))
m('FixAnnFactor', '2.0')
m('FixTB', '%.2f' % 0.739)
for tag, w in (('Hd', 'A002_Xc26103_X155a'), ('Bp', 'A002_X6f1341_X1484'),
               ('Vir', 'A002_Xc079b5_X82f')):
    q = [x for x in s1 if x['eb'] == w]
    if q:
        d = dv_kms(q[0])
        m('FixT%s' % tag, '%.1f' % q[0]['star'])
        m('FixDv%s' % tag, '%+.0f' % d[1])
open(OUT, 'w').writelines(L)

print('acafix: %d blocks, %d windows (%d ACA, %d 12 m)'
      % (len({w['eb'] for w in W}), len(W), len(aca), len(twm)))
print('  ACA ranks: D=%.3f p=%.4f median %.3f  -> PASS (criterion p>0.05)'
      % (D, p, med))
print('  stage-1 under the corrected screen: %d (%d line-attributed, '
      '%d unattributed)' % (len(s1), len(attributed), len(unattributed)))
for w in s1:
    d = dv_kms(w)
    print('     %-22s T*=%6.2f  %s %+.1f km/s'
          % (w['eb'], w['star'], d[0] if d else '--', d[1] if d else 0))
