#!/usr/bin/env python3
"""R2-7 (v3.98): quantify what is gained by working in the visibility domain.

Referee 2 objected that the recommendation to "use the visibilities" is
made repeatedly but never costed against what the image-plane statistic
delivers.  This generator measures the gain on the survey's own data rather
than arguing it.

The measurement is available because both statistics were computed for the
same 13 stage-1 windows.  In the image plane those 13 are
*indistinguishable*: every one of them has zero of the 512 control
positions at or above the star, so every one sits at rank 1 of 513, which
is the floor of what the ensemble can express.  The statistic has no
remaining dynamic range with which to separate them.  In the visibility
domain the same 13 split cleanly: the windows carrying real emission at the
stellar position reach 6-10 sigma on the real part, while every
unattributed window is consistent with nothing at the star at below 1
sigma.

So the gain is not a marginal improvement in sensitivity.  It is the
difference between a statistic that saturates and one that does not.

Writes survey_numbers_round60.tex.
"""
import csv
import math
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'survey_numbers_round60.tex')

CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.98.csv'))))
flagged = [r for r in CAT if r['stage1_flag'] == 'True']

NCTRL = 512
floor_p = 1.0 / (NCTRL + 1)
# one-sided Gaussian equivalent of the rank floor
def z_of(p):
    # inverse survival function without scipy: bisection on erfc
    lo, hi = 0.0, 40.0
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if 0.5 * math.erfc(mid / math.sqrt(2.0)) > p:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)

z_floor = z_of(floor_p)

# every flagged window must be AT the floor for the saturation claim to hold
nge = [int(r['n_ctrl_ge_star']) for r in flagged]
assert set(nge) == {0}, (
    'not every stage-1 window is at the rank floor (n_ctrl_ge_star values '
    '%s), so the image-plane statistic is not saturated and the gain '
    'argument below does not hold as stated' % sorted(set(nge)))

# read the visibility fit results back out of the generated table, so this
# generator cannot drift from what the paper prints
tab = open(os.path.join(HERE, 'tab_visfit_v385.tex')).read()
# R2 minor 1: select on the VERDICT, not on a numeric cut. Cutting at
# Re/sigma >= 5 swept in HD 48370 at +5.93, which the same table classes as
# "displaced: phase inconsistent", and so quoted the positive-control range
# as 5.9-9.5 sigma when the beta Pic windows run 6.1-9.5.
re_vals, at_star, null_like = [], [], []
for line in tab.splitlines():
    if '&' not in line or line.lstrip().startswith('%'):
        continue
    cells = [c.strip() for c in line.split('&')]
    if len(cells) < 7:
        continue
    mm = re.match(r'\$?([-+]?[\d.]+)\$?$', cells[3].replace('\\', ''))
    if not mm:
        continue
    v = float(mm.group(1))
    verdict = cells[6].replace('\\\\', '').strip().lower()
    name = cells[0].lower()
    re_vals.append(v)
    if verdict.startswith('source at the stellar position'):
        at_star.append(v)
    # the null set is the UNATTRIBUTED events only: a beta Pic window that
    # happens to read "nothing at the star" belongs to the positive-control
    # population and would inflate this bound
    elif ('pic' not in name and '48370' not in name):
        null_like.append(abs(v))
assert len(re_vals) >= 13, 'parsed only %d visibility rows' % len(re_vals)
assert at_star and null_like, 'visibility rows did not separate by verdict'
assert all(v >= 6.0 for v in at_star), (
    'a window verdicted "source at the stellar position" has Re/sigma %.2f, '
    'below the 6 sigma the text quotes' % min(at_star))

vis_max = max(re_vals)
gain = vis_max / z_floor
sep = min(at_star) - max(null_like)

with open(OUT, 'w') as f:
    f.write('%% GENERATED by visgain_v398.py -- do not hand-edit.\n')
    f.write('\\newcommand{\\VgNFlag}{%d}\n' % len(flagged))
    f.write('\\newcommand{\\VgRankFloorZ}{%.1f}\n' % z_floor)
    f.write('\\newcommand{\\VgVisMax}{%.1f}\n' % vis_max)
    f.write('\\newcommand{\\VgGain}{%.1f}\n' % gain)
    f.write('\\newcommand{\\VgAtStarLo}{%.1f}\n' % min(at_star))
    f.write('\\newcommand{\\VgAtStarHi}{%.1f}\n' % max(at_star))
    f.write('\\newcommand{\\VgNullMax}{%.2f}\n' % max(null_like))
    f.write('\\newcommand{\\VgSep}{%.1f}\n' % sep)

print('visgain: all %d flagged at the rank floor (z=%.2f); visibility '
      'reaches %.1f sigma, gain x%.1f; at-star %.1f-%.1f vs null <= %.2f, '
      'separation %.1f sigma'
      % (len(flagged), z_floor, vis_max, gain, min(at_star), max(at_star),
         max(null_like), sep))
