#!/usr/bin/env python3
"""R2-num 22: the drift-trial distribution, and residual smear, BY CLASS.

The manuscript quoted a median of four drift trials per window. That is a
Class B number and it misrepresents the carrier experiment: Class B windows
are coarse enough that almost no de-drifting is needed, and they outnumber
Class A three to one, so the pooled median is theirs. The Class A windows
that constitute the principal experiment search a median of eighty-one
trial drift rates, with a quarter of them above a hundred and thirty and a
maximum approaching two thousand.

Residual smear separates the same way, and for the same reason: a coarse
channel cannot be smeared by a drift small enough to matter, so every
Class B window has eta_smear = 1 exactly, and the entire residual-smear
loss in the survey lives in Class A.

Reporting one pooled median for both hides the only stratum in which
either quantity is non-trivial.

Writes survey_numbers_round70.tex.
"""
import csv
import os
import statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
ROWS = list(csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.99.csv'))))
OUT = os.path.join(HERE, 'survey_numbers_round70.tex')

L = ['%% GENERATED by drifttrials_v400.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


def F(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def block(tag, rows):
    n = [int(float(r['n_drift_trials'])) for r in rows if r['n_drift_trials']]
    q = st.quantiles(n, n=4)
    m('Trials%sMed' % tag, '%d' % round(st.median(n)))
    m('Trials%sQLo' % tag, '%d' % round(q[0]))
    m('Trials%sQHi' % tag, '%d' % round(q[2]))
    m('Trials%sMin' % tag, '%d' % min(n))
    m('Trials%sMax' % tag, '{:,}'.format(max(n)).replace(',', '\\,'))
    sm = [F(r['eta_smear']) for r in rows if F(r['eta_smear']) is not None]
    m('Smear%sN' % tag, '%d' % len(sm))
    m('Smear%sMin' % tag, '%.3f' % min(sm))
    m('Smear%sWorstPct' % tag, '%.0f' % (100 * (1 - min(sm))))
    m('Smear%sNLossy' % tag, '%d' % sum(1 for v in sm if v < 0.99))
    return n, sm


FINE = [r for r in ROWS if r['resolution_class'] == 'fine']
COARSE = [r for r in ROWS if r['resolution_class'] != 'fine']
nA, smA = block('A', FINE)
nB, smB = block('B', COARSE)
block('All', ROWS)

# The claim the text needs to be able to make: all of the residual smear is
# in Class A, because a coarse channel cannot be smeared enough to matter.
assert min(smB) == 1.0, (
    'Class B carries residual smear (min eta_smear = %.4f); the text says it '
    'does not' % min(smB))
m('SmearBExact', '1')

print('drifttrials_v400: Class A trials median %d (quartiles %d-%d, max %d); '
      'Class B median %d. Residual smear: Class A worst %.3f (%d windows below '
      '0.99), Class B exactly 1 in all %d.'
      % (st.median(nA), st.quantiles(nA, n=4)[0], st.quantiles(nA, n=4)[2],
         max(nA), st.median(nB), min(smA),
         sum(1 for v in smA if v < 0.99), len(smB)))

open(OUT, 'w').writelines(L)
