#!/usr/bin/env python3
r"""Round 79 (R2-m26): run the known-answer test vectors and report the result.

S6.5 says the release ships known-answer vectors "so a reader who did not
write this pipeline can check its stacking and normalisation against
arithmetic", and then does not say what happens when they are run.  The
referee asks for the result.  This runs them.

The stack is re-implemented here from Eq. (3) in half a page, deliberately
importing nothing from the search or the injection code, which is the whole
point of the exercise: the vectors are Gaussian noise plus a closed-form
drifting sinusoid, so the answer is arithmetic and a disagreement means the
convention is wrong somewhere.

Reports, per case, the recovered T at the best (channel, drift) cell, and
checks each against the expectation the manifest states:

  null                 no carrier; T is the extreme of NCHAN x NDRIFT
                       standard normals, so it must be a few, not ~5
  stationary_5sigma    T ~ 5 at zero drift
  drifting_5sigma      T ~ 5 ONLY at the matching drift trial, and stacking
                       at zero drift must lose about sqrt(NINT/4)
  drifting_offgrid     reduced relative to the on-grid case: the grid-loss
                       term the completeness curve has to carry
"""
import hashlib
import json
import os

import numpy as np

os.chdir(os.path.dirname(os.path.abspath(__file__)))
TVDIR = 'testvectors_v399'
MAN = json.load(open(os.path.join(TVDIR, 'manifest.json')))
OUT = []


def M(n, v):
    OUT.append(r'\newcommand{\%s}{%s}' % (n, v))


def stack(spec, chanw_hz, dt_s, drift_hz_s):
    """Eq. (3) at one drift rate, unit noise: the inverse-variance-weighted
    de-drifted stack, normalised by the noise of the stacked spectrum."""
    nint, nchan = spec.shape
    acc = np.zeros(nchan)
    for i in range(nint):
        sh = int(round(drift_hz_s * (i * dt_s) / chanw_hz))
        acc += np.roll(spec[i], -sh)
    return acc / np.sqrt(nint)


RES = {}
for c in MAN:
    path = os.path.join(TVDIR, c['file'])
    got = hashlib.sha256(open(path, 'rb').read()).hexdigest()
    assert got == c['sha256'], 'checksum changed for %s' % c['file']
    z = np.load(path)
    spec = z['spectra'].astype(float)
    chanw, dt = float(z['chanw_hz']), float(z['dt_s'])
    nint, nchan = spec.shape
    # the same grid shape the search uses: uniform in drift over the track
    dmax = chanw / (nint * dt) * 8.0
    grid = np.linspace(-dmax, dmax, 65)
    gmax = max(stack(spec, chanw, dt, d).max() for d in grid)
    # the value AT the injected cell, which is where the arithmetic is
    # predictable: it is the injected amplitude plus one N(0,1) draw. The
    # grid maximum is not, because it is the extreme of NCHAN x NDRIFT
    # cells and carries the trials inflation the null case measures.
    cell = float(stack(spec, chanw, dt, c['drift_hz_s'])[nchan // 2])
    RES[c['name']] = dict(cell=cell, gmax=gmax, amp=c['amp'],
                          zero=float(stack(spec, chanw, dt, 0.0)[nchan // 2]),
                          nint=nint, nchan=nchan, ngrid=len(grid))

# The expectations, in the order the manifest states them. The injected-cell
# value carries one unit-variance noise draw, so it is checked to +-3 and not
# to a fraction of a per cent; the incisive checks are the losses, which are
# structural and do not depend on the realisation.
NINT = RES['null']['nint']
_ok, _why = [], []
_why.append('null does not reach the trigger anywhere on the grid')
_ok.append(RES['null']['gmax'] < 5.0)
_why.append('a centred stationary carrier returns its injected amplitude')
_ok.append(abs(RES['stationary_5sigma']['cell'] - 5.0) < 3.0)
_why.append('a drifting carrier returns it only on its own drift trial')
_ok.append(abs(RES['drifting_5sigma']['cell'] - 5.0) < 3.0
           and RES['drifting_5sigma']['zero']
           < RES['drifting_5sigma']['cell'] / 2.0)
_why.append('an off-grid drift is recovered with a loss')
_ok.append(RES['drifting_offgrid']['cell'] < RES['drifting_5sigma']['cell'])
assert all(_ok), 'known-answer vectors fail: %s' % [
    w for w, o in zip(_why, _ok) if not o]

M('KatNCases', '%d' % len(MAN))
M('KatNPass', '%d' % sum(_ok))
M('KatNull', '%.1f' % RES['null']['gmax'])
M('KatStat', '%.1f' % RES['stationary_5sigma']['cell'])
M('KatDrift', '%.1f' % RES['drifting_5sigma']['cell'])
M('KatDriftZero', '%.1f' % RES['drifting_5sigma']['zero'])
M('KatOffGrid', '%.1f' % RES['drifting_offgrid']['cell'])
M('KatOffGridLoss', '%.0f' % (100 * (1 - RES['drifting_offgrid']['cell']
                                     / RES['drifting_5sigma']['cell'])))

with open('survey_numbers_round79.tex', 'w') as fh:
    fh.write('%% GENERATED by katcheck_v401.py -- do not hand-edit.\n')
    fh.write('\n'.join(OUT) + '\n')

for k, v in RES.items():
    print('%-20s injected cell T=%5.2f (amp %3.1f); grid max %5.2f; '
          'at zero drift %5.2f' % (k, v['cell'], v['amp'], v['gmax'], v['zero']))
for w, o in zip(_why, _ok):
    print('  %s %s' % ('PASS' if o else 'FAIL', w))
print('%d macros -> survey_numbers_round79.tex' % len(OUT))
