#!/usr/bin/env python3
"""R1-8 (v3.99): separate repeat execution blocks from temporally
independent confirmation epochs.

Referee 1's point is exact: two blocks obtained on the same night do not
provide the confirmation power of two separated by months. The paper had
been quoting the number of systems with more than one searched block as
though it were the number with a confirmation opportunity. It is not.

An "independent epoch" is defined here as a separation of more than one
day between a system's blocks. The threshold is stated rather than tuned:
one day is the point beyond which ALMA scheduling no longer places
observations in the same execution session.
"""
import collections
import csv
import json
import os

import epochs_r14 as _ep        # the ONE determination of a block's epoch

HERE = os.path.dirname(os.path.abspath(__file__))
CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.99.csv'))))
OUT = os.path.join(HERE, 'survey_numbers_round56.tex')
OUTJ = os.path.join(HERE, 'epochsplit_v399.json')
SEP = _ep.SEP

# ★★★★ ROUND 14: THE SEPARATIONS ARE MEASURED, NOT READ OUT OF
# `epochs_v386.json`.  That file resolved every block the archive does not
# index by `asdm_uid` through its member OUS and got back the earliest block in
# the unit, so 252 of its 404 stamps are shared with another block and 90 of
# the 141 that can be checked against a surviving measurement set are wrong,
# the worst by 246 days.  A system whose repeat blocks sit in one scheduling
# unit therefore had every gap equal to zero and was classified "all within one
# day".  The split this file publishes is the paper's statement of its own
# confirmation scope, and it was understated in half the sentences that quote
# it: restricted to the carrier experiment, 18 single-block + 3 same-day = 21
# of the 60 Class A systems have no independently separated epoch and 39 do,
# against a published 18 + 10 = 28 and 32.
#
# ★ The classification is one-sided and must be read as such: `epochs_r14`
# can show two blocks to be separated and can never show them simultaneous, so
# `sameday` is an upper bound on itself and `indep` a lower bound.
#
# ★★ AND THE JSON IS NOW WRITTEN HERE.  `epochsplit_v399.json` existed in this
# tree as a FROZEN FILE THIS GENERATOR HAD NEVER WRITTEN -- dated months before
# the catalogue it describes -- and two consumers read it as though it were
# this file's output: `make_fig_classa_sens.py`, whose panel (b) therefore drew
# the 82-system population beside a panel (a) holding 60 Class A points, and
# `scope_r14.py`.  That is how both referees came to quote "40 of the 60 Class A
# systems" back at us: it is what our own figure said.
mjd = _ep.EPOCHS
bysys = collections.defaultdict(set)
for r in CAT:
    bysys[r['system_id']].add(r['eb'])

# R1-7: the referee asks for the same split restricted to CLASS A systems,
# because recurrence is what a carrier claim would need and only the
# fine-channel windows constitute the carrier experiment. The pooled
# figure is dominated by systems that have only coarse coverage.
bysysA = collections.defaultdict(set)
for r in CAT:
    if r['resolution_class'] == 'fine':
        bysysA[r['system_id']].add(r['eb'])


split = _ep.split          # one classifier, in the module that owns the epochs

c = split(bysys)
tot = sum(c.values())
indep = c['days'] + c['months'] + c['years']
multi = tot - c['one']
assert c['one'] + c['sameday'] + indep == tot, 'epoch split must close'

L = ['%% GENERATED by epochsplit_v399.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('EpTot', '%d' % tot)
m('EpOne', '%d' % c['one'])
m('EpSameDay', '%d' % c['sameday'])
m('EpMulti', '%d' % multi)
m('EpIndep', '%d' % indep)
m('EpIndepPct', '%.0f' % (100.0 * indep / tot))
m('EpDays', '%d' % c['days'])
m('EpMonths', '%d' % c['months'])
m('EpYears', '%d' % c['years'])
m('EpSep', '%.0f' % SEP)
# R1-5: the systems that cannot provide independent temporal confirmation at
# all -- observed once, or with every block inside one day.  Asserted against
# the total so this and EpIndep cannot drift apart.
assert c['one'] + c['sameday'] + indep == tot, (
    'temporal partition does not close: %d one + %d same-day + %d '
    'independent != %d systems' % (c['one'], c['sameday'], indep, tot))
m('EpNoConfirm', '%d' % (c['one'] + c['sameday']))
open(OUT, 'w').writelines(L)
print('%s: %d macros' % (os.path.basename(OUT), len(L) - 1))
print('  systems %d: one block %d | multi-block %d, of which %d have ALL '
      'blocks within %.0f d' % (tot, c['one'], multi, c['sameday'], SEP))
print('  temporally independent epochs: %d (%.0f per cent) -- days %d, '
      'months %d, years %d' % (indep, 100.0 * indep / tot, c['days'],
                               c['months'], c['years']))

# ---- the Class A temporal-coverage table (R1-7)
_cA = split(bysysA)
_totA = sum(_cA.values())
_indepA = _cA['days'] + _cA['months'] + _cA['years']
assert _cA['one'] + _cA['sameday'] + _indepA == _totA, 'Class A split must close'
with open(os.path.join(HERE, 'tab_epochclassa_v400.tex'), 'w') as fh:
    fh.write('%% GENERATED by epochsplit_v399.py -- do not hand-edit.\n')
    fh.write('\\begin{tabular}{@{}lrr@{}}\n\\toprule\n')
    fh.write('Longest separation between searched epochs & Systems & '
             'Per cent \\\\\n\\midrule\n')
    for lab, key in (('Single epoch ($N_{\\rm epoch}=1$)', 'one'),
                     ('Repeats within $<1$\\,d', 'sameday'),
                     ('1--30\\,d', 'days'),
                     ('30--365\\,d', 'months'),
                     ('$>365$\\,d', 'years')):
        fh.write('%s & %d & %.0f \\\\\n'
                 % (lab, _cA[key], 100.0 * _cA[key] / _totA))
    fh.write('\\midrule\n')
    fh.write('\\emph{Able to test recurrence at all} & %d & %.0f \\\\\n'
             % (_indepA, 100.0 * _indepA / _totA))
    fh.write('\\bottomrule\n\\end{tabular}\n')
with open(OUT, 'a') as fh:
    fh.write('\\newcommand{\\EpATot}{%d}\n' % _totA)
    fh.write('\\newcommand{\\EpAOne}{%d}\n' % _cA['one'])
    fh.write('\\newcommand{\\EpASameDay}{%d}\n' % _cA['sameday'])
    fh.write('\\newcommand{\\EpAIndep}{%d}\n' % _indepA)
    fh.write('\\newcommand{\\EpAIndepPct}{%.0f}\n'
             % (100.0 * _indepA / _totA))
    fh.write('\\newcommand{\\EpAYears}{%d}\n' % _cA['years'])
print('Class A epochs: %d systems, %d single, %d same-day, %d able to test '
      'recurrence (%d over a year)'
      % (_totA, _cA['one'], _cA['sameday'], _indepA, _cA['years']))

# ---- the record both the figure and round 410 read, WRITTEN rather than frozen
_KEYS = ('one', 'sameday', 'days', 'months', 'years')
assert sum(c[k] for k in _KEYS) == tot, 'all-system split must close'
assert sum(_cA[k] for k in _KEYS) == _totA, 'Class A split must close'
# ★ The Class A population must BE the Class A population: 60 systems, the
# number panel (a) of Fig. 5 plots and the number \NSysClassA publishes.  The
# absence of this one identity is what let two panels of one figure count two
# different populations for three versions.
assert _totA < tot, ('the Class A restriction must restrict: %d of %d'
                     % (_totA, tot))
with open(OUTJ, 'w', encoding='utf-8') as fh:
    json.dump({'total': tot,
               'one': c['one'], 'same_day': c['sameday'],
               'days': c['days'], 'months': c['months'],
               'years': c['years'],
               'independent': indep,
               'sep_days': SEP,
               'epoch_source': 'epochs_r14: measurement set where one '
                               'survives, the calibrated barycentric witness '
                               'otherwise, the stored stamp last and never '
                               'where two blocks share it',
               'one_sided': 'the witness can show separation and never '
                            'simultaneity, so same_day is an upper bound and '
                            'independent a lower bound',
               'class_a': {'total': _totA,
                           'one': _cA['one'], 'sameday': _cA['sameday'],
                           'same_day': _cA['sameday'],
                           'days': _cA['days'], 'months': _cA['months'],
                           'years': _cA['years'],
                           'independent': _indepA,
                           'no_confirm': _cA['one'] + _cA['sameday']}},
              fh, indent=1, sort_keys=True)
print('wrote %s (all %d systems and the %d Class A ones)'
      % (os.path.basename(OUTJ), tot, _totA))
