#!/usr/bin/env python3
"""Rank-uniformity tests, recomputed on the released catalogue.

The manuscript carried these from `frozen_macros/survey_numbers_round6.tex`,
a round-6 freeze over a 431-window catalogue, and stated that excluding the
fine windows with a stellar crossing "restores uniformity" at p = 0.39.

On the 1655-window release that is no longer true: excluding them leaves
p = 0.0015. The claim was a property of the old sample. Recompute it here,
per class and with the crossings removed, so the manuscript states the
departure it actually has.

This makes the paper's caution stronger, not weaker: the spatial screen was
already described as a prioritisation rather than a test of the null.
"""
import csv, os
import numpy as np
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
R = list(csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.90.csv'))))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))


def ks(rows):
    x = np.array([float(r['p_rank_addone']) for r in rows if r['p_rank_addone']])
    d, p = stats.kstest(x, 'uniform')
    return len(x), float(d), float(p)


def pfmt(p):
    """A p-value a reader can quote: never '0.00'.

    The macro carries its own relation, because a body beginning with `<`
    after a typed `=` renders as `p =< 10^{-4}`. Callers write
    `$p\\KsFineP$` with no relation of their own.
    """
    if p < 1e-4:
        return r'<10^{-4}'
    if p < 0.001:
        return r'<10^{-3}'
    return '=%.3f' % p


A = [r for r in R if r['search_class'] == 'A']
B = [r for r in R if r['search_class'] == 'B']
AC = [r for r in A if r['crossing'] == 'True']
ANC = [r for r in A if r['crossing'] != 'True']

for tag, rows in (('All', R), ('Fine', A), ('Coarse', B), ('FineNoCross', ANC)):
    n, d, p = ks(rows)
    M('Ks%sN' % tag, '%d' % n)
    M('Ks%sD' % tag, '%.3f' % d)
    M('Ks%sP' % tag, pfmt(p))
M('KsFineCrossN', '%d' % len(AC))

# Does removing the crossings help at all? Report the change, not a verdict.
_, dA, pA = ks(A)
_, dN, pN = ks(ANC)
M('KsFineDropD', '%.3f' % (dA - dN))
M('KsFineStillDep', 'yes' if pN < 0.05 else 'no')

# Median rank per class: the direction of the displacement.
for tag, rows in (('Fine', A), ('Coarse', B)):
    x = sorted(float(r['p_rank_addone']) for r in rows if r['p_rank_addone'])
    M('MedRank%s' % tag, '%.3f' % x[len(x) // 2])

open(os.path.join(HERE, 'survey_numbers_round41.tex'), 'w').write(
    '%% GENERATED by ksrank_v385.py -- do not hand-edit.\n' + '\n'.join(OUT) + '\n')

for tag, rows in (('all', R), ('fine', A), ('coarse', B),
                  ('fine, no crossing', ANC)):
    n, d, p = ks(rows)
    print('  %-18s n=%5d  D=%.3f  p=%s' % (tag, n, d, pfmt(p)))
print('  excluded fine crossings: %d' % len(AC))
print('  removing them changes D by %.3f and leaves p %s 0.05'
      % (dA - dN, '<' if pN < 0.05 else '>'))
print('macros -> survey_numbers_round41.tex (%d)' % len(OUT))
