#!/usr/bin/env python3
"""Macros and figure for the injection campaigns added in v3.58.

Two experiments, both run on the pipeline host against real retained spectra:
  (a) a stratified Class-A injection-recovery campaign over 28 configurations,
      which converts the previously ASSUMED 0.5-2x completeness transfer
      bracket into a measured dispersion;
  (b) an injection through the instrument's spectral-response kernel at a
      range of sub-channel positions, which turns the previously ANALYTIC
      x2.00-2.67 correction into a measured one.
"""
import csv, collections, os, math
import numpy as np
import matplotlib
matplotlib.use('Agg')
matplotlib.rcParams['pdf.fonttype'] = 42
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

R = list(csv.DictReader(open(os.path.join(HERE, 'stratified_inject_trials_v3.58.csv'))))
H = list(csv.DictReader(open(os.path.join(HERE, 'hanning_response_trials_v3.58.csv'))))
AMPS = sorted({float(r['amp_sigma']) for r in R})


def curve(rows):
    return {a: float(np.mean([r['detected'] == 'True' for r in rows
                              if float(r['amp_sigma']) == a])) for a in AMPS}


def pX(c, x):
    xs = sorted(c); ys = [c[a] for a in xs]
    for i in range(1, len(xs)):
        if ys[i - 1] < x <= ys[i]:
            f = (x - ys[i - 1]) / (ys[i] - ys[i - 1]) if ys[i] != ys[i - 1] else 0.0
            return xs[i - 1] + f * (xs[i] - xs[i - 1])
    return float('nan') if ys[-1] < x else xs[0]


pool = curve(R)
wins = sorted(set(r['window'] for r in R))
M('StratTrials', '%d' % len(R))
M('StratWindows', '%d' % len(wins))
M('StratStars', '%d' % len(set(r['target'] for r in R)))
_bands = sorted({int(r['band']) for r in R})
M('StratBands', '%d' % len(_bands))
M('StratBandLo', '%d' % min(_bands)); M('StratBandHi', '%d' % max(_bands))
M('StratChanLo', '%.1f' % (min(float(r['chanw_Hz']) for r in R) / 1e3))
M('StratChanHi', '%.0f' % (max(float(r['chanw_Hz']) for r in R) / 1e3))
M('StratIntLo', '%d' % min(int(r['n_int']) for r in R))
M('StratIntHi', '%d' % max(int(r['n_int']) for r in R))
M('StratDriftLo', '%d' % min(int(r['n_drift']) for r in R))
M('StratDriftHi', '%d' % max(int(r['n_drift']) for r in R))
M('StratPFifty', '%.1f' % pX(pool, 0.5))
M('StratPNinety', '%.1f' % pX(pool, 0.9))
for a in (4, 5, 6, 8, 10):
    M('StratRec%s' % {4: 'Four', 5: 'Five', 6: 'Six', 8: 'Eight', 10: 'Ten'}[a],
      '%.0f' % (100 * pool[float(a)]))

p50 = np.array([pX(curve([r for r in R if r['window'] == w]), 0.5) for w in wins])
p90 = np.array([pX(curve([r for r in R if r['window'] == w]), 0.9) for w in wins])
p50 = p50[np.isfinite(p50)]; p90 = p90[np.isfinite(p90)]
M('StratPFiftyLo', '%.1f' % p50.min()); M('StratPFiftyHi', '%.1f' % p50.max())
M('StratPNinetyLo', '%.1f' % p90.min()); M('StratPNinetyHi', '%.1f' % p90.max())
M('StratTransferLo', '%.2f' % (p50 / np.median(p50)).min())
M('StratTransferHi', '%.2f' % (p50 / np.median(p50)).max())
M('StratTransferNineLo', '%.2f' % (p90 / np.median(p90)).min())
M('StratTransferNineHi', '%.2f' % (p90 / np.median(p90)).max())
# per-axis stability
for key, tag in (('band', 'Band'), ('array', 'Array')):
    g = collections.defaultdict(list)
    for r in R:
        g[r[key]].append(r)
    v = [pX(curve(g[k]), 0.5) for k in g]
    v = [x for x in v if np.isfinite(x)]
    M('StratPFifty%sLo' % tag, '%.1f' % min(v))
    M('StratPFifty%sHi' % tag, '%.1f' % max(v))

f = np.array([float(r['factor']) for r in H])
M('HanMeasTrials', '%d' % len(H))
M('HanMeasWin', '%d' % len(set(r['window'] for r in H)))
M('HanMeasMed', '%.2f' % np.median(f))
M('HanMeasLo', '%.2f' % f.min())
M('HanMeasHi', '%.2f' % f.max())
phis = sorted({float(r['phi']) for r in H})
M('HanMeasCentred', '%.2f' % np.mean([float(r['factor']) for r in H if float(r['phi']) == 0.0]))
M('HanMeasEdge', '%.2f' % np.mean([float(r['factor']) for r in H if float(r['phi']) == max(phis)]))
dev = []
for phi in phis:
    meas = np.mean([float(r['factor']) for r in H if float(r['phi']) == phi])
    ana = 1.0 / np.max(np.convolve(np.array([0.0, 0.0, 1 - phi, phi, 0.0]),
                                   np.array([0.25, 0.5, 0.25]), mode='same'))
    dev.append(abs(meas - ana) / ana)
M('HanMeasDevPct', '%.1f' % (100 * max(dev)))

open(os.path.join(HERE, 'survey_numbers_round23.tex'), 'w').write(
    '%% Generated by v358_inject.py -- do not edit by hand.\n' + '\n'.join(OUT) + '\n')
print('\n'.join(OUT))

# ------------------------------------------------------------------ figure
fig, (ax, ax2) = plt.subplots(1, 2, figsize=(6.8, 2.0))
for w in wins:
    c = curve([r for r in R if r['window'] == w])
    ax.plot(sorted(c), [c[a] for a in sorted(c)], color='0.75', lw=0.5, zorder=1)
ax.plot(sorted(pool), [pool[a] for a in sorted(pool)], color='#1f4e9c', lw=1.8,
        marker='o', ms=2.6, zorder=3, label='pooled, %d trials' % len(R))
ax.axhline(0.5, color='0.4', lw=0.6, ls=':'); ax.axhline(0.9, color='0.4', lw=0.6, ls=':')
ax.set_xlabel(r'injected carrier significance ($\sigma$)', fontsize=7)
ax.set_ylabel('recovered fraction', fontsize=7)
ax.tick_params(labelsize=6.4)
ax.set_xlim(3, 12); ax.set_ylim(0, 1.02)
ax.legend(fontsize=6, loc='lower right', frameon=True, framealpha=0.9)
# second panel: the drift-fraction axis, on all configurations at once
dmax = {}
for r in R:
    nd = int(r['n_drift'])
    if nd > 1:
        dd = float(r['chanw_Hz']) / float(r['span_s']) / 2.0
        dmax[r['window']] = dd * (nd - 1) / 2.0
edges = np.linspace(0, 1, 7)
for A, col in ((5.0, '#c2432b'), (8.0, '#1f4e9c')):
    xs, ys = [], []
    for i in range(len(edges) - 1):
        sel = [r for r in R if float(r['amp_sigma']) == A
               and r['window'] in dmax and dmax[r['window']] > 0
               and edges[i] <= abs(float(r['inj_drift_Hz_s'])) / dmax[r['window']] < edges[i + 1]]
        if len(sel) >= 12:
            xs.append(0.5 * (edges[i] + edges[i + 1]))
            ys.append(np.mean([x['detected'] == 'True' for x in sel]))
    ax2.plot(xs, ys, marker='o', ms=2.6, lw=1.4, color=col,
             label=r'$%d\sigma$' % int(A))
ax2.set_xlabel(r'drift fraction $f_{\rm drift}$ of the searched ceiling', fontsize=7)
ax2.set_ylabel('recovered fraction', fontsize=7)
ax2.tick_params(labelsize=6.4)
ax2.set_xlim(0, 1); ax2.set_ylim(0, 1.02)
ax2.legend(fontsize=6, loc='lower right', frameon=True, framealpha=0.9)
fig.tight_layout(pad=0.25)
fig.savefig(os.path.join(HERE, 'figures', 'stratified_completeness.pdf'))
print('wrote figures/stratified_completeness.pdf')

# ---------------------------------------------------------------- visibilities
import json as _json
VF = _json.load(open(os.path.join(HERE, 'visfit_cp72_v358.json')))
OUT2 = []
def M2(n, v): OUT2.append(r'\newcommand{\%s}{%s}' % (n, v))
M2('VisNVis', '{:,}'.format(VF['n_visibilities']).replace(',', r'\,'))
M2('VisSigmaMJy', '%.2f' % (VF['sigma_Jy'] * 1e3))
M2('VisStarMJy', '%.1f' % (VF['flagged']['A_star_Jy'] * 1e3))
M2('VisStarSnr', '%.1f' % VF['flagged']['A_star_snr'])
M2('VisStarImagSnr', '%.2f' % abs(VF['flagged']['A_star_imag_snr']))
M2('VisDchi', '%.0f' % VF['flagged']['dchi2_star_vs_noise'])
M2('VisContMJy', '%.1f' % (VF['continuum_at_star_Jy'] * 1e3))
_c = VF['off_frequency_controls']
M2('VisCtrlN', '%d' % len(_c))
M2('VisCtrlMax', '%.1f' % max(abs(x['A_star_snr']) for x in _c))
M2('VisCtrlGridLo', '%.1f' % min(x['A_best_snr'] for x in _c))
M2('VisCtrlGridHi', '%.1f' % max(x['A_best_snr'] for x in _c))
M2('VisGridN', '%d' % (31 * 31))
open(os.path.join(HERE, 'survey_numbers_round24.tex'), 'w').write(
    '%% Generated by v358_inject.py -- do not edit by hand.\n' + '\n'.join(OUT2) + '\n')
print('\n'.join(OUT2))

# ------------------------------------------------- running block accounting
# The frozen analysis searched NEB blocks; the epoch-extension campaign has
# searched HOBlocks more since. Both numbers are quoted in the paper, so the
# running total is derived here rather than written by hand.
def _texval(macro):
    import glob as _g
    for fn in _g.glob(os.path.join(HERE, 'survey_numbers*.tex')):
        m = re.search(r'\\newcommand\{\\%s\}\{(.*?)\}\s*$' % macro, open(fn).read(), re.M)
        if m:
            return m.group(1)
    raise SystemExit('%s not found' % macro)

import re
_neb = int(_texval('NEB')); _prog = int(_texval('NProgenitorEBTotal'))
_ho = int(_texval('HOBlocks'))
OUT3 = ['%% Generated by v358_inject.py -- do not edit by hand.',
        r'\newcommand{\EbSearchedNow}{%d}' % (_neb + _ho),
        r'\newcommand{\EbRemainNow}{%d}' % (_prog - _neb - _ho),
        r'\newcommand{\PctEbSearchedNow}{%.0f}' % (100.0 * (_neb + _ho) / _prog)]
open(os.path.join(HERE, 'survey_numbers_round25.tex'), 'w').write('\n'.join(OUT3) + '\n')
print('\n'.join(OUT3))

# ------------------------------------------------- Bands 9 and 10, omitted
HB = _json.load(open(os.path.join(HERE, 'highband_v359.json')))
OUT4 = ['%% Generated by v358_inject.py -- do not edit by hand.',
        r'\newcommand{\HiBandWin}{%d}' % HB['n_windows'],
        r'\newcommand{\HiBandStars}{%d}' % HB['n_stars'],
        r'\newcommand{\HiBandBlocks}{%d}' % HB['n_blocks'],
        r'\newcommand{\HiBandLo}{%.0f}' % HB['freq_lo_GHz'],
        r'\newcommand{\HiBandHi}{%.0f}' % HB['freq_hi_GHz'],
        r'\newcommand{\HiBandEirpLo}{%s}' % ('%.1f\\times10^{%d}' % (
            HB['eirp_lo_W'] / 10 ** int(math.floor(math.log10(HB['eirp_lo_W']))),
            int(math.floor(math.log10(HB['eirp_lo_W']))))),
        r'\newcommand{\HiBandEirpHi}{%s}' % ('%.1f\\times10^{%d}' % (
            HB['eirp_hi_W'] / 10 ** int(math.floor(math.log10(HB['eirp_hi_W']))),
            int(math.floor(math.log10(HB['eirp_hi_W']))))),
        r'\newcommand{\HiBandMaxT}{%.2f}' % HB['max_star_peak_snr']]
open(os.path.join(HERE, 'survey_numbers_round26.tex'), 'w').write('\n'.join(OUT4) + '\n')
print('\n'.join(OUT4))
