#!/usr/bin/env python3
"""R1-1 (v3.94): what extending the visibility-domain localisation test to
every threshold crossing requires, costed from what we actually hold.

Referee 1 asked for the test to be applied to all 75 threshold crossings
rather than only the 13 the spatial screen flagged, and asked that if the
products no longer exist we say exactly which subset can be tested and why.

CORRECTED in v3.94.  The previous version of this generator partitioned the
crossings by whether their execution block had been SEARCHED, on the
assumption that a searched block is a block we still hold.  That is wrong,
and printing it would have been an error of the kind this paper has been
caught by before: the pipeline deletes each measurement set after the
search completes, retaining only the products.  Searched is not held.
Checking the host directly, exactly two execution blocks retain visibility
data and neither of them contains a threshold crossing, so

    no crossing window's visibilities survive on disk,

and every one of the 62 untested crossings requires re-calibration from the
archive.  The two counts this changes (60 -> 62 windows, 50 -> 52 blocks)
are small, but the reasoning behind them was unsound and the partition is
now asserted to close rather than left to be read off three separate
numbers.

Writes survey_numbers_round54.tex.
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CAT = list(csv.DictReader(open(os.path.join(
    HERE, 'per_target_results_v3.94.csv'))))
OUT = os.path.join(HERE, 'survey_numbers_round54.tex')

# Number of execution blocks whose measurement sets survive on the pipeline
# host, and how many of those carry a threshold crossing.  Measured, not
# assumed: see the docstring.  If either changes, this must be re-measured.
N_EB_MS_SURVIVING = 2
N_EB_MS_SURVIVING_WITH_CROSSING = 0

cross = [r for r in CAT if r['crossing'] == 'True']
# The 13 that were tested were tested in flight, while their visibilities
# were still on disk; the flag and the test coincide for that reason.
tested = [r for r in cross if r['stage1_flag'] == 'True']
untested = [r for r in cross if r['stage1_flag'] != 'True']

# the partition must close, or one of the three numbers is wrong
assert len(tested) + len(untested) == len(cross), (
    'crossing partition does not close: %d tested + %d untested != %d '
    'crossings' % (len(tested), len(untested), len(cross)))
assert N_EB_MS_SURVIVING_WITH_CROSSING == 0, (
    'a crossing block now retains visibilities, so the claim that every '
    'untested crossing needs re-calibration is no longer true')

need_ebs = sorted({r['eb'] for r in untested})

sizes = {}
meta = json.load(open(os.path.join(HERE, 'archive_meta_v381.json')))
for v in meta['mous'].values():
    sizes.update(v.get('sizes') or {})
missing = [e for e in need_ebs if not sizes.get(e)]
assert not missing, (
    'no archive size for %d of the %d blocks needed (%s); the quoted volume '
    'would silently understate the job' % (len(missing), len(need_ebs),
                                           ', '.join(missing[:4])))
gb = sum(sizes[e] for e in need_ebs) / 1e9
# the campaign's own measured cost model, t = 384 s + 113 s/GB per block
hrs = (len(need_ebs) * 384.0 + gb * 113.0) / 3600.0

L = ['%% GENERATED by visextend_v394.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('VxNCross', '%d' % len(cross))
m('VxNTestedWin', '%d' % len(tested))
m('VxNUntestedWin', '%d' % len(untested))
m('VxNBlocks', '%d' % len(need_ebs))
m('VxNEbHeld', '%d' % N_EB_MS_SURVIVING)
m('VxTB', '%.2f' % (gb / 1000.0))
m('VxHours', '%.0f' % hrs)
open(OUT, 'w').writelines(L)

print('visextend: %d = %d tested + %d untested ; %d blocks, %.2f TB, %.0f h ; '
      '%d EBs retain visibilities, %d of them with a crossing'
      % (len(cross), len(tested), len(untested), len(need_ebs), gb / 1000.0,
         hrs, N_EB_MS_SURVIVING, N_EB_MS_SURVIVING_WITH_CROSSING))
