#!/usr/bin/env python3
"""Empirical calibration of the spatial-control null, and the rank CDF figure.

Referees asked for two things the paper did not have: the stage-1 expectation
recomputed from the observed held-out rank distribution instead of assumed
exchangeability, and a figure showing the rank distributions themselves.
Both are produced here from the released catalogue and the campaign export.
"""
import json, csv, math, os
import numpy as np
import matplotlib
matplotlib.use('Agg')
# Type 42 (TrueType): matplotlib's default Type 3 would fail the release gate
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

HO = json.load(open(os.path.join(HERE, 'heldout_v352.json')))['windows']
R = list(csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.61.csv'))))

# Null pool: every held-out window except the beta Pic CO detections, which are
# real astrophysical signal and must not calibrate a false-alarm rate.
null = [w for w in HO if not w.get('line_attributed')]
k = sum(1 for w in null if w.get('unattributed_stage1'))
n = len(null)
NW = len(R)
p_hat = k / n
LO, HI = 0.0253 / n, 3.689 / n          # exact Poisson limits for k = 1

M('RankCalN', '%d' % n)
M('RankCalK', '%d' % k)
M('RankCalRate', '%.2f' % (100.0 * p_hat))
M('RankCalOneIn', '%d' % round(1 / p_hat))
M('RankCalRatio', '%.1f' % (p_hat * 513))
M('RankCalExpIdeal', '%.2f' % (NW / 513))
M('RankCalExpEmp', '%.1f' % (NW * p_hat))
M('RankCalExpLo', '%.2f' % (NW * LO))
M('RankCalExpHi', '%.1f' % (NW * HI))
M('RankCalPgeOne', '%.0f' % (100 * (1 - math.exp(-NW * p_hat))))

# Is the displacement widespread or driven by a subset?
import collections, statistics as st
byst = collections.defaultdict(list)
for w in null:
    if w.get('p_star_empirical') is not None and not w.get('unattributed_stage1'):
        byst[w['star']].append(w['p_star_empirical'])
meds = {s: st.median(v) for s, v in byst.items()}
M('RankCalStarsBelow', '%d' % sum(1 for v in meds.values() if v < 0.5))
M('RankCalStarsN', '%d' % len(meds))

open(os.path.join(HERE, 'survey_numbers_round22.tex'), 'w').write(
    '%% Generated by v357_rankcal.py -- do not edit by hand.\n' + '\n'.join(OUT) + '\n')
print('\n'.join(OUT))

# ---------------------------------------------------------------- the figure
# v3.61: two panels.  (a) the rank CDFs, now including the PSEUDO-STARS --
# control positions at the inner edge of the annulus, ranked against the other
# controls -- which carry no star and so measure the instrumental part of the
# displacement.  (b) the radial profile of the control statistic itself, which
# is why the displacement exists: the star sits at a radius no control probe
# occupies.  Both come from radial_null_v361.json, which re-ranks stored
# products and starts no new search.
RAD = json.load(open(os.path.join(HERE, 'radial_null_v361.json')))
ho = np.array(sorted(w['p_star_empirical'] for w in null
                     if w.get('p_star_empirical') is not None))
sv = np.array(sorted(float(r['p_rank_addone']) for r in R
                     if r['p_rank_addone'] not in ('', 'nan')))
ps = np.array(sorted(RAD['arrays']['pseudo_heldout']))
fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.15))
ax = axes[0]
ax.plot([0, 1], [0, 1], color='0.55', lw=0.9, ls='--', label='uniform')
ax.step(sv, np.arange(1, sv.size + 1) / sv.size, where='post', lw=1.4,
        color='#1f4e9c', label='survey stars (%d)' % sv.size)
ax.step(ho, np.arange(1, ho.size + 1) / ho.size, where='post', lw=1.4,
        color='#c2432b', label='held-out stars (%d)' % ho.size)
ax.step(ps, np.arange(1, ps.size + 1) / ps.size, where='post', lw=1.4,
        color='#2e7d32', ls=':', label='held-out pseudo-stars (%d)' % ps.size)
ax.set_xlabel(r'add-one rank among the %d controls' % 512, fontsize=7.0)
ax.set_ylabel('cumulative fraction', fontsize=7.0)
ax.tick_params(labelsize=6.4)
ax.set_xlim(0, 1); ax.set_ylim(0, 1)
ax.legend(fontsize=5.9, loc='lower right', frameon=True, framealpha=0.9)
ax.set_title('(a) rank distributions', fontsize=7.2)

ax = axes[1]
for key, col, lab in (('profile', '#1f4e9c', 'survey'),
                      (None, '#c2432b', 'held out')):
    prof = RAD['profile'] if key else RAD['heldout']['profile']
    ax.plot(prof['u'], prof['z'], 'o-', ms=2.6, lw=1.3, color=col, label=lab)
ax.axvspan(0.0, RAD['r_in'], color='0.88', zorder=0)
ax.axvline(RAD['ustar']['u_median'], color='k', lw=1.1)
ax.text(RAD['r_in'] / 2.0, 0.5, 'no control probes\n(the star is here)',
        transform=ax.get_xaxis_transform(), ha='center', va='center',
        fontsize=5.8, rotation=90, color='0.25')
ax.set_xlabel(r'radius from the pointing centre ($\theta_{\rm PB}$)', fontsize=7.0)
ax.set_ylabel(r'control statistic ($\sigma$, window-normalised)', fontsize=7.0)
ax.tick_params(labelsize=6.4)
ax.set_xlim(0, 0.82)
ax.legend(fontsize=6.0, loc='upper center', frameon=True, framealpha=0.9, ncol=2)
ax.set_title('(b) the control level is radius-dependent', fontsize=7.2)
fig.tight_layout(pad=0.3)
fig.savefig(os.path.join(HERE, 'figures', 'rank_cdf.pdf'))
print('wrote figures/rank_cdf.pdf  (survey n=%d, held-out n=%d, pseudo n=%d)'
      % (sv.size, ho.size, ps.size))
