#!/usr/bin/env python3
"""R2-M3(b): the spectral-response correction, from the correlator response
rather than from an assumed kernel.

The paper models a channel as a top-hat convolved with the (1/4, 1/2, 1/4)
Hanning kernel. A tone at a channel boundary then splits 1/2 : 1/2 between
two channels before smoothing, and the smoothed peak channel retains

    1/2 x 1/2 + 1/4 x 1/2 = 0.375,

so C_resp runs 1/0.5 = 2.00 at a channel centre to 1/0.375 = 2.67 at a
boundary. The referee's objection is that this is not the correlator's
response. ALMA's spectra are the Fourier transform of a windowed lag
function, so the response to a monochromatic tone is the transform of that
window -- a sinc-like kernel sampled at the channel grid -- and the
worst-case (scalloping) loss of a Hann window is about 1.42 dB, i.e. a peak
fraction near 0.42 rather than 0.375. The adopted model is therefore too
pessimistic at the channel edges.

This generator settles it by computation rather than by assertion. It
builds a monochromatic tone, applies the lag-domain window, transforms, and
measures the fraction of total power landing in the peak channel as a
function of where the tone sits within that channel. No data are involved
and nothing here depends on the search products.

Two windows are evaluated:
  * uniform lag weighting followed by the (1/4, 1/2, 1/4) channel kernel,
    which is what ALMA calls Hanning smoothing and what the 12 m baseline
    correlator delivers by default;
  * the Hann-windowed lag function itself, which is the analytic form the
    referee points to.

Writes survey_numbers_round65.tex.
"""
import json
import math
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'survey_numbers_round65.tex')

NLAG = 4096          # lags; the answer is insensitive to this
OVER = 64            # sub-channel positions sampled across one channel


def peak_fraction(window, offsets):
    """Fraction of a tone's power in the peak channel, versus its position
    within that channel, for a given lag-domain window."""
    n = NLAG
    lag = np.arange(n)
    w = window(n)
    out = []
    for d in offsets:
        # a tone d channels from the centre of channel 0
        f = (np.arange(n) + d) / n
        sig = np.exp(2j * math.pi * f[0] * lag)
        # An ALMA channel is a DFT BIN of the windowed lag function, not an
        # integral of the continuous spectrum over the channel width. So the
        # channel values are the DFT samples themselves; padding and summing
        # would model a different instrument and gives a different answer.
        chan = np.abs(np.fft.fft(sig * w)) ** 2
        tot = chan.sum()
        out.append(float(chan.max() / tot) if tot else float('nan'))
    return np.array(out)


def uniform(n):
    return np.ones(n)


def hann(n):
    return np.hanning(n)


offs = np.linspace(0.0, 0.5, OVER)      # centre to boundary

# --- the adopted model, computed rather than assumed -------------------
# top-hat channel: a tone splits linearly between the two channels it
# straddles, then the (1/4, 1/2, 1/4) kernel is applied
def adopted(d):
    a, b = 1.0 - d, d                   # pre-smoothing split
    chans = np.array([0.0, a, b, 0.0])
    ker = np.array([0.25, 0.5, 0.25])
    sm = np.convolve(chans, ker, mode='same')
    return sm.max() / sm.sum()


adopt = np.array([adopted(d) for d in offs])

# --- the correlator's own response -------------------------------------
true_h = peak_fraction(hann, offs)

a_lo, a_hi = float(adopt.max()), float(adopt.min())      # centre, boundary
t_lo, t_hi = float(true_h.max()), float(true_h.min())

c_adopt_lo, c_adopt_hi = 1.0 / a_lo, 1.0 / a_hi
c_true_lo, c_true_hi = 1.0 / t_lo, 1.0 / t_hi
# uniform average over sub-channel position, which is the right average for
# a transmitter whose frequency is unknown
c_adopt_mean = float(np.mean(1.0 / adopt))
c_true_mean = float(np.mean(1.0 / true_h))

scallop_db = -10.0 * math.log10(t_hi / t_lo)

assert 0.3 < t_hi < 0.6, (
    'the computed worst-case peak fraction %.3f is outside any plausible '
    'range; the transform or the windowing is wrong' % t_hi)
assert c_true_hi < c_adopt_hi, (
    'the correlator response should be LESS pessimistic at the channel edge '
    'than the adopted top-hat model, but gives %.2f against %.2f'
    % (c_true_hi, c_adopt_hi))

L = ['%% GENERATED by cresp_v399.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('CrAdoptLo', '%.2f' % c_adopt_lo)
m('CrAdoptHi', '%.2f' % c_adopt_hi)
m('CrAdoptMean', '%.2f' % c_adopt_mean)
m('CrTrueLo', '%.2f' % c_true_lo)
m('CrTrueHi', '%.2f' % c_true_hi)
m('CrTrueMean', '%.2f' % c_true_mean)
m('CrAdoptEdgeFrac', '%.3f' % a_hi)
m('CrTrueEdgeFrac', '%.3f' % t_hi)
m('CrScallopDb', '%.2f' % scallop_db)
m('CrOverPct', '%.0f' % (100.0 * (c_adopt_hi / c_true_hi - 1.0)))
open(OUT, 'w').writelines(L)

json.dump(dict(adopted_centre=a_lo, adopted_edge=a_hi, true_centre=t_lo,
               true_edge=t_hi, c_adopt=[c_adopt_lo, c_adopt_hi],
               c_true=[c_true_lo, c_true_hi], scallop_db=scallop_db),
          open(os.path.join(HERE, 'cresp_v399.json'), 'w'), indent=1)

print('cresp: adopted model  peak fraction %.3f (centre) -> %.3f (edge)  '
      '=> C_resp %.2f-%.2f' % (a_lo, a_hi, c_adopt_lo, c_adopt_hi))
print('       correlator     peak fraction %.3f (centre) -> %.3f (edge)  '
      '=> C_resp %.2f-%.2f' % (t_lo, t_hi, c_true_lo, c_true_hi))
print('       scalloping loss %.2f dB; the adopted model is %.0f per cent '
      'too pessimistic at the edge' % (scallop_db,
                                       100.0 * (c_adopt_hi / c_true_hi - 1.0)))
