#!/usr/bin/env python3
r"""Recovery as a function of transmitter power and duty cycle.

Referee 1's eighth required change: convert "sensitivity falls steeply
below a duty cycle of about 0.1" into an explicit selection function,
C(P, f_dwell), so a reader can see at once that the quoted EIRP limits
apply to persistent or high-duty-cycle emission.

The dwell campaign measured recovery on a grid of injected amplitude and
dwell fraction; this draws the resulting surface with power expressed in
units of P_90, the quantity the paper quotes.

Writes figures/dwell_selection.pdf.
"""
import csv, glob, os, re

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

os.chdir(os.path.dirname(os.path.abspath(__file__)))
plt.rcParams.update({'pdf.fonttype': 42, 'ps.fonttype': 42,
                     'font.family': 'serif', 'font.serif': ['DejaVu Serif'],
                     'mathtext.fontset': 'dejavuserif'})

SRC = 'dwell_campaign_trials_v3.32.csv'
rows = list(csv.DictReader(open(SRC)))
cols = rows[0].keys()
amp_k = 'amp_sigma'
dwl_k = 'dwell'
# 'recovered_snr' is a number, not the outcome: picking it by a substring
# match made every trial read as a failure and the whole surface zero.
rec_k = next(c for c in cols if c.lower() in ('detected', 'recovered', 'hit'))

A = np.array([float(r[amp_k]) for r in rows])
D = np.array([float(r[dwl_k]) for r in rows])
Rv = np.array([1.0 if str(r[rec_k]).lower() in ('1', 'true', 'yes') else 0.0
               for r in rows])

au, du = np.unique(A), np.unique(D)
C = np.full((du.size, au.size), np.nan)
for i, d in enumerate(du):
    for j, a in enumerate(au):
        m = (D == d) & (A == a)
        if m.sum():
            C[i, j] = Rv[m].mean()

# Express amplitude in units of P90: the campaign amplitude is in units of
# the trigger, and P90 = 1.2 P_eff = 1.2 x 2.29 P_trig.
def texval(name):
    for f in sorted(glob.glob('survey_numbers*.tex')):
        m = re.search(r'\\newcommand\{\\%s\}\{([^}]*)\}' % name, open(f).read())
        if m:
            return m.group(1)
    return None


from inject_curve import P90_OVER_TRIG
P90_IN_TRIG = P90_OVER_TRIG * float(texval('HanFacMed'))
x = au / P90_IN_TRIG

fig, ax = plt.subplots(figsize=(3.4, 2.5))
levels = [0.1, 0.25, 0.5, 0.75, 0.9]
cf = ax.contourf(x, du, C, levels=np.linspace(0, 1, 11), cmap='viridis',
                 vmin=0, vmax=1)
cs = ax.contour(x, du, C, levels=levels, colors='w', linewidths=0.7)
ax.clabel(cs, fmt='%.2f', fontsize=5.4, inline=True)
ax.set_xscale('log')
from matplotlib.ticker import FixedLocator, FixedFormatter, NullFormatter
ax.xaxis.set_major_locator(FixedLocator([0.5, 1, 2, 5]))
ax.xaxis.set_major_formatter(FixedFormatter(['0.5', '1', '2', '5']))
ax.xaxis.set_minor_formatter(NullFormatter())
ax.set_xlabel('transmitter power / $P_{90}$', fontsize=7.4)
ax.set_ylabel('duty cycle $f_{\\rm dwell}$', fontsize=7.4)
ax.tick_params(labelsize=6.6)
ax.axvline(1.0, color='#b03030', ls=':', lw=0.9)
ax.text(1.06, 0.04, '$P_{90}$', color='#b03030', fontsize=6.2)
cb = fig.colorbar(cf, ax=ax, fraction=0.045, pad=0.02)
cb.set_label('recovery probability', fontsize=6.8)
cb.ax.tick_params(labelsize=6.0)
fig.savefig('figures/dwell_selection.pdf', bbox_inches='tight', pad_inches=0.02)
print('dwell_selection.pdf: amplitude %s, dwell %s, %d trials'
      % (au.min(), du.min(), len(rows)))
print('  P90 in trigger units: %.2f' % P90_IN_TRIG)
# The caption quotes this product; emit it rather than let it be typed.
open('survey_numbers_round40.tex', 'w').write(
    '%% GENERATED by make_fig_dwell2d.py -- do not hand-edit.\n'
    '\\newcommand{\\PNinetyInTrig}{%.2f}\n' % P90_IN_TRIG)
