#!/usr/bin/env python3
r"""The radius-corrected statistic, over ALL windows, as the primary analysis.

Referee 2's first required change. The released statistic divides every
position in a window by one global noise scale, while the true
primary-beam-corrected noise varies with radius across the annulus the
controls occupy. The bias is real and measured: out of sample the star's
add-one rank has median 0.405 against 0.5. A fix demonstrated on thirteen
flagged windows and a twenty-five window spot check is not enough to
license the claim that the bias is immaterial; the corrected statistic has
to define the candidate list for the whole survey.

The probes come from one fixed seed, so every stored control value can be
paired with its radius. Each probe is standardised within its own radius
bin and the star on the innermost bin, which removes the gradient by
construction and introduces no free parameter.

Writes localnorm_all_v385.json and survey_numbers_round34.tex.
"""
import csv, json

import numpy as np

# The statistic itself lives in localnorm_core.py, because the catalogue
# writer needs the identical arithmetic and runs long before this file.
from localnorm_core import NPROBE, SEL, FLOOR, local_rank, global_rank

EXP = json.load(open('frozen_export_v3.81_survey.json'))['rows']
CAT = {}
for r in csv.DictReader(open('per_target_results_v3.95.csv')):
    CAT[(r['eb'], round(min(float(r['flo_GHz']), float(r['fhi_GHz'])), 4))] = r

seen = set()
n = 0
gflag = lflag = both = gained = lost = 0
ranks_g, ranks_l = [], []
changed = []
for r in EXP:
    c = np.asarray(r.get('ctrl_all') or [], float)
    if c.size != NPROBE or r['star_snr'] is None:
        continue
    key = (r['eb'], round(min(r['flo'], r['fhi']), 4))
    cat = CAT.get(key)
    if cat is None or key in seen:
        continue
    seen.add(key)
    n += 1
    g = global_rank(r['star_snr'], c)
    l = local_rank(r['star_snr'], c)
    ranks_g.append(g)
    ranks_l.append(l)
    # A stage-1 outlier is rank-first AND above the trigger; a rank-first
    # window below T*=5 is not a candidate event under either statistic.
    cross = r['star_snr'] >= 5.0
    fg, fl = (g <= FLOOR and cross), (l <= FLOOR and cross)
    gflag += fg
    lflag += fl
    both += (fg and fl)
    if fg and not fl:
        lost += 1
        changed.append(dict(star=cat['star_name'].split('  Gaia')[0].strip(),
                            band=cat['band'], eb=r['eb'], how='lost',
                            tstar=r['star_snr'], rank_g=g, rank_l=l))
    if fl and not fg:
        gained += 1
        changed.append(dict(star=cat['star_name'].split('  Gaia')[0].strip(),
                            band=cat['band'], eb=r['eb'], how='gained',
                            tstar=r['star_snr'], rank_g=g, rank_l=l))

rg, rl = np.array(ranks_g), np.array(ranks_l)
res = dict(n_windows=n,
           flag_global=gflag, flag_local=lflag, flag_both=both,
           lost=lost, gained=gained,
           med_rank_global=float(np.median(rg)),
           med_rank_local=float(np.median(rl)),
           changed=changed)
# The released catalogue carries the same statistic in a column; assert the
# two agree, so that a reader reproducing the candidate list from the file
# alone gets the list this paper reports.
_catloc = sum(1 for r in CAT.values() if r.get('stage1_flag_local') == 'True')
_catglo = sum(1 for r in CAT.values() if r.get('stage1_flag') == 'True')
assert _catloc == lflag, 'catalogue local flags %d != %d' % (_catloc, lflag)
assert _catglo == gflag, 'catalogue global flags %d != %d' % (_catglo, gflag)

json.dump(res, open('localnorm_all_v385.json', 'w'), indent=1)

M = ['\\newcommand{\\LocAllWin}{%d}' % n,
     '\\newcommand{\\LocAllFlagGlobal}{%d}' % gflag,
     '\\newcommand{\\LocAllFlagLocal}{%d}' % lflag,
     '\\newcommand{\\LocAllBoth}{%d}' % both,
     '\\newcommand{\\LocAllLost}{%d}' % lost,
     '\\newcommand{\\LocAllGained}{%d}' % gained,
     '\\newcommand{\\LocAllMedGlobal}{%.3f}' % float(np.median(rg)),
     '\\newcommand{\\LocAllMedLocal}{%.3f}' % float(np.median(rl))]
open('survey_numbers_round34.tex', 'w').write(
    '% generated by localnorm_all_v385.py -- do not edit\n' + '\n'.join(M) + '\n')
print('windows %d | STAGE-1 global %d, local %d, both %d | lost %d gained %d'
      % (n, gflag, lflag, both, lost, gained))
print('median add-one rank: global %.3f -> local %.3f'
      % (np.median(rg), np.median(rl)))
for d in changed:
    print('   %-6s %-14s B%-2s T*=%6.2f  %.4f -> %.4f'
          % (d['how'], d['star'][:14], d['band'], d['tstar'],
             d['rank_g'], d['rank_l']))
