#!/usr/bin/env python3
"""One table: all thirteen stage-1 events and their outcome at every stage.

Referee 1, point 4. The fate of the thirteen is the strongest part of the
result and it was spread over four tables and several pages of discussion.
A reader should be able to look at one object and see why each event was
rejected.

The columns are the pipeline of Section 4.2, in order:

  trigger     T* at the stellar position
  screen      does the star outrank all 512 controls
  localise    does the drift-following, continuum-subtracted visibility fit
              put the emission at the stellar position
  veto        is there an astrophysical identification
  recur       does it repeat at the same tuning in another block

Everything is read from the released catalogue and the two visibility
records; nothing is typed.
"""
import csv, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROWS = [r for r in csv.DictReader(open(os.path.join(HERE,
        'per_target_results_v3.95.csv'))) if r['stage1_flag'] == 'True']
FIT = json.load(open(os.path.join(HERE, 'visfit_all_v385.json')))
UNI = json.load(open(os.path.join(HERE, 'vistest_v385.json')))
OUT = []
def M(n, v): OUT.append(r'\newcommand{\%s}{%s}' % (n, v))

TIDY = {'bet Pic': r'$\beta$~Pic', 'CP-72 2713': r'CP$-$72~2713',
        'HD 23484 Gaia DR3 4856592239127350400': 'HD 23484',
        'HD14055': 'HD~14055', 'HD 48370': 'HD~48370', '61 Vir': '61 Vir',
        'LP 736-15': 'LP 736-15'}


def tidy(n):
    n = ' '.join(str(n).split())
    return TIDY.get(n, n.split('  Gaia')[0])


def by_eb(store):
    out = {}
    for k, v in store.items():
        if isinstance(v, dict) and v.get('event'):
            out[v['event']['eb']] = v
    return out


F, U = by_eb(FIT), by_eb(UNI)

# repeat coverage, matched on the window as Section 5.3 does
BYNAME = {}
for r in csv.DictReader(open(os.path.join(HERE, 'per_target_results_v3.95.csv'))):
    BYNAME.setdefault(r['star_name'], []).append(r)


def repeats(r):
    lo, hi = sorted((float(r['flo_GHz']), float(r['fhi_GHz'])))
    return [q for q in BYNAME[r['star_name']] if q['eb'] != r['eb']
            and min(float(q['flo_GHz']), float(q['fhi_GHz'])) <= lo + 0.02
            and max(float(q['flo_GHz']), float(q['fhi_GHz'])) >= hi - 0.02]


rows = sorted(ROWS, key=lambda r: -float(r['star_snr']))
lines = [r'\begin{tabular}{@{}llrcccl@{}}', r'\toprule',
         r'Star & B & $T_\star$ & screen & localised & attributed & '
         r'recurs \\', r'\midrule']
n_loc, n_att, n_rec, n_surv = 0, 0, 0, 0
for r in rows:
    eb = r['eb']
    fit = F.get(eb)
    # localisation: the sensitive estimator, with the uniform one as a
    # fallback where the track is too wide to reference
    if fit and abs(fit['star']['snr_re']) >= 0.01:
        st = fit['star']
        loc = (st['snr_re'] >= 3.0 and abs(st['snr_im']) <= 2.5)
        lab = r'\checkmark' if loc else r'$\times$'
    else:
        lab = r'n/a$^{a}$'
        loc = False
    n_loc += loc
    att = bool(r['nearest_line']) and r['line_offset_kms'] and \
        abs(float(r['line_offset_kms'])) <= 50
    n_att += att
    rep = repeats(r)
    if not rep:
        rlab = 'no repeat'
        rec = None
    else:
        best = max(float(q['star_snr']) for q in rep)
        rec = best >= 5.0
        n_rec += bool(rec)
        rlab = (r'\checkmark (%d, $T_\star=%.1f$)' % (len(rep), best) if rec
                else r'$\times$ (%d, $T_\star\leq%.2f$)' % (len(rep), best))
    lines.append('%s & %s & %.2f & %s & %s & %s & %s \\\\'
                 % (tidy(r['star_name']), r['band'], float(r['star_snr']),
                    r'\checkmark', lab,
                    r'\checkmark' if att else r'$\times$', rlab))
lines += [r'\bottomrule', r'\end{tabular}']
open(os.path.join(HERE, 'tab_stages_v386.tex'), 'w').write('\n'.join(lines) + '\n')

M('NStageTableRows', '%d' % len(rows))
M('NStageLocalised', '%d' % n_loc)
M('NStageAttributed', '%d' % n_att)
M('NStageSurvivors', '%d' % n_surv)
M('NStageRecurs', '%d' % n_rec)
M('NStageNoRepeat',
  '%d' % sum(1 for r in rows if not repeats(r)))
open(os.path.join(HERE, 'survey_numbers_round45.tex'), 'w').write(
    '%% GENERATED by stagetable_v386.py -- do not hand-edit.\n'
    + '\n'.join(OUT) + '\n')

print('stage table: %d events' % len(rows))
print('  localised at the star : %d' % n_loc)
print('  astrophysically attributed: %d' % n_att)
print('  surviving every stage : %d' % n_surv)
print('table -> tab_stages_v386.tex; macros -> survey_numbers_round45.tex')
