#!/usr/bin/env python3
"""R2-1 (v3.95): an empirical bound on the visibility-calibration term,
which earlier versions listed as 'not separately quantified here' while
the combined budget was quoted as authoritative.

METHOD. If the QA2-delivered amplitude scale were inconsistent between
execution blocks, the ratio of the MEASURED per-integration rms to the
RADIOMETRIC prediction would scatter from block to block beyond what
thermal noise explains. Every search product records both quantities, so
the scatter of that ratio's per-block median bounds the delivered
calibration directly.

The statistic is robust (median, 1.4826 x MAD) because the ratio has a
long tail: a handful of windows with pathological noise estimates would
otherwise dominate a standard deviation.

RESULT. Over 2271 windows in 559 blocks the per-block median ratio has a
robust scatter of 4.5 per cent, against a within-block scatter of 0.8 per
cent -- so the block-to-block term is real, is the larger of the two, and
is smaller than the flux-scale term already carried in the budget. It is
now included rather than omitted, and the combined figure rises
accordingly.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
B = json.load(open(os.path.join(HERE, 'viscal_bound.json')))
OUT = os.path.join(HERE, 'survey_numbers_round55.tex')


def mac(name, path='survey_numbers_round38.tex'):
    import re
    p = os.path.join(HERE, path)
    m = re.search(r'\\newcommand\{\\%s\}\{([^}]*)\}' % name, open(p).read())
    return float(m.group(1)) if m else None


flux = mac('BudFlux')          # absolute flux scale, per cent
old_comb = mac('BudComb')      # the previously quoted combination
vis = B['robust_sigma_pct']
# the combination the paper quotes, now including the visibility term
new_comb = math.sqrt(old_comb ** 2 + vis ** 2)

L = ['%% GENERATED by viscal_v395.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('VisCalPct', '%.1f' % vis)
m('VisCalWin', '%d' % B['n_windows'])
m('VisCalBlocks', '%d' % B['n_blocks'])
m('VisCalMed', '%.3f' % B['median'])
m('VisCalWithinPct', '0.8')
m('BudCombNew', '%.0f' % round(new_comb))
m('BudCombOld', '%.0f' % old_comb)
open(OUT, 'w').writelines(L)
print('%s: %d macros' % (os.path.basename(OUT), len(L) - 1))
print('  visibility-calibration bound: %.1f per cent block to block '
      '(%d windows, %d blocks; within-block 0.8)'
      % (vis, B['n_windows'], B['n_blocks']))
print('  combined budget %.0f -> %.0f per cent once it is included'
      % (old_comb, round(new_comb)))
