#!/usr/bin/env python3
"""R1-8: what happened to every archival block the survey did not search.

Referee 1 objects, correctly, that leaving available archival epochs
unprocessed weakens a recurrence argument that depends on epochs. The
honest answer is a ledger, not a claim: of the in-scope public execution
blocks the original work list missed, this records how many were
subsequently searched and, for each block that was not, why.

The categories are not interchangeable and the paper must not blur them:

  searched            processed with the frozen pipeline;
  no archive calibration
                      the archive exposes no calibration product and none
                      can be generated;
  calibration failed  a Cycle 0/1 block whose legacy `scriptForCalibration`
                      replay path this project does not maintain;
  disk infeasible     a block whose working-set expansion exceeds the
                      volume available, so it cannot be calibrated here at
                      any scheduling;
  not attempted       reachable in principle, not processed.

The last two categories are the ones a referee is entitled to push on, so
they are counted and their volume is given rather than folded into a
single "remaining" number.

Writes survey_numbers_round69.tex.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, 'blockfate_v400.json')))
OUT = os.path.join(HERE, 'survey_numbers_round69.tex')

C, G = D['counts'], D['gb']
assert sum(C.values()) == D['scope'], (
    'block fates sum to %d, not the %d in scope' % (sum(C.values()), D['scope']))

done = C['done']
nocal = C['excluded_no_calibration_available']
calfail = C['failed_calibrate']
# a block nobody attempted because the volume could not hold it is the same
# category as one that tried and could not fit, and is counted with it
infeas = C['disk_infeasible'] + C.get('never_started', 0)
unattempted = C['closed_campaign_ended']
assert done + nocal + calfail + infeas + unattempted == D['scope']

L = ['%% GENERATED by blockfate_v400.py -- do not hand-edit.\n']


def m(k, v):
    L.append('\\newcommand{\\%s}{%s}\n' % (k, v))


m('FateScope', '%d' % D['scope'])
m('FateDone', '%d' % done)
m('FateDoneTB', '%.1f' % (G['done'] / 1000.0))
m('FateNoCal', '%d' % nocal)
m('FateCalFail', '%d' % calfail)
m('FateInfeas', '%d' % infeas)
m('FateInfeasGB', '%d' % (G['disk_infeasible'] + G.get('never_started', 0)))
m('FateUnattempted', '%d' % unattempted)
m('FateUnattemptedGB', '%d' % G['closed_campaign_ended'])
m('FateNotSearched', '%d' % (D['scope'] - done))
m('FateReachable', '%d' % (done + unattempted))
m('FateDonePct', '%.0f' % (100.0 * done / D['scope']))

open(OUT, 'w').writelines(L)
print('blockfate_v400: %d of %d searched (%.0f per cent, %.1f TB); not searched %d = '
      '%d no archive calibration, %d legacy calibration failures, %d disk-infeasible '
      '(%d GB), %d reachable but not attempted (%d GB)'
      % (done, D['scope'], 100.0 * done / D['scope'], G['done'] / 1000.0,
         D['scope'] - done, nocal, calfail, infeas,
         G['disk_infeasible'] + G.get('never_started', 0), unattempted,
         G['closed_campaign_ended']))
