#!/usr/bin/env python3
r"""Macros for the CP-72 2713 recurrence test (cycle 2, folded in after the
main revision run).

Input: cp72_recurrence_v344.json, a frozen record of a search of the second,
previously unsearched public execution block of MOUS uid://A001/X2d20/X2e25.
That block, A002_Xff0235_X502d (49.46 GB), was declined by the per-target
download budget during the survey; the pipeline log records
"SKIPPING ..._X502d (49.5 GB): would exceed this target's 85 GB download
budget".  It was calibrated and searched afterwards with the UNMODIFIED
release pipeline in an isolated target directory, so the two epochs are
directly comparable: same window, channel width, channel count and number of
integrations, and therefore the same channel index for the feature.

Products retained on the processing host under
/data/SETI/targets/CP-72_2713_EB2/products/ for audit.
"""
import json

R = json.load(open('cp72_recurrence_v344.json'))

# The comparison is only clean because the configuration matches exactly.
assert R['nchan'] == 3534 and R['n_int'] == 495, 'configuration mismatch'
assert abs(R['chanw_kHz'] - 488.28125) < 1e-6, 'channel width mismatch'

M = [
    ('CpRecEb',        R['eb'].replace('_', r'\_')),
    ('CpRecGB',        '49.5'),
    ('CpRecNInt',      '%d' % R['n_int']),
    ('CpRecNChan',     '%s' % format(R['nchan'], ',').replace(',', r'\,')),
    ('CpRecChanwkHz',  '%.2f' % R['chanw_kHz']),
    ('CpRecChan',      '%d' % R['feature_chan']),
    # the statistic at the feature frequency, second epoch, against 5.81 first
    ('CpRecT',         '%.2f' % R['T_at_feature']),
    ('CpRecCtrlMed',   '%.2f' % R['ctrl_pct'][0]),
    ('CpRecCtrlMax',   '%.2f' % R['ctrl_pct'][3]),
    ('CpRecWinPeak',   '%.2f' % R['window_peak']),
    ('CpRecWinPeakGHz', '%.4f' % R['window_peak_GHz']),
    ('CpRecHits',      '%d' % R['n_hits']),
]
with open('survey_numbers_recurrence.tex', 'w') as f:
    f.write('%% GENERATED by recurrence_calc.py -- do not hand-edit.\n')
    for k, v in M:
        f.write('\\newcommand{\\%s}{%s}\n' % (k, v))

print('second epoch at the feature frequency: T* = %.2f (first epoch 5.81)'
      % R['T_at_feature'])
print('  control percentiles 50/90/99/100: %s' %
      ' / '.join('%.2f' % x for x in R['ctrl_pct']))
print('  window peak %.2f at %.4f GHz, hits above threshold %d, detection %s'
      % (R['window_peak'], R['window_peak_GHz'], R['n_hits'], R['detection']))
print('  -> the second-epoch value at the feature frequency lies BELOW the '
      'median of the 512 controls')
print('macros -> survey_numbers_recurrence.tex')
